import * as Store from '../assets/js/store.js';
import { el, card } from '../assets/js/ui.js';
const W={N1:50,N2:30,N3:15,bonus:10};
const N1=['work','school','brief','epfc','nl','review','supp_morning','supp_evening','exam'];
const N2=['coding','ai','iot','repair','proof','vinted','supp_focus','savings','finance','focus'];
const N3=['sport','admin','chess','reading'];
const D={work:'routine',school:'routine',brief:'routine',review:'routine',supp_morning:'routine',supp_evening:'routine',epfc:'étude',nl:'langues',coding:'tech',ai:'tech',iot:'tech',repair:'tech',proof:'étude',vinted:'argent',savings:'argent',finance:'argent',sport:'sport',chess:'loisir',reading:'loisir',water:'fuel',protein:'fuel'};
export function priority(id){if(N1.includes(id))return'N1';if(N2.includes(id))return'N2';if(N3.includes(id))return'N3';return'N3'}
export function xpFor(id){return W[priority(id)]||W.bonus}
export function domainFor(id,fallback='routine'){return D[id]||fallback}
export function rankFor(xp){if(xp<500)return{rank:'Recrue',level:1,next:500};if(xp<1500)return{rank:'Bronze',level:2,next:1500};if(xp<3500)return{rank:'Argent',level:3,next:3500};if(xp<7000)return{rank:'Or',level:4,next:7000};if(xp<12000)return{rank:'Platine',level:5,next:12000};if(xp<20000)return{rank:'Diamant',level:6,next:20000};if(xp<35000)return{rank:'Élite',level:7,next:35000};return{rank:'Ultime',level:8,next:null}}
function add(items,id,domain,prio,xp){items.push({id,domain,priority:prio,xp});return xp}
export function dailyScore(date=Store.today()){let xp=0;const items=[];const routine=Store.get('routine_'+date,{done:{}});Object.entries(routine.done||{}).forEach(([id,done])=>{if(done){const p=priority(id),v=xpFor(id);xp+=add(items,id,domainFor(id,'routine'),p,v)}});const fuel=Store.get('fuel_'+date,{water:0,protein:0});if((+fuel.water||0)>=3000)xp+=add(items,'water','fuel','N2',25);if((+fuel.protein||0)>=150)xp+=add(items,'protein','fuel','N2',25);Store.sportSessions().filter(s=>s.date===date).forEach(s=>xp+=add(items,'sport_session','sport','N3',s.status==='completed'?40:s.status==='deload'?25:15));Store.get('chess_elo_history',[]).filter(x=>x.date===date).forEach(()=>xp+=add(items,'chess_log','loisir','N3',15));Store.get('chess_games',[]).filter(x=>x.date===date).forEach(x=>xp+=add(items,'chess_game','loisir','N3',(+x.puzzles||0)>=10?15:10));Store.get('reading_activity',[]).filter(x=>x.date===date).forEach(x=>{const p=Math.min(30,Math.ceil((+x.pages||0)/5)*5)+(x.finished?30:0)+(x.action?10:0);xp+=add(items,'reading_pages','loisir','N3',p)});Store.get('study_activity',[]).filter(x=>x.date===date).forEach(x=>{if(x.domain==='error_bank')xp+=add(items,'review_error','étude','N2',20);else if(['coding','ai','iot','repair'].includes(x.domain))xp+=add(items,x.domain,'tech','N2',Math.min(45,+x.minutes||25));else if(['epfc','nl'].includes(x.domain))xp+=add(items,x.domain,x.domain==='nl'?'langues':'étude','N1',30);});Store.get('savings_history',[]).filter(x=>x.date===date).forEach(x=>{if((+x.amount||0)>0)xp+=add(items,'savings','argent','N2',30)});return{date,xp,items}}
export function knownDates(){const set=new Set([Store.today()]);const all=Store.all();Object.keys(all).forEach(k=>{const m=k.match(/(\d{4}-\d{2}-\d{2})/);if(m)set.add(m[1])});Store.sportSessions().forEach(x=>x.date&&set.add(x.date));['chess_elo_history','chess_games','savings_history','reading_activity','study_activity'].forEach(k=>Store.get(k,[]).forEach(x=>x.date&&set.add(x.date)));return[...set].sort()}
function dayMinus(i){const d=new Date(Store.today());d.setDate(d.getDate()-i);return d.toISOString().slice(0,10)}
export function lastDays(n=7){const out=[];for(let i=n-1;i>=0;i--)out.push(dayMinus(i));return out}
export function totalXp(){return knownDates().reduce((a,d)=>a+dailyScore(d).xp,0)}
export function weekXp(){return lastDays(7).reduce((a,d)=>a+dailyScore(d).xp,0)}
export function domainScore(days=lastDays(7)){const out={routine:0,étude:0,tech:0,langues:0,sport:0,fuel:0,argent:0,loisir:0};days.forEach(d=>dailyScore(d).items.forEach(x=>{out[x.domain]=(out[x.domain]||0)+x.xp}));return out}
export function priorityScore(days=lastDays(7)){const out={N1:0,N2:0,N3:0};days.forEach(d=>dailyScore(d).items.forEach(x=>{if(out[x.priority]!==undefined)out[x.priority]+=1}));return out}
export function weakDomains(){const s=domainScore();return Object.entries(s).filter(([k,v])=>v<60).sort((a,b)=>a[1]-b[1]).map(([domain,xp])=>({domain,xp}))}
export function globalScore(){const s=domainScore(),w=weakDomains().length,xp=weekXp();let score=Math.min(100,Math.round(xp/900*100));score-=Math.min(30,w*5);if(s.fuel<80)score-=10;if(s.routine<120)score-=10;return Math.max(0,score)}
export function streak(type='daily'){let n=0;for(let i=0;i<365;i++){const d=dayMinus(i),s=dailyScore(d);const ok=type==='daily'?s.xp>0:type==='n1'?s.items.some(x=>x.priority==='N1'):type==='sport'?Store.sportSessions().some(x=>x.date===d&&x.status==='completed'):type==='study'?s.items.some(x=>['epfc','nl','coding','ai','iot','repair','proof','review_error'].includes(x.id)):false;if(ok)n++;else break}return n}
export function gameSummary(){const xp=totalXp(),r=rankFor(xp),today=dailyScore(),domains=domainScore(),weak=weakDomains();return{xp,rank:r.rank,level:r.level,next:r.next,todayXp:today.xp,weekXp:weekXp(),global:globalScore(),domains,weak,items:today.items,streakDaily:streak('daily'),streakN1:streak('n1'),streakSport:streak('sport'),streakStudy:streak('study')}};
export function renderGameCard(){const g=gameSummary();const pct=g.next?Math.min(100,Math.round(g.xp/g.next*100)):100;const c=card('XP / Classement','Score global '+g.global+'/100 · rang '+g.rank+' · niveau '+g.level+' · XP total '+g.xp+' · aujourd’hui '+g.todayXp+' · semaine '+g.weekXp);c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct+'%'})));c.append(el('div',{class:'small muted'},(g.next?'Prochain rang: '+g.next+' XP':'Rang maximum')+' · série jour '+g.streakDaily+' · N1 '+g.streakN1+' · sport '+g.streakSport+' · étude '+g.streakStudy));if(g.weak.length)c.append(el('div',{class:'exercise warn'},'Faible: '+g.weak.slice(0,4).map(x=>x.domain+' '+x.xp+' XP').join(' · ')));return c}
export function nextRoutineAction(plan,done){return plan.find(x=>!done[x.id])||null}
