import * as Store from '../assets/js/store.js';
import { el, card } from '../assets/js/ui.js';
const W={N1:50,N2:30,N3:15,bonus:10};
const N1=['work','school','brief','epfc','nl','review','supp_morning','supp_evening'];
const N2=['coding','ai','iot','repair','proof','vinted','supp_focus','savings'];
const N3=['sport','admin','chess','reading'];
export function priority(id){if(N1.includes(id))return'N1';if(N2.includes(id))return'N2';if(N3.includes(id))return'N3';return'N3'}
export function xpFor(id){return W[priority(id)]||W.bonus}
export function rankFor(xp){if(xp<500)return{rank:'Recrue',level:1,next:500};if(xp<1500)return{rank:'Bronze',level:2,next:1500};if(xp<3500)return{rank:'Argent',level:3,next:3500};if(xp<7000)return{rank:'Or',level:4,next:7000};if(xp<12000)return{rank:'Platine',level:5,next:12000};if(xp<20000)return{rank:'Diamant',level:6,next:20000};if(xp<35000)return{rank:'Élite',level:7,next:35000};return{rank:'Ultime',level:8,next:null}}
function add(items,id,domain,priority,xp){items.push({id,domain,priority,xp});return xp}
export function dailyScore(date=Store.today()){let xp=0;const items=[];const routine=Store.get('routine_'+date,{done:{}});Object.entries(routine.done||{}).forEach(([id,done])=>{if(done){const p=priority(id);xp+=add(items,id,'routine',p,xpFor(id))}});const fuel=Store.get('fuel_'+date,{water:0,protein:0});if((+fuel.water||0)>=3000)xp+=add(items,'water','fuel','N2',25);if((+fuel.protein||0)>=150)xp+=add(items,'protein','fuel','N2',25);Store.sportSessions().filter(s=>s.date===date).forEach(s=>xp+=add(items,'sport_session','sport','N3',s.status==='completed'?40:15));Store.get('chess_elo_history',[]).filter(x=>x.date===date).forEach(()=>xp+=add(items,'chess_log','loisir','N3',15));Store.get('chess_games',[]).filter(x=>x.date===date).forEach(()=>xp+=add(items,'chess_game','loisir','N3',10));Store.get('reading_activity',[]).filter(x=>x.date===date).forEach(x=>{const p=Math.min(30,Math.ceil((+x.pages||0)/5)*5)+(x.finished?30:0)+(x.action?10:0);xp+=add(items,'reading_pages','loisir','N3',p)});Store.get('study_activity',[]).filter(x=>x.date===date&&x.domain==='error_bank').forEach(()=>xp+=add(items,'review_error','étude','N2',20));Store.get('savings_history',[]).filter(x=>x.date===date).forEach(x=>{const v=(+x.amount||0)>0?30:0;if(v)xp+=add(items,'savings','finance','N2',v)});return{date,xp,items}}
export function knownDates(){const set=new Set([Store.today()]);const all=Store.all();Object.keys(all).forEach(k=>{const m=k.match(/(\d{4}-\d{2}-\d{2})/);if(m)set.add(m[1])});Store.sportSessions().forEach(x=>x.date&&set.add(x.date));['chess_elo_history','chess_games','savings_history','reading_activity','study_activity'].forEach(k=>Store.get(k,[]).forEach(x=>x.date&&set.add(x.date)));return[...set].sort()}
export function totalXp(){return knownDates().reduce((a,d)=>a+dailyScore(d).xp,0)}
export function weekXp(){const now=new Date(Store.today());return knownDates().filter(d=>(now-new Date(d))/86400000<7).reduce((a,d)=>a+dailyScore(d).xp,0)}
function dateMinus(i){const d=new Date(Store.today());d.setDate(d.getDate()-i);return d.toISOString().slice(0,10)}
export function streak(type='daily'){let n=0;for(let i=0;i<365;i++){const d=dateMinus(i),s=dailyScore(d);const ok=type==='daily'?s.xp>0:type==='n1'?s.items.some(x=>x.priority==='N1'):type==='sport'?Store.sportSessions().some(x=>x.date===d&&x.status==='completed'):type==='study'?s.items.some(x=>['epfc','nl','coding','ai','iot','repair','proof','review_error'].includes(x.id)):false;if(ok)n++;else break}return n}
export function gameSummary(){const xp=totalXp(),r=rankFor(xp),today=dailyScore();return{xp,rank:r.rank,level:r.level,next:r.next,todayXp:today.xp,weekXp:weekXp(),items:today.items,streakDaily:streak('daily'),streakN1:streak('n1'),streakSport:streak('sport'),streakStudy:streak('study')}}
export function renderGameCard(){const g=gameSummary();const pct=g.next?Math.min(100,Math.round(g.xp/g.next*100)):100;const c=card('XP / Classement','Rang '+g.rank+' · Niveau '+g.level+' · XP total '+g.xp+' · aujourd’hui '+g.todayXp+' · semaine '+g.weekXp);c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct+'%'})));c.append(el('div',{class:'small muted'},(g.next?'Prochain rang: '+g.next+' XP':'Rang maximum')+' · série jour '+g.streakDaily+' · N1 '+g.streakN1+' · sport '+g.streakSport+' · étude '+g.streakStudy));return c}
export function nextRoutineAction(plan,done){return plan.find(x=>!done[x.id])||null}
