import { EPFC_YEAR1 } from '../assets/js/epfc-year1.js';
import { EPFC_DAILY_ROTATION } from '../assets/js/practice-catalog.js';
import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import { SPORT_CYCLE } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, toast, isSimple, actionRow, kpi as uiKpi, compactTable } from '../assets/js/ui.js';
import { renderGameCard } from './game.js';
const ROUTINE_IDS=new Set(['epfc','coding','ai','iot','repair','nl','sport','vinted','proof','review','chess','reading','savings']);
export function renderHome(root,refresh){const day=homeDay(),plan=buildPlan(),doneMap=mergedDone(day),ranked=rankActions(plan,doneMap),done=plan.filter(x=>doneMap[x.id]).length,score=Math.round(done/plan.length*100),next=ranked[0];root.append(hero(day,plan,doneMap,next,score,refresh));root.append(kpiRow(plan,doneMap));const layout=el('div',{class:'grid'});layout.append(commandCard(ranked,day,doneMap,refresh));layout.append(section('N1 · vital',rankActions(plan.filter(x=>x.p==='N1'),doneMap),day,doneMap,refresh,'span-6'));if(isSimple())layout.append(simpleNext(ranked,day,doneMap,refresh));else{layout.append(section('N2 · progression',rankActions(plan.filter(x=>x.p==='N2'),doneMap),day,doneMap,refresh,'span-6'));layout.append(section('N3 · bonus',rankActions(plan.filter(x=>x.p==='N3'),doneMap),day,doneMap,refresh,'span-6'));layout.append(opsCard())}root.append(layout);if(!isSimple())root.append(notes(day,refresh))}
function hero(day,plan,doneMap,next,score,refresh){const c=card('Cockpit',next?'À faire maintenant: '+next.title:'Journée complétée.','span-12 module-hero');c.className+=' '+(next?'warn':'ok');const rail=el('div',{class:'action-rail'});rail.append(uiKpi('Avancement',score+'%',plan.filter(x=>doneMap[x.id]).length+'/'+plan.length+' blocs',score>=80?'ok':score>=45?'warn':'danger'));rail.append(uiKpi('Priorité',next?next.p:'OK',next?next.title:'RAS',next?.p==='N1'?'danger':next?'warn':'ok'));rail.append(uiKpi('Fuel',fuelText(),'eau / protéines',fuelOk()?'ok':'warn'));c.append(rail);if(!isSimple())c.append(renderGameCard());if(next)c.append(actionLine(next,day,doneMap,refresh,true));return c}
function commandCard(ranked,day,doneMap,refresh){const c=card('File d’action','Triée par urgence réelle, pas par catégorie.','span-6');const list=ranked.slice(0,isSimple()?4:7);if(!list.length)c.append(el('div',{class:'empty-state'},'Aucune action restante.'));list.forEach(x=>c.append(actionLine(x,day,doneMap,refresh)));return c}
function simpleNext(ranked,day,doneMap,refresh){const c=card('Ensuite','Secondaires utiles, déjà triées.','span-6');ranked.filter(x=>x.p!=='N1').slice(0,4).forEach(x=>c.append(actionLine(x,day,doneMap,refresh)));return c}
function kpiRow(plan,doneMap){const g=el('div',{class:'grid'}),n1=count(plan,doneMap,'N1'),n2=count(plan,doneMap,'N2'),n3=count(plan,doneMap,'N3'),ctx=context();g.append(uiKpi('N1',n1.done+'/'+n1.total,'vital',n1.done===n1.total?'ok':'danger'));g.append(uiKpi('N2',n2.done+'/'+n2.total,'progression',n2.done?n2.done===n2.total?'ok':'warn':''));if(!isSimple())g.append(uiKpi('N3',n3.done+'/'+n3.total,'bonus',n3.done?'ok':''));g.append(uiKpi('Contexte',ctx.inWork?'Travail':ctx.inSchool?'Cours':'Libre','fatigue '+ctx.fatigue+'/5',ctx.fatigue>=5?'danger':ctx.fatigue>=4?'warn':'ok'));return g}
function section(title,items,day,doneMap,refresh,cls){const c=card(title,items.length+' actions',cls);if(!items.length)c.append(el('div',{class:'empty-state'},'Rien à traiter.'));items.slice(0,isSimple()?5:99).forEach(x=>c.append(actionLine(x,day,doneMap,refresh)));return c}
function actionLine(x,day,doneMap,refresh,main=false){const ok=!!doneMap[x.id];return actionRow({label:x.title,meta:(x.reason||x.desc),priority:(x.score!==undefined?x.p+' · '+x.score:x.p),status:main?'maintenant':'',done:ok,onDone:()=>{setDone(day,x.id,!ok);toast(!ok?'Validé':'Rouvert');refresh()}})}
function opsCard(){const stale=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'&&age(x)>=14).sort((a,b)=>age(b)-age(a)),s=savings();const c=card('Argent / opérations','Vinted et épargne en mode contrôle.','span-6');c.append(compactTable(['zone','état','action'],[['Vinted',stale.length?stale.length+' articles':'RAS',stale.length?'trier / baisser':'rien'],['Épargne',euro(s.done)+'/'+euro(s.target),'reste '+euro(Math.max(0,s.target-s.done))]]));stale.slice(0,3).forEach(x=>c.append(actionRow({label:(x.brand?x.brand+' · ':'')+(x.name||'Article'),meta:age(x)+' jours · prix '+euro(x.asking),priority:'VINTED'})));return c}
function notes(day,refresh){const c=card('Note rapide','Une ligne, pas un journal.');const txt=el('textarea',{class:'input',rows:'2',placeholder:'reprise, blocage, prochaine action'},day.notes||'');c.append(txt);c.append(el('button',{class:'btn green',onclick:()=>{day.notes=txt.value;saveHome(day);toast('Notes sauvegardées');refresh()}},'Sauver'));return c}
function rankActions(plan,doneMap){return plan.filter(x=>!doneMap[x.id]).map(x=>({...x,score:scoreAction(x),reason:reasonAction(x)})).sort((a,b)=>b.score-a.score)}
function scoreAction(x){const ctx=context();let s=x.p==='N1'?100:x.p==='N2'?60:25;if(ctx.inWork&&x.id!=='work')s-=40;if(ctx.inSchool&&x.id!=='school')s-=40;if(ctx.fatigue>=5&&x.p!=='N1')s-=45;if(ctx.fatigue>=4&&x.p==='N3')s-=25;if(x.id==='fuel_water'&&ctx.water<1500&&ctx.hour>=16)s+=80;if(x.id==='fuel_protein'&&ctx.protein<80&&ctx.hour>=18)s+=75;if(x.id==='vinted'&&ctx.vinted30)s+=70;if(x.id==='vinted'&&ctx.vinted14)s+=35;if(x.id==='savings'&&ctx.savingsLeft>0&&ctx.dayOfMonth>=20)s+=55;if(x.id==='review'&&ctx.hour>=21)s+=65;if(x.id==='sport'&&ctx.daysSinceSport>=4)s+=30;if(x.id==='reading'&&ctx.daysSinceReading>=3)s+=20;if(x.id==='chess'&&ctx.daysSinceChess>=3)s+=15;if(x.id==='epfc'&&ctx.hour<=16)s+=15;if(x.id==='nl'&&ctx.hour<=16)s+=10;if(x.id==='coding'||x.id==='iot'||x.id==='repair'||x.id==='ai')s+=ctx.fatigue<=3?10:-10;return s}
function reasonAction(x){const c=context();if(x.id==='fuel_water')return'Eau basse: '+c.water+'/3000 ml';if(x.id==='fuel_protein')return'Protéines basses: '+c.protein+'/150 g';if(x.id==='vinted'&&c.vinted30)return c.vinted30+' articles ≥30j: décision obligatoire';if(x.id==='vinted'&&c.vinted14)return c.vinted14+' articles ≥14j: baisse/tri';if(x.id==='savings'&&c.savingsLeft>0)return'Épargne: reste '+euro(c.savingsLeft);if(x.id==='review'&&c.hour>=21)return'Fin de journée: sécuriser la reprise';if(x.id==='sport'&&c.daysSinceSport>=4)return'Sport absent depuis '+c.daysSinceSport+'j';if(x.id==='reading'&&c.daysSinceReading>=3)return'Lecture absente depuis '+c.daysSinceReading+'j';if(c.inWork)return'Plage travail: reporter sauf urgence';if(c.inSchool)return'Plage cours: reporter sauf urgence';if(c.fatigue>=5)return'Fatigue 5: minimum vital uniquement';return x.desc}
function context(){const r=routineDay(),cfg=r.cfg||{},fuel=Store.get('fuel_'+Store.today(),{water:0,protein:0}),now=new Date(),h=now.getHours(),m=now.getMinutes(),min=h*60+m,work=cfg.work&&between(min,cfg.workStart,cfg.workEnd),school=cfg.school&&between(min,cfg.schoolStart,cfg.schoolEnd),v=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'),sav=savings();return{hour:h,dayOfMonth:now.getDate(),fatigue:+cfg.fatigue||3,inWork:work,inSchool:school,water:+fuel.water||0,protein:+fuel.protein||0,vinted14:v.filter(x=>age(x)>=14).length,vinted30:v.filter(x=>age(x)>=30).length,savingsLeft:Math.max(0,sav.target-sav.done),daysSinceSport:daysSince(Store.sportSessions().filter(x=>x.status==='completed').map(x=>x.date)),daysSinceReading:daysSince(Store.get('reading_activity',[]).map(x=>x.date)),daysSinceChess:daysSince([...Store.get('chess_games',[]),...Store.get('chess_elo_history',[])].map(x=>x.date))}}
function count(plan,doneMap,p){const list=plan.filter(x=>x.p===p);return{total:list.length,done:list.filter(x=>doneMap[x.id]).length}}function fuelText(){const f=Store.get('fuel_'+Store.today(),{water:0,protein:0});return Math.round((+f.water||0)/1000)+'L / '+(+f.protein||0)+'g'}function fuelOk(){const f=Store.get('fuel_'+Store.today(),{water:0,protein:0});return(+f.water||0)>=3000&&(+f.protein||0)>=150}
function homeDay(){return Store.get('home_'+Store.today(),{done:{},notes:''})}function routineDay(){return Store.get('routine_'+Store.today(),{done:{},cfg:{}})}function saveHome(day){Store.set('home_'+Store.today(),day)}function saveRoutine(r){Store.set('routine_'+Store.today(),r)}function mergedDone(day){const r=routineDay();return{...(day.done||{}),...(r.done||{})}}function setDone(day,id,val){day.done=day.done||{};day.done[id]=val;saveHome(day);if(ROUTINE_IDS.has(id)){const r=routineDay();r.done=r.done||{};r.done[id]=val;saveRoutine(r)}}
function buildPlan(){const ep=epfcToday(),fuel=Store.get('fuel_'+Store.today(),{water:0,protein:0});const base=[{id:'epfc',p:'N1',title:'EPFC du jour',desc:ep.code+' · '+ep.title+' → '+epfcResume(ep.code)},{id:'nl',p:'N1',title:'NL / SELOR',desc:nlResume()},{id:'review',p:'N1',title:'Review soir',desc:'Erreur, reprise, prochaine action.'},{id:'coding',p:'N2',title:'Coding',desc:trackResume('coding')},{id:'ai',p:'N2',title:'IA',desc:trackResume('ai')},{id:'iot',p:'N2',title:'IoT',desc:trackResume('iot')},{id:'repair',p:'N2',title:'Réparation',desc:trackResume('repair')},{id:'vinted',p:'N2',title:'Vinted urgent',desc:vintedNeed()},{id:'savings',p:'N2',title:'Épargne',desc:savingsNeed()},{id:'proof',p:'N2',title:'Preuve du jour',desc:'Une preuve: exercice, note, lien, capture.'},{id:'sport',p:'N3',title:'Sport',desc:'Séance: '+sportToday()},{id:'chess',p:'N3',title:'Échecs',desc:'1 partie analysée ou 5 puzzles.'},{id:'reading',p:'N3',title:'Lecture scientifique',desc:'Lire pages du livre actif.'}];if((+fuel.water||0)<3000)base.unshift({id:'fuel_water',p:'N1',title:'Eau',desc:'Atteindre 3L aujourd’hui.'});if((+fuel.protein||0)<150)base.unshift({id:'fuel_protein',p:'N1',title:'Protéines',desc:'Atteindre 150g aujourd’hui.'});return base}
function between(now,start,end){const a=toMin(start||'00:00'),b=toMin(end||'00:00');return a<=b?now>=a&&now<=b:now>=a||now<=b}function toMin(t){const [a,b]=String(t||'00:00').split(':').map(Number);return(a||0)*60+(b||0)}function daysSince(dates){const valid=dates.filter(Boolean).sort();if(!valid.length)return 99;return Math.floor((new Date(Store.today())-new Date(valid[valid.length-1]))/86400000)}
function vintedNeed(){const list=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned');const n14=list.filter(x=>age(x)>=14).length,n30=list.filter(x=>age(x)>=30).length;return n30?'N1: '+n30+' articles ≥30j à décider':n14?'N2: '+n14+' articles ≥14j à baisser':'Rien d’urgent'}function savings(){const d=Store.get('finance_month',{income:2300,savingsGoalPct:20});const target=Math.round((+d.income||0)*(+d.savingsGoalPct||0)/100),month=new Date().toISOString().slice(0,7),done=Store.get('savings_history',[]).filter(x=>x.month===month).reduce((a,x)=>a+(+x.amount||0),0);return{target,done}}function savingsNeed(){const s=savings();return s.done>=s.target?'Objectif atteint':'Reste '+euro(Math.max(0,s.target-s.done))}
function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}function euro(n){return(Number(n)||0).toFixed(2)+' €'}function epfcToday(){return byCode(EPFC_DAILY_ROTATION[dayIndex(new Date())%EPFC_DAILY_ROTATION.length])}function dayIndex(d){return Math.floor((d-new Date(d.getFullYear(),0,1))/86400000)}function byCode(code){return EPFC_YEAR1.find(c=>c.code===code)||EPFC_YEAR1[0]}function epfcResume(code){const st=Store.get('epfc_y1_state',{})[code]||{};const c=byCode(code);const r=c.resources[st.activeIndex||0];if(!r)return 'terminé';const p=(st.progress||{})[r[0]]||{};return r[1]+' · '+(p.current||0)+'/'+(p.total||'?')+' '+r[3]}function trackResume(track){const st=Store.get('track_state',{})[track]||{};const book=(BOOKS[track]||[])[st.bookIndex||0]||'livres terminés';const ex=(EXERCISE_PACKS[track]||[])[st.exerciseIndex||0]||'exercices terminés';return'Livre: '+book+' · Exercice: '+ex}function nlResume(){const d=Store.get('nl_program',{level:'A1',target:'SELOR'});return d.level+' → '+d.target}function sportToday(){const c=Store.sportCycle();const diff=Math.floor((new Date(Store.today())-new Date(c.anchorDate))/86400000);const start=SPORT_CYCLE.indexOf(c.anchorType);return SPORT_CYCLE[((start<0?0:start)+diff%SPORT_CYCLE.length+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
