import { EPFC_YEAR1 } from '../assets/js/epfc-year1.js';
import { EPFC_DAILY_ROTATION } from '../assets/js/practice-catalog.js';
import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, toast, isSimple, actionRow, kpi as uiKpi, compactTable } from '../assets/js/ui.js';

const ROUTINE_IDS=new Set(['epfc','coding','ai','iot','repair','nl','sport','vinted','proof','review','chess','reading','savings','fuel_water','fuel_protein']);
const DUR={fuel_water:2,fuel_protein:5,epfc:25,nl:10,review:5,coding:25,ai:20,iot:20,repair:20,vinted:15,savings:5,proof:5,sport:45,chess:15,reading:20};
export function renderHome(root,refresh){const day=homeDay(),plan=buildPlan(),doneMap=mergedDone(day),ranked=rankActions(plan,doneMap),done=plan.filter(x=>doneMap[x.id]).length,score=Math.round(done/Math.max(1,plan.length)*100),next=ranked[0];root.append(missionControl(next,plan,doneMap,score,day,refresh));root.append(signalRail(plan,doneMap));const grid=el('div',{class:'grid'});grid.append(commandQueue(ranked,day,doneMap,refresh));grid.append(focusCard());grid.append(proofCard(refresh));if(!isSimple()){grid.append(section('N1 · vital',rankActions(plan.filter(x=>x.p==='N1'),doneMap),day,doneMap,refresh,'span-6'));grid.append(section('N2 · progression',rankActions(plan.filter(x=>x.p==='N2'),doneMap),day,doneMap,refresh,'span-6'));grid.append(section('N3 · optionnel',rankActions(plan.filter(x=>x.p==='N3'),doneMap),day,doneMap,refresh,'span-6'));grid.append(opsCard())}root.append(grid);if(!isSimple())root.append(notes(day,refresh))}
function missionControl(next,plan,doneMap,score,day,refresh){const done=plan.filter(x=>doneMap[x.id]).length;const c=card('MISSION CONTROL',next?'Ordre immédiat: '+next.title:'Journée sécurisée.','span-12 module-hero mission-control');c.className+=' '+(next?.p==='N1'?'danger':next?'warn':'ok');c.append(el('div',{class:'grid'},[uiKpi('Score jour',score+'%',done+'/'+plan.length+' blocs',score>=80?'ok':score>=45?'warn':'danger'),uiKpi('Ordre',next?next.p:'OK',next?next.title:'RAS',next?.p==='N1'?'danger':next?'warn':'ok'),uiKpi('Durée',next?(DUR[next.id]||10)+' min':'0 min',next?'fallback disponible':'terminé')]));if(next){c.append(el('div',{class:'exercise '+(next.p==='N1'?'danger':'warn')},[el('div',{class:'exercise-title'},'À exécuter maintenant'),el('div',{},next.title),el('div',{class:'small muted'},'Raison: '+(next.reason||next.desc)),el('div',{class:'small muted'},'Fallback: '+fallback(next)),el('div',{class:'row'},[el('button',{class:'btn green',onclick:()=>{setDone(day,next.id,true);toast('Ordre validé');refresh()}},'Terminé'),el('button',{class:'btn',onclick:()=>{Store.push('study_activity',{domain:'mission',kind:'fallback',title:next.title,date:Store.today(),status:'fallback'});setDone(day,next.id,true);toast('Fallback validé');refresh()}},'Fallback validé'),el('button',{class:'btn danger',onclick:()=>{day.notes=(day.notes||'')+'\nBlocage '+new Date().toLocaleTimeString('fr-BE')+': '+next.title;saveHome(day);toast('Blocage noté');refresh()}},'Bloqué')])]))}return c}
function fallback(x){if(x.id==='epfc')return'5 questions ou 10 minutes de reprise.';if(x.id==='sport')return'15 minutes mobilité/marche.';if(x.id==='vinted')return'Traiter 1 article mort.';if(x.id==='coding'||x.id==='ai'||x.id==='iot'||x.id==='repair')return'Lire 1 page + produire 1 note.';if(x.id==='nl')return'10 phrases + 5 cartes.';if(x.id==='fuel_water')return'500 ml maintenant.';if(x.id==='fuel_protein')return'1 repas/protéine simple.';return'Version 5 minutes, preuve minimale.'}
function signalRail(plan,doneMap){const ctx=context(),n1=count(plan,doneMap,'N1'),n2=count(plan,doneMap,'N2'),n3=count(plan,doneMap,'N3'),g=el('div',{class:'grid'});g.append(uiKpi('N1',n1.done+'/'+n1.total,'vital',n1.done===n1.total?'ok':'danger'));g.append(uiKpi('N2',n2.done+'/'+n2.total,'progression',n2.done?n2.done===n2.total?'ok':'warn':''));g.append(uiKpi('Contexte',ctx.inWork?'Travail':ctx.inSchool?'Cours':'Libre','fatigue '+ctx.fatigue+'/5',ctx.fatigue>=5?'danger':ctx.fatigue>=4?'warn':'ok'));if(!isSimple())g.append(uiKpi('N3',n3.done+'/'+n3.total,'optionnel',n3.done?'ok':''));return g}
function commandQueue(ranked,day,doneMap,refresh){const c=card('File d’action','Triée par urgence réelle. Le haut gagne.','span-6');const list=ranked.slice(0,isSimple()?5:8);if(!list.length)c.append(el('div',{class:'empty-state'},'Aucune action restante.'));list.forEach(x=>c.append(actionLine(x,day,doneMap,refresh)));return c}
function actionLine(x,day,doneMap,refresh){const ok=!!doneMap[x.id];return actionRow({label:x.title,meta:(x.reason||x.desc)+' · '+(DUR[x.id]||10)+' min',priority:(x.score!==undefined?x.p+' · '+x.score:x.p),done:ok,onDone:()=>{setDone(day,x.id,!ok);toast(!ok?'Validé':'Rouvert');refresh()}})}
function focusCard(){const focus=Store.get('focus_quarter',{primary:['EPFC / informatique','Sport santé','Argent / Vinted'],parking:['Échecs','Lecture avancée','IA avancée','IoT avancé']});const c=card('Focus trimestre','Maximum 3 axes actifs. Le reste va au parking.','span-6');c.append(compactTable(['actif','mission'],focus.primary.map((x,i)=>['#'+(i+1),x])));if(!isSimple())c.append(el('div',{class:'small muted'},'Parking: '+(focus.parking||[]).join(' · ')));return c}
function proofCard(refresh){const proofs=Store.get('proofs',[]).filter(x=>x.date===Store.today()||x.dueDate===Store.today()),done=proofs.filter(x=>x.status==='validated').length;const c=card('Preuves du jour',done+'/3 minimum: étude, santé, argent.','span-6 '+(done>=3?'ok':'warn'));['étude','santé/sport','argent/admin'].forEach(zone=>c.append(el('button',{class:'btn '+(proofs.some(p=>p.course===zone&&p.status==='validated')?'green':''),onclick:()=>{Store.push('proofs',{course:zone,title:'Preuve '+zone,date:Store.today(),dueDate:Store.today(),status:'validated'});toast('Preuve '+zone+' validée');refresh()}},'Valider preuve '+zone)));return c}
function section(title,items,day,doneMap,refresh,cls){const c=card(title,items.length+' actions',cls);if(!items.length)c.append(el('div',{class:'empty-state'},'Rien à traiter.'));items.forEach(x=>c.append(actionLine(x,day,doneMap,refresh)));return c}
function opsCard(){const stale=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'&&age(x)>=14).sort((a,b)=>age(b)-age(a)),s=savings();const c=card('Argent / opérations','Vinted et épargne en contrôle.','span-6');c.append(compactTable(['zone','état','action'],[['Vinted',stale.length?stale.length+' articles':'RAS',stale.length?'trier / baisser':'rien'],['Épargne',euro(s.done)+'/'+euro(s.target),'reste '+euro(Math.max(0,s.target-s.done))]]));stale.slice(0,3).forEach(x=>c.append(actionRow({label:(x.brand?x.brand+' · ':'')+(x.name||'Article'),meta:age(x)+' jours · prix '+euro(x.asking),priority:'VINTED'})));return c}
function notes(day,refresh){const c=card('Note rapide','Une ligne: blocage, reprise, prochaine action.');const txt=el('textarea',{class:'input',rows:'3',placeholder:'reprise, blocage, prochaine action'},day.notes||'');c.append(txt);c.append(el('button',{class:'btn green',onclick:()=>{day.notes=txt.value;saveHome(day);toast('Notes sauvegardées');refresh()}},'Sauver'));return c}
function rankActions(plan,doneMap){return plan.filter(x=>!doneMap[x.id]).map(x=>({...x,score:scoreAction(x),reason:reasonAction(x)})).sort((a,b)=>b.score-a.score)}
function scoreAction(x){const ctx=context();let s=x.p==='N1'?100:x.p==='N2'?60:25;if(ctx.inWork&&x.id!=='work')s-=40;if(ctx.inSchool&&x.id!=='school')s-=40;if(ctx.fatigue>=5&&x.p!=='N1')s-=45;if(ctx.fatigue>=4&&x.p==='N3')s-=25;if(x.id==='fuel_water'&&ctx.water<1500&&ctx.hour>=16)s+=80;if(x.id==='fuel_protein'&&ctx.protein<80&&ctx.hour>=18)s+=75;if(x.id==='vinted'&&ctx.vinted30)s+=70;if(x.id==='vinted'&&ctx.vinted14)s+=35;if(x.id==='savings'&&ctx.savingsLeft>0&&ctx.dayOfMonth>=20)s+=55;if(x.id==='review'&&ctx.hour>=21)s+=65;if(x.id==='sport'&&ctx.daysSinceSport>=4)s+=30;if(x.id==='reading'&&ctx.daysSinceReading>=3)s+=20;if(x.id==='chess'&&ctx.daysSinceChess>=3)s+=15;if(x.id==='epfc'&&ctx.hour<=16)s+=15;if(x.id==='nl'&&ctx.hour<=16)s+=10;if(x.id==='coding'||x.id==='iot'||x.id==='repair'||x.id==='ai')s+=ctx.fatigue<=3?10:-10;return s}
function reasonAction(x){const c=context();if(x.id==='fuel_water')return'Eau basse: '+c.water+'/3000 ml';if(x.id==='fuel_protein')return'Protéines basses: '+c.protein+'/150 g';if(x.id==='vinted'&&c.vinted30)return c.vinted30+' articles ≥30j: décision obligatoire';if(x.id==='vinted'&&c.vinted14)return c.vinted14+' articles ≥14j: baisse/tri';if(x.id==='savings'&&c.savingsLeft>0)return'Épargne: reste '+euro(c.savingsLeft);if(x.id==='review'&&c.hour>=21)return'Fin de journée: sécuriser reprise';if(x.id==='sport'&&c.daysSinceSport>=4)return'Sport absent depuis '+c.daysSinceSport+'j';if(x.id==='reading'&&c.daysSinceReading>=3)return'Lecture absente depuis '+c.daysSinceReading+'j';if(c.inWork)return'Plage travail: reporter sauf urgence';if(c.inSchool)return'Plage cours: reporter sauf urgence';if(c.fatigue>=5)return'Fatigue 5: minimum vital uniquement';return x.desc}
function context(){const r=routineDay(),cfg=r.cfg||{},fuel=Store.get('fuel_'+Store.today(),{water:0,protein:0}),now=new Date(),h=now.getHours(),m=now.getMinutes(),min=h*60+m,work=cfg.work&&between(min,cfg.workStart,cfg.workEnd),school=cfg.school&&between(min,cfg.schoolStart,cfg.schoolEnd),v=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'),sav=savings();return{hour:h,dayOfMonth:now.getDate(),fatigue:+cfg.fatigue||3,inWork:work,inSchool:school,water:+fuel.water||0,protein:+fuel.protein||0,vinted14:v.filter(x=>age(x)>=14).length,vinted30:v.filter(x=>age(x)>=30).length,savingsLeft:Math.max(0,sav.target-sav.done),daysSinceSport:daysSince(Store.sportSessions().filter(x=>x.status==='completed'||x.status==='deload').map(x=>x.date)),daysSinceReading:daysSince(Store.get('reading_activity',[]).map(x=>x.date)),daysSinceChess:daysSince([...Store.get('chess_games',[]),...Store.get('chess_elo_history',[])].map(x=>x.date))}}
function buildPlan(){const ep=epfcToday(),fuel=Store.get('fuel_'+Store.today(),{water:0,protein:0});const base=[{id:'epfc',p:'N1',title:'EPFC du jour',desc:ep.code+' · '+ep.title+' → '+epfcResume(ep.code)},{id:'nl',p:'N1',title:'NL / SELOR',desc:nlResume()},{id:'review',p:'N1',title:'Review soir',desc:'Erreur, reprise, prochaine action.'},{id:'coding',p:'N2',title:'Coding',desc:trackResume('coding')},{id:'ai',p:'N2',title:'IA',desc:trackResume('ai')},{id:'iot',p:'N2',title:'IoT',desc:trackResume('iot')},{id:'repair',p:'N2',title:'Réparation',desc:trackResume('repair')},{id:'vinted',p:'N2',title:'Vinted urgent',desc:vintedNeed()},{id:'savings',p:'N2',title:'Épargne',desc:savingsNeed()},{id:'proof',p:'N2',title:'Preuve du jour',desc:'Une preuve: exercice, note, lien, capture.'},{id:'sport',p:'N3',title:'Sport',desc:'Séance ou mobilité.'},{id:'chess',p:'N3',title:'Échecs',desc:'1 partie analysée ou 5 puzzles.'},{id:'reading',p:'N3',title:'Lecture scientifique',desc:'Lire pages du livre actif.'}];if((+fuel.water||0)<3000)base.unshift({id:'fuel_water',p:'N1',title:'Eau',desc:'Atteindre 3L aujourd’hui.'});if((+fuel.protein||0)<150)base.unshift({id:'fuel_protein',p:'N1',title:'Protéines',desc:'Atteindre 150g aujourd’hui.'});return base}
function count(plan,doneMap,p){const list=plan.filter(x=>x.p===p);return{total:list.length,done:list.filter(x=>doneMap[x.id]).length}}function homeDay(){return Store.get('home_'+Store.today(),{done:{},notes:''})}function routineDay(){return Store.get('routine_'+Store.today(),{done:{},cfg:{}})}function saveHome(day){Store.set('home_'+Store.today(),day)}function saveRoutine(r){Store.set('routine_'+Store.today(),r)}function mergedDone(day){const r=routineDay();return{...(day.done||{}),...(r.done||{})}}function setDone(day,id,val){day.done=day.done||{};day.done[id]=val;saveHome(day);if(ROUTINE_IDS.has(id)){const r=routineDay();r.done=r.done||{};r.done[id]=val;saveRoutine(r)}}
function between(now,start,end){const a=toMin(start||'00:00'),b=toMin(end||'00:00');return a<=b?now>=a&&now<=b:now>=a||now<=b}function toMin(t){const [a,b]=String(t||'00:00').split(':').map(Number);return(a||0)*60+(b||0)}function daysSince(dates){const valid=dates.filter(Boolean).sort();if(!valid.length)return 99;return Math.floor((new Date(Store.today())-new Date(valid[valid.length-1]))/86400000)}function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}function euro(n){return(Number(n)||0).toFixed(2)+' €'}
function savings(){const d=Store.get('finance_month',{income:2300,savingsGoalPct:20});const target=Math.round((+d.income||0)*(+d.savingsGoalPct||0)/100),month=new Date().toISOString().slice(0,7),done=Store.get('savings_history',[]).filter(x=>x.month===month).reduce((a,x)=>a+(+x.amount||0),0);return{target,done}}function savingsNeed(){const s=savings();return s.done>=s.target?'Objectif atteint':'Reste '+euro(Math.max(0,s.target-s.done))}
function vintedNeed(){const list=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned');const n14=list.filter(x=>age(x)>=14).length,n30=list.filter(x=>age(x)>=30).length;return n30?'N1: '+n30+' articles ≥30j à décider':n14?'N2: '+n14+' articles ≥14j à baisser':'Rien d’urgent'}
function epfcToday(){return byCode(EPFC_DAILY_ROTATION[dayIndex(new Date())%EPFC_DAILY_ROTATION.length])}function dayIndex(d){return Math.floor((d-new Date(d.getFullYear(),0,1))/86400000)}function byCode(code){return EPFC_YEAR1.find(c=>c.code===code)||EPFC_YEAR1[0]}function epfcResume(code){const st=Store.get('epfc_y1_state',{})[code]||{};const c=byCode(code);const r=c.resources[st.activeIndex||0];if(!r)return 'terminé';const p=(st.progress||{})[r[0]]||{};return r[1]+' · '+(p.current||0)+'/'+(p.total||'?')+' '+r[3]}function trackResume(track){const st=Store.get('track_state',{})[track]||{};const book=(BOOKS[track]||[])[st.bookIndex||0]||'livres terminés';const ex=(EXERCISE_PACKS[track]||[])[st.exerciseIndex||0]||'exercices terminés';return'Livre: '+book+' · Exercice: '+ex}function nlResume(){const d=Store.get('nl_program',{level:'A1',target:'SELOR'});return d.level+' → '+d.target+' · Anki/écoute/phrases/corrections'}
