import { SPORT_CYCLE, SPORT_LIBRARY, SPORT_PROGRAM, BODYWEIGHT_LADDERS, MUSCLE_LABELS } from '../assets/js/hybrid-ppl-data.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast, progress } from '../assets/js/ui.js';

const VERSION='hybrid-ppl-v1';
let panel='today',cat='all';
const byId=id=>SPORT_LIBRARY.find(x=>x.id===id);
const sessions=()=>Store.sportSessions().filter(x=>x.programVersion===VERSION);
const today=()=>Store.today();
const draft=()=>Store.sportDraft(today());
const saveDraft=x=>Store.setSportDraft(today(),x);
const isRest=t=>String(t).startsWith('Rest');

function cycleType(){const c=Store.sportCycle(),days=Math.floor((new Date(today())-new Date(c.anchorDate))/86400000),start=Math.max(0,SPORT_CYCLE.indexOf(c.anchorType));return SPORT_CYCLE[(start+(days%SPORT_CYCLE.length)+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
function sessionIds(type=cycleType()){return SPORT_PROGRAM[type]||[]}
function profile(){return Store.bodyweight()||{}}
function profileKey(skill){return({pullup:'pullups',chinup:'pullups',pushup:'pushups',dip:'dips',pike:'pike'})[skill]||skill}
function level(ex){return Math.max(0,Math.min(5,+profile()?.[profileKey(ex.skill)]?.level||0))}
function resolve(ex){if(!ex?.skill)return{...ex,activeName:ex.name};const step=BODYWEIGHT_LADDERS[ex.skill]?.[level(ex)]||ex.prescription;return{...ex,activeName:ex.name+' · '+step.label,prescription:step,skillLevel:level(ex),next:step.next}}
function setRows(p){return Array.from({length:+p.sets||1},()=>({reps:'',kg:'',sec:'',rir:'',pain:''}))}
function loadSets(id,p){return draft().exercises?.[id]?.sets||setRows(p)}
function setField(id,index,key,value,p){const d=draft();d.exercises=d.exercises||{};const row=d.exercises[id]||{sets:setRows(p)};row.sets=row.sets||setRows(p);row.sets[index]={...row.sets[index],[key]:value};d.exercises[id]=row;saveDraft(d)}
function range(text){const n=String(text||'').match(/(\d+)\D+(\d+)/);return n?[+n[1],+n[2]]:[0,0]}
function lastExercise(id){return sessions().filter(s=>s.exercises?.[id]).slice(-1)[0]?.exercises?.[id]||null}
function advice(ex,p){const last=lastExercise(ex.id),sets=last?.sets||[];if(!sets.length)return'Base : garde 1 à 2 RIR et note les séries réelles.';const pain=Math.max(0,...sets.map(s=>+s.pain||0));if(pain>=4)return'Douleur élevée : allège, change la variante ou arrête le mouvement.';const [min,max]=range(p.reps);if(p.kind==='time'){const top=Math.max(...sets.map(s=>+s.sec||0));return top>=max?'Augmente légèrement la durée ou la charge.':'Atteins '+max+' secondes proprement.'}const reps=sets.map(s=>+s.reps||0).filter(Boolean),loads=sets.map(s=>+s.kg||0).filter(Boolean);if(reps.length<+p.sets)return'Renseigne toutes les séries pour une progression fiable.';if(reps.every(x=>x>=max)&&loads.length)return ex.skill?'Passe au niveau suivant lorsque la technique est propre.':'Ajoute 1 à 2,5 kg à la séance suivante.';if(reps.every(x=>x>=max))return ex.skill?'Passe au niveau suivant lorsque la technique est propre.':'Passe à une variante plus dure.';if(reps.every(x=>x>=min))return'Ajoute 1 rep à la série la plus basse.';return'Atteins le minimum de '+min+' reps avec 1 à 2 RIR.'}
function plannedSets(type){return sessionIds(type).reduce((n,id)=>n+(resolve(byId(id))?.prescription?.sets||0),0)}

export function renderSport(root,refresh){root.append(cycleControl(refresh));root.append(subTabs([{id:'today',label:'Séance'},{id:'coverage',label:'Couverture'},{id:'bodyweight',label:'Poids du corps'},{id:'library',label:'Bibliothèque'},{id:'history',label:'Historique'},{id:'tests',label:'Tests'}],panel,id=>{panel=id;refresh()}));const box=el('div');root.append(box);({today:todayPanel,coverage:coveragePanel,bodyweight:bodyweightPanel,library:libraryPanel,history:historyPanel,tests:testsPanel}[panel]||todayPanel)(box,refresh)}

function cycleControl(refresh){const current=cycleType(),pick=el('select',{class:'input',style:'max-width:200px'});SPORT_CYCLE.forEach(x=>pick.append(el('option',{value:x},x)));pick.value=current;return el('div',{class:'row'},[el('span',{class:'pill'},'CYCLE · '+current),pick,button('Démarrer ici',()=>{Store.setSportCycle({anchorDate:today(),anchorType:pick.value});toast('Cycle redémarré : '+pick.value);refresh()},'green')])}
function todayPanel(root,refresh){const type=cycleType(),ids=sessionIds(type),all=ids.map(byId).filter(Boolean),c=card('Hybrid PPL · '+type,isRest(type)?'Récupération active. Tu valides la séance sans inventer de records.':'Séries réelles uniquement. Les performances non saisies ne comptent pas.','span-12');c.append(el('div',{class:'grid'},[metric('Exercices',String(all.length),'programme'),metric('Séries',String(plannedSets(type)),'prévues'),metric('Standard','1–2 RIR','sauf dernière série') ]));const state=draft(),pain=input('douleur globale 0-10',state.globalPain||0),energy=input('énergie 1-5',state.energy||3),notes=el('textarea',{class:'input',rows:'3',placeholder:'notes séance · douleur · variante'},state.notes||'');notes.addEventListener('change',()=>{const d=draft();d.notes=notes.value;saveDraft(d)});c.append(el('div',{class:'row'},[pain,energy]),notes);all.forEach((ex,i)=>c.append(exerciseCard(resolve(ex),i)));c.append(el('div',{class:'row'},[button('Séance validée',()=>saveSession('completed',type,pain.value,energy.value,notes.value,refresh),'green'),button('Séance allégée',()=>saveSession('deload',type,pain.value,energy.value,notes.value,refresh),'warn'),button('Sautée',()=>saveSession('skipped',type,pain.value,energy.value,notes.value,refresh)]));root.append(c)}
function metric(title,value,sub){const c=card(title,sub,'span-4 compact-card');c.append(el('div',{class:'metric'},value));return c}
function exerciseCard(ex,index){const p=ex.prescription,sets=loadSets(ex.id,p),d=el('section',{class:'exercise '+(ex.optional?'warn':'')});d.append(el('div',{class:'row'},[el('span',{class:'pill'},String(index+1).padStart(2,'0')),el('span',{class:'pill'},ex.category),ex.optional?el('span',{class:'pill'},'OPTION'):null,el('b',{},ex.activeName)]));d.append(el('div',{class:'small'},p.sets+' séries · '+p.reps+' · repos '+p.rest+' sec · RIR '+p.rir+' · '+ex.equipment));if(ex.next)d.append(el('div',{class:'small muted'},'Niveau '+ex.skillLevel+'/5 · '+ex.next));if(ex.note)d.append(el('div',{class:'small muted'},ex.note));d.append(el('div',{class:'exercise-title'},advice(ex,p)));sets.forEach((s,i)=>d.append(setLine(ex.id,i,s,p)));d.append(el('div',{class:'small muted'},'Cibles : '+Object.keys(ex.muscles).map(k=>MUSCLE_LABELS[k]).join(' · ')));return d}
function setLine(id,i,s,p){const row=el('div',{class:'set-row'});row.append(el('div',{class:'set-index'},'S'+(i+1)+'/'+p.sets));const fields=p.kind==='time'?[['sec','Sec'],['kg','Kg'],['rir','RIR'],['pain','Douleur']]:[['reps','Reps'],['kg','Kg'],['rir','RIR'],['pain','Douleur']];fields.forEach(([key,label])=>row.append(field(label,s[key],v=>setField(id,i,key,v,p))));return row}
function field(label,value,save){const w=el('label',{class:'field-mini'}),n=el('input',{type:'number',placeholder:label,value:String(value??'')});n.addEventListener('change',()=>save(n.value));w.append(el('span',{},label),n);return w}
function input(label,value){return el('input',{class:'input',type:'number',placeholder:label,value:String(value??''),style:'max-width:170px'})}
function button(label,onClick,cls=''){return el('button',{class:'btn '+cls,onclick:onClick},label)}
function saveSession(status,type,pain,energy,notes,refresh){const d=draft(),exercises={};sessionIds(type).forEach(id=>{const ex=resolve(byId(id)),sets=d.exercises?.[id]?.sets||[];exercises[id]={name:ex.activeName,sets,prescription:ex.prescription,muscles:ex.muscles}});const setPain=Math.max(0,...Object.values(exercises).flatMap(x=>x.sets).map(x=>+x.pain||0)),maxPain=Math.max(+pain||0,setPain),final=maxPain>=7?'pain_stop':status==='completed'&&maxPain>=4?'deload':status;Store.addSportSession({date:today(),programVersion:VERSION,sessionType:type,status:final,exercises,notes:notes||'',globalPainLevel:maxPain,energyLevel:+energy||3});Store.setSportDraft(today(),{});toast(final==='pain_stop'?'Arrêt douleur enregistré':final==='deload'?'Séance allégée enregistrée':'Séance enregistrée');refresh()}

function coveragePanel(root){const p=profile(),volume={};SPORT_CYCLE.filter(x=>!isRest(x)).forEach(type=>sessionIds(type).forEach(id=>{const ex=resolve(byId(id)),sets=ex.prescription.sets;Object.entries(ex.muscles).forEach(([m,f])=>volume[m]=(volume[m]||0)+sets*f)}));const c=card('Couverture musculaire · cycle complet','Séries directes équivalentes prévues. Les chiffres servent à repérer les oublis, pas à gonfler le volume.');const grid=el('div',{class:'grid'});Object.entries(MUSCLE_LABELS).forEach(([id,label])=>{const n=Math.round((volume[id]||0)*10)/10,box=card(label,n?'≈'+n+' séries':'0 série','span-4 compact-card '+(n?'':'warn'));box.append(progress(Math.min(n,16),16));grid.append(box)});c.append(grid);c.append(el('div',{class:'exercise'},'Contrôle inclus : pecs, trois faisceaux épaules, triceps, dorsaux, milieu du dos, biceps, avant-bras, grip, quadriceps, ischios, fessiers, adducteurs, mollets debout, soléaire, tibial, abdos, obliques et cou optionnel.'));root.append(c)}
function bodyweightPanel(root,refresh){const c=card('Progression poids du corps','Le niveau choisi modifie automatiquement les tractions, chin-ups, pompes, dips et pike push-ups de la séance.');Object.entries(BODYWEIGHT_LADDERS).forEach(([skill,steps])=>{const key=profileKey(skill),p=profile(),current=Math.max(0,Math.min(5,+p[key]?.level||0)),select=el('select',{class:'input',style:'max-width:230px'});steps.forEach((s,i)=>select.append(el('option',{value:i},i+' · '+s.label)));select.value=String(current);const currentStep=steps[current];c.append(el('div',{class:'exercise'},[el('div',{class:'row'},[el('b',{},skill.toUpperCase()),select,button('Sauver',()=>{const x=profile();x[key]={...(x[key]||{}),level:+select.value,lastTestDate:today()};Store.setBodyweight(x);toast('Niveau '+skill+' sauvegardé');refresh()},'green')]),el('div',{class:'small'},currentStep.sets+'×'+currentStep.reps+' · repos '+currentStep.rest+' sec · '+currentStep.next)]));});root.append(c)}
function libraryPanel(root,refresh){const cats=['all','push','pull','legs','core','conditioning','mobility'];root.append(subTabs(cats.map(x=>({id:x,label:x})),cat,id=>{cat=id;refresh()}));const c=card('Bibliothèque hybride','Exercices utilisés par le PPL et alternatives simples.');SPORT_LIBRARY.filter(x=>cat==='all'||x.category===cat).forEach(ex=>{const p=resolve(ex).prescription;c.append(el('div',{class:'exercise'},[el('div',{class:'row'},[el('span',{class:'pill'},ex.category),el('b',{},resolve(ex).activeName)]),el('div',{class:'small'},p.sets+'×'+p.reps+' · repos '+p.rest+' sec · RIR '+p.rir),el('div',{class:'small muted'},'Alternatives : '+(ex.alternatives.join(', ')||'—'))]));});root.append(c)}
function historyPanel(root){const c=card('Historique Hybrid PPL','Anciennes séances ne polluent pas les nouveaux records.');sessions().slice(-50).reverse().forEach(s=>{const count=Object.values(s.exercises||{}).flatMap(x=>x.sets||[]).filter(x=>x.reps||x.sec||x.kg).length;c.append(el('div',{class:'exercise '+(s.status==='pain_stop'?'danger':s.status==='deload'?'warn':'')},s.date+' · '+s.sessionType+' · '+s.status+' · séries renseignées '+count+' · douleur '+(s.globalPainLevel??0)+' · énergie '+(s.energyLevel??'-')))});if(!sessions().length)c.append(el('div',{class:'empty-state'},'Aucune séance Hybrid PPL enregistrée.'));root.append(c)}
function testsPanel(root){const c=card('Tests mensuels','Tests bruts pour fixer tes niveaux poids du corps.');const fields=['tractions strictes max','chin-ups max','pompes strictes max','dips max','dead hang sec','poids kg'],nodes={};fields.forEach(x=>nodes[x]=input(x,''));c.append(el('div',{class:'row'},Object.values(nodes)));c.append(button('Sauver test',()=>{const t={date:today(),programVersion:VERSION};Object.entries(nodes).forEach(([k,n])=>t[k]=n.value?+n.value:null);Store.addSportMonthlyTest(t);toast('Test mensuel sauvegardé')},'green'));Store.sportMonthlyTests().filter(x=>x.programVersion===VERSION).slice(-6).reverse().forEach(t=>c.append(el('div',{class:'exercise'},t.date+' · tractions '+(t['tractions strictes max']??'-')+' · pompes '+(t['pompes strictes max']??'-')+' · poids '+(t['poids kg']??'-'))));root.append(c)}
