import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='chess';
const TRACKS={
 apprendre:{label:'Apprendre / mémoire',books:[['Apprendre !','Stanislas Dehaene','neurosciences cognitives de l apprentissage'],['Les Neurones de la lecture','Stanislas Dehaene','lecture, cerveau, apprentissage'],['La Bosse des maths','Stanislas Dehaene','cognition numerique et maths']]},
 psychologie:{label:'Psychologie / décision',books:[['Systeme 1 / Systeme 2','Daniel Kahneman','biais cognitifs et decision'],['L Erreur de Descartes','Antonio Damasio','emotion, raison, decision'],['Votre cerveau vous joue des tours','Albert Moukheiber','biais cognitifs'],['Ou est le sens ?','Sebastien Bohler','motivation et sens']]},
 influence:{label:'Charisme / influence',books:[['Influence et manipulation','Robert Cialdini','psychologie sociale de la persuasion'],['Pre-suasion','Robert Cialdini','influence avant decision']]},
 argent:{label:'Argent / risque',books:[['Nudge','Richard Thaler, Cass Sunstein','economie comportementale'],['Misbehaving','Richard Thaler','comportements economiques reels'],['La Psychologie de l argent','Morgan Housel','comportement financier'],['Le Cygne noir','Nassim Nicholas Taleb','risque et incertitude'],['Le Hasard sauvage','Nassim Nicholas Taleb','hasard, finance, decision']]},
 science:{label:'Science / statistiques',books:[['L Art de la statistique','David Spiegelhalter','raisonnement statistique'],['Factfulness','Hans Rosling','donnees et biais'],['Le Code de la conscience','Stanislas Dehaene','conscience et cerveau']]},
 corps:{label:'Corps / cerveau / performance',books:[['Spinoza avait raison','Antonio Damasio','emotion, corps, cerveau'],['Le Charme discret de l intestin','Giulia Enders','physiologie digestive'],['Pourquoi nous dormons','Matthew Walker','sommeil et performance'],['Endurance','Alex Hutchinson','performance physique'],['Le Bug humain','Sebastien Bohler','dopamine et comportement'],['Pourquoi nous faisons ce que nous faisons','Robert Sapolsky','biologie du comportement']]}
};
export function renderLeisure(root,rr){root.append(subTabs([{id:'chess',label:'Échecs'},{id:'reading',label:'Lecture'}],panel,id=>{panel=id;rr()}));const box=el('div');root.append(box);if(panel==='reading')return reading(box,rr);chess(box,rr)}
function chess(root,rr){const h=Store.get('chess_elo_history',[]),games=Store.get('chess_games',[]),goal=Store.get('chess_goal',{target:1200});const last=h[h.length-1];root.append(chessSummary(h,games,goal));const c=card('Échecs · ELO tracker',last?'ELO actuel '+last.elo+' · rang '+rank(last.elo):'Aucun ELO loggé');c.append(graph(h));const elo=input('nouvel ELO','number',last?.elo||''),platform=select(['Chess.com','Lichess','OTB','Autre'],last?.platform||'Chess.com'),target=input('objectif ELO','number',goal.target||1200),note=input('note');c.append(el('div',{class:'row'},[elo,platform,target,note,el('button',{class:'btn green',onclick:()=>{Store.push('chess_elo_history',{date:Store.today(),elo:+elo.value||0,platform:platform.value,note:note.value});Store.set('chess_goal',{target:+target.value||0});toast('ELO sauvegardé');rr()}},'Ajouter ELO') ]));root.append(c);root.append(gameLog(rr));root.append(rankingCard(h));root.append(historyCard(h,games))}
function chessSummary(h,games,goal){const last=h[h.length-1]?.elo||0,prev=h[h.length-2]?.elo||last,delta=last-prev,target=+goal.target||0,last7=h.slice(-7).map(x=>+x.elo||0),avg=last7.length?Math.round(last7.reduce((a,b)=>a+b,0)/last7.length):0,w=games.filter(g=>g.result==='win').length,l=games.filter(g=>g.result==='loss').length,d=games.filter(g=>g.result==='draw').length,puz=games.reduce((a,g)=>a+(+g.puzzles||0),0);const c=card('Échecs · command center','ELO '+(last||'-')+' · objectif '+(target||'-')+' · écart '+(target&&last?target-last:'-')+' · tendance '+(delta>=0?'+'+delta:delta)+' · moyenne 7 logs '+avg);c.className+=' '+(delta>=0?'ok':'warn');c.append(el('div',{class:'exercise'},'Parties: '+games.length+' · V '+w+' / D '+l+' / N '+d+' · puzzles '+puz));return c}
function gameLog(rr){const c=card('Journal partie / puzzles','Log utile: résultat, accuracy, ouverture, erreur principale.');const result=select(['win','loss','draw','puzzles'], 'puzzles'),platform=select(['Chess.com','Lichess','OTB','Autre'],'Chess.com'),puzzles=input('puzzles faits','number',''),accuracy=input('accuracy %','number',''),opening=input('ouverture'),mistake=input('erreur principale'),note=input('note');c.append(el('div',{class:'row'},[result,platform,puzzles,accuracy,opening,mistake,note]));c.append(el('button',{class:'btn green',onclick:()=>{Store.push('chess_games',{date:Store.today(),result:result.value,platform:platform.value,puzzles:+puzzles.value||0,accuracy:+accuracy.value||0,opening:opening.value,mistake:mistake.value,note:note.value});toast('Partie/puzzles loggés');rr()}},'Ajouter log'));return c}
function graph(h){if(!h.length)return el('div',{class:'exercise'},'Graph vide. Ajoute ton premier ELO.');const vals=h.map(x=>+x.elo||0),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),w=320,hg=120;const pts=vals.map((v,i)=>{const x=vals.length===1?w/2:i*(w/(vals.length-1));const y=hg-10-((v-min)/range)*(hg-20);return x+','+y}).join(' ');return el('div',{class:'exercise'},el('svg',{viewBox:'0 0 '+w+' '+hg,style:'width:100%;height:140px'},[el('polyline',{points:pts,fill:'none',stroke:'currentColor','stroke-width':'4'}),el('text',{x:'4',y:'14',fill:'currentColor'},String(max)),el('text',{x:'4',y:String(hg-4),fill:'currentColor'},String(min))]))}
function rank(e){e=+e||0;if(e<800)return'Débutant';if(e<1000)return'Novice';if(e<1200)return'Intermédiaire bas';if(e<1400)return'Intermédiaire';if(e<1600)return'Club';if(e<1800)return'Bon club';if(e<2000)return'Avancé';if(e<2200)return'Expert';return'Maître / très fort'}
function rankingCard(h){const last=h[h.length-1]?.elo||0;const c=card('Ranking ELO','Classement indicatif par tranche.');[['0-799','Débutant'],['800-999','Novice'],['1000-1199','Intermédiaire bas'],['1200-1399','Intermédiaire'],['1400-1599','Club'],['1600-1799','Bon club'],['1800-1999','Avancé'],['2000-2199','Expert'],['2200+','Maître / très fort']].forEach(r=>c.append(el('div',{class:'exercise '+(rank(last)===r[1]?'ok':'')},r[0]+' · '+r[1])));return c}
function historyCard(h,games){const c=card('Historique Échecs','ELO + parties/puzzles.');h.slice(-8).reverse().forEach(x=>c.append(el('div',{class:'exercise'},x.date+' · ELO '+x.elo+' · '+rank(x.elo)+' · '+(x.note||''))));games.slice(-8).reverse().forEach(x=>c.append(el('div',{class:'exercise'},x.date+' · '+x.result+' · puzzles '+(x.puzzles||0)+' · acc '+(x.accuracy||'-')+'% · '+(x.opening||'-')+' · erreur: '+(x.mistake||'-'))));return c}
function reading(root,rr){const st=Store.get('reading_tracks',{});root.append(readingStats(st));Object.entries(TRACKS).forEach(([id,t])=>root.append(trackCard(id,t,st,rr)))}
function trackCard(id,t,st,rr){const s=st[id]||{index:0,books:{}};const c=card(t.label,'Parcours séquentiel: livre actif → notes → action → suivant.');t.books.forEach((b,i)=>{const bid=id+'_'+i,rec=s.books?.[bid]||{current:0,total:0,done:false,notes:{}};const locked=i>s.index,active=i===s.index&&!rec.done;const row=el('div',{class:'exercise '+(rec.done?'ok':locked?'warn':'')});row.append(el('b',{},(rec.done?'✅ ':locked?'🔒 ':active?'📘 ':'')+b[0]+' · '+b[1]));row.append(el('div',{class:'small muted'},b[2]+' · Amazon.fr à vérifier avant achat'));row.append(el('div',{class:'small muted'},'Progression: '+(rec.current||0)+'/'+(rec.total||'?')+' pages · utilité '+(rec.notes?.utility||'-')+'/5'));row.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct(rec.current,rec.total)+'%'})));if(active)row.append(readingControls(id,bid,b,rec,rr));if(rec.notes?.ideas)row.append(el('div',{class:'small muted'},'Idées: '+rec.notes.ideas));if(rec.notes?.action)row.append(el('div',{class:'small muted'},'Action: '+rec.notes.action));c.append(row)});return c}
function readingControls(track,bid,b,rec,rr){const box=el('div');const cur=input('pages lues','number',rec.current||''),total=input('pages totales','number',rec.total||''),add=input('+ pages','number',''),today=input('objectif pages jour','number',rec.todayTarget||20);const ideas=area('idées clés',rec.notes?.ideas||''),action=area('action à appliquer',rec.notes?.action||''),quote=area('citation perso / phrase clé',rec.notes?.quote||''),utility=select(['1','2','3','4','5'],String(rec.notes?.utility||3));box.append(el('div',{class:'row'},[cur,total,add,today,utility]));box.append(ideas,action,quote);box.append(el('div',{class:'row'},[el('button',{class:'btn',onclick:()=>{saveBook(track,bid,b,Math.max(+cur.value||0,(+rec.current||0)+(+add.value||0)),+total.value||rec.total||0,false,{ideas:ideas.value,action:action.value,quote:quote.value,utility:+utility.value||3},+today.value||0);toast('Lecture sauvegardée');rr()}},'Sauver'),el('button',{class:'btn green',onclick:()=>{saveBook(track,bid,b,+total.value||rec.total||rec.current||0,+total.value||rec.total||rec.current||0,true,{ideas:ideas.value,action:action.value,quote:quote.value,utility:+utility.value||3},+today.value||0);toast('Livre terminé, suivant débloqué');rr()}},'Terminer et suivant')]));return box}
function saveBook(track,bid,b,current,total,finish,notes={},todayTarget=0){const st=Store.get('reading_tracks',{});const s=st[track]||{index:0,books:{}};s.books=s.books||{};const prev=s.books[bid]||{current:0};const delta=Math.max(0,(+current||0)-(+prev.current||0));const done=finish||(total&&current>=total);s.books[bid]={title:b[0],author:b[1],current,total,done,todayTarget,notes,finishedAt:done?Store.today():''};if(delta>0)Store.push('reading_activity',{date:Store.today(),track,bookId:bid,title:b[0],pages:delta,finished:done,action:notes.action||''});if(done)s.index=Math.min((s.index||0)+1,(TRACKS[track]?.books.length||1));st[track]=s;Store.set('reading_tracks',st)}
function readingStats(st){let active=0,done=0,pages=0,actions=0;Object.entries(TRACKS).forEach(([id,t])=>{const s=st[id]||{index:0,books:{}};active+=s.index<t.books.length?1:0;Object.values(s.books||{}).forEach(x=>{if(x.done)done++;pages+=+x.current||0;if(x.notes?.action)actions++})});return card('Tracker lecture','Parcours actifs '+active+' · livres terminés '+done+' · pages lues '+pages+' · actions extraites '+actions)}
function pct(a,b){return b?Math.min(100,Math.round((+a||0)/(+b||1)*100)):0}
function input(p,t='text',v=''){return el('input',{class:'input',placeholder:p,type:t,value:v,style:'max-width:160px'})}function area(p,v=''){return el('textarea',{class:'input',rows:'2',placeholder:p},v)}function select(items,v){const s=el('select',{class:'input',style:'max-width:160px'});items.forEach(x=>s.append(el('option',{value:x},x)));s.value=v;return s}
