import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='dashboard';
export function renderMoney(root,refresh){root.append(subTabs([{id:'dashboard',label:'Dashboard'},{id:'vinted',label:'Vinted'},{id:'actions',label:'Actions'},{id:'stock',label:'Stock'},{id:'finance',label:'Finance'}],panel,id=>{panel=id;refresh()}));const box=el('div');root.append(box);if(panel==='dashboard')return dashboard(box,refresh);if(panel==='actions')return actions(box,refresh);if(panel==='stock')return stock(box,refresh);if(panel==='finance')return finance(box,refresh);vinted(box,refresh)}
function input(p,t='text',v=''){return el('input',{class:'input',placeholder:p,type:t,value:v})}function select(items,v=''){const s=el('select',{class:'input'});items.forEach(x=>s.append(el('option',{value:x},x)));s.value=v;return s}
function items(){return Store.get('vinted_items',[])}function round(n){return Math.round((+n||0)*100)/100}function euro(n){return round(n).toFixed(2)+' €'}function days(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}
function boostTotal(x){return(+x.boost||0)+(x.boosts||[]).reduce((a,b)=>a+(+b.amount||0),0)}function cost(x){return(+x.buy||0)+(+x.shipping||0)+boostTotal(x)}function result(x){return(+x.sold||0)-cost(x)}function roi(x){const c=cost(x);return c?Math.round(result(x)/c*100):0}function potential(x,price=+x.asking||0){return price-cost(x)}
function numbers(list=items()){const sold=list.filter(x=>x.status==='sold'),active=list.filter(x=>x.status!=='sold'&&x.status!=='abandoned'),abandoned=list.filter(x=>x.status==='abandoned');return{total:list.length,active:active.length,sold:sold.length,abandoned:abandoned.length,activeCost:active.reduce((a,x)=>a+cost(x),0),activePotential:active.reduce((a,x)=>a+potential(x),0),revenue:sold.reduce((a,x)=>a+(+x.sold||0),0),realProfit:sold.reduce((a,x)=>a+result(x),0),losses:sold.filter(x=>result(x)<0).length,stale14:active.filter(x=>days(x)>=14).length,stale30:active.filter(x=>days(x)>=30).length,stale45:active.filter(x=>days(x)>=45).length,abandonNow:active.filter(x=>decision(x).label==='ABANDONNER').length,boostNow:active.filter(x=>decision(x).label==='BOOSTER').length,dropNow:active.filter(x=>decision(x).label==='BAISSER').length}}
function resultLabel(x){if(x.status!=='sold')return'Potentiel: '+euro(potential(x))+' · marge '+marginPct(x)+'%';const r=result(x);return(r>=0?'PROFIT réel: ':'PERTE réelle: ')+euro(r)+' · ROI '+roi(x)+'%'}function marginPct(x){const ask=+x.asking||0;return ask?Math.round(potential(x)/ask*100):0}
function suggested(x){const c=cost(x),target=round(c*(1+(+x.targetRoi||100)/100)),age=days(x),ask=+x.asking||target,floor=+x.floor||Math.ceil(c*1.15);if(age>=60)return Math.max(floor,round(ask*.65));if(age>=45)return Math.max(floor,round(ask*.75));if(age>=30)return Math.max(floor,round(ask*.84));if(age>=14)return Math.max(floor,round(ask*.9));if(age>=7)return Math.max(floor,round(ask*.95));return target}
function decision(x){if(x.status==='sold')return result(x)>=0?{label:'PROFIT',prio:'OK',score:0,why:'vente rentable'}:{label:'PERTE',prio:'N1',score:100,why:'vente à perte'};if(x.status==='abandoned')return{label:'ABANDONNÉ',prio:'OFF',score:0,why:'sorti du stock actif'};const age=days(x),c=cost(x),ask=+x.asking||0,floor=+x.floor||Math.ceil(c*1.15),boost=boostTotal(x),pot=ask-c,margin=ask?pot/ask:0,drop=suggested(x);if(!ask)return{label:'PRIX MANQUANT',prio:'N1',score:110,why:'aucun prix annonce'};if(pot<0)return{label:'ABANDONNER',prio:'N1',score:105,why:'prix actuel sous coût total'};if(age>=60)return{label:'ABANDONNER',prio:'N1',score:100,why:'≥60 jours: stock mort'};if(age>=45&&drop<=floor)return{label:'ABANDONNER',prio:'N1',score:96,why:'≥45 jours et prix au plancher'};if(boost>c*.45)return{label:'ABANDONNER',prio:'N1',score:94,why:'boosts trop élevés'};if(age>=30&&margin<.25)return{label:'ABANDONNER',prio:'N1',score:90,why:'≥30 jours avec marge faible'};if(age>=30)return{label:'BAISSER',prio:'N1',score:85,why:'≥30 jours sans vente'};if(age>=14)return{label:'BAISSER',prio:'N2',score:70,why:'≥14 jours: baisse contrôlée'};if(age>=7&&margin>=.35&&boost<c*.2)return{label:'BOOSTER',prio:'N2',score:55,why:'marge suffisante pour tester boost'};return{label:'GARDER',prio:'N3',score:20,why:'annonce saine'}}
function risk(x){const d=decision(x);if(['ABANDONNER','PERTE','PRIX MANQUANT'].includes(d.label))return'danger';if(['BAISSER','BOOSTER'].includes(d.label))return'warn';return'ok'}
function applyDecision(x){const d=decision(x),s=suggested(x);if(d.label==='ABANDONNER')return{status:'abandoned',abandonedAt:Store.today()};if(d.label==='PRIX MANQUANT')return{status:'missing_price'};if(d.label==='BAISSER')return{asking:s,status:'price_drop',priceDrops:[...(x.priceDrops||[]),{date:Store.today(),from:+x.asking||0,to:s}]};if(d.label==='BOOSTER')return{status:'boost_recommended'};return{status:x.status||'listed'}}
function dashboard(root,rr){const v=numbers(),f=financeData(),month=savingsMonth(f);const g=el('div',{class:'grid'});g.append(kpi('Profit réel',euro(v.realProfit),v.sold+' ventes · pertes '+v.losses,v.realProfit<0?'danger':'ok'));g.append(kpi('Cash stock',euro(v.activeCost),v.active+' actifs · potentiel '+euro(v.activePotential),v.activeCost>500?'warn':''));g.append(kpi('Actions Vinted',String(v.abandonNow+v.dropNow+v.boostNow),'abandon '+v.abandonNow+' · baisse '+v.dropNow+' · boost '+v.boostNow,v.abandonNow?'danger':v.dropNow?'warn':'ok'));g.append(kpi('Épargne mois',euro(month.done)+'/'+euro(month.target),'reste '+euro(Math.max(0,month.target-month.done)),month.done>=month.target?'ok':'danger'));g.append(kpi('Cash libre',euro(f.freeAfterSavings),'après charges + épargne cible',f.freeAfterSavings<0?'danger':f.freeAfterSavings<200?'warn':'ok'));g.append(kpi('Burn mensuel',euro(f.charges),'charges fixes',f.charges>f.income*.75?'danger':'warn'));root.append(g);root.append(actionsCard(rr));root.append(financeQuick(rr))}
function kpi(title,value,sub,cls=''){const c=card(title,sub,'span-4 '+cls);c.append(el('div',{class:'metric'},value));return c}
function actionsCard(rr){const list=items().filter(x=>x.status!=='sold'&&x.status!=='abandoned').sort((a,b)=>decision(b).score-decision(a).score).slice(0,5);const c=card('Décisions prioritaires','Top 5 à traiter maintenant.');list.forEach(x=>c.append(actionLine(x,rr)));return c}
function financeQuick(rr){const f=financeData(),m=savingsMonth(f);const c=card('Cashflow rapide','Revenu '+euro(f.income)+' · charges '+euro(f.charges)+' · épargne cible '+euro(m.target)+' · libre '+euro(f.freeAfterSavings));const amount=input('épargne ajoutée €','number'),note=input('note');c.append(el('div',{class:'row'},[amount,note,el('button',{class:'btn green',onclick:()=>{Store.push('savings_history',{month:currentMonth(),amount:+amount.value||0,note:note.value,date:Store.today()});toast('Épargne enregistrée');rr()}},'Ajouter épargne')]));return c}
function vinted(root,rr){const list=items();root.append(summary(list));const c=card('Ajouter article Vinted','Prix conseillé = coût total + ROI cible.');const name=input('article'),brand=input('marque'),cat=input('catégorie'),cond=select(['neuf','excellent','bon','correct'],'excellent'),buy=input('achat €','number'),ship=input('frais €','number'),boost=input('boost initial €','number'),ask=input('prix annonce €','number'),target=input('ROI cible %','number',100),floor=input('prix plancher €','number');c.append(el('div',{class:'row'},[name,brand,cat,cond,buy,ship,boost,ask,target,floor]));c.append(el('button',{class:'btn green',onclick:()=>{const total=(+buy.value||0)+(+ship.value||0)+(+boost.value||0),price=round(total*(1+(+target.value||100)/100));Store.push('vinted_items',{name:name.value,brand:brand.value,category:cat.value,condition:cond.value,buy:+buy.value||0,shipping:+ship.value||0,boost:+boost.value||0,asking:+ask.value||price,floor:+floor.value||Math.ceil(total*1.15),targetRoi:+target.value||100,sold:0,status:'listed',listedAt:Store.today(),boosts:(+boost.value||0)?[{date:Store.today(),amount:+boost.value}]:[],priceDrops:[]});toast('Article ajouté');rr()}},'Ajouter article'));root.append(c);list.slice().reverse().forEach(x=>root.append(itemCard(x,rr)))}
function summary(list){const n=numbers(list);const c=card('Résumé Vinted','Actifs '+n.active+' · vendus '+n.sold+' · abandonnés '+n.abandoned+' · ≥14j '+n.stale14+' · ≥30j '+n.stale30+' · ≥45j '+n.stale45+' · cash stock '+euro(n.activeCost)+' · profit réel '+euro(n.realProfit));c.className+=' '+(n.abandonNow?'danger':n.dropNow?'warn':'ok');return c}
function itemCard(x,rr){const d=decision(x),s=suggested(x);const c=card((d.prio||'')+' · '+d.label+' · '+(x.brand?x.brand+' · ':'')+(x.name||'Article'),'Âge '+days(x)+'j · score '+d.score+' · statut '+x.status+' · coût '+euro(cost(x))+' · annonce '+euro(x.asking||0)+' · conseillé '+euro(s)+' · plancher '+euro(x.floor||0),'span-4');c.className+=' '+risk(x);c.append(el('div',{class:'exercise-title'},resultLabel(x)));c.append(el('div',{class:'small muted'},'Décision: '+d.why+' · boosts '+euro(boostTotal(x))+' · marge '+marginPct(x)+'%'));const sold=input('vendu €','number',x.sold||''),newAsk=input('nouveau prix €','number',s),boost=input('boost €','number','');c.append(el('div',{class:'row'},[sold,el('button',{class:'btn green',onclick:()=>{Store.updateList('vinted_items',x.id,{sold:+sold.value||0,status:'sold',soldAt:Store.today(),realResult:(+sold.value||0)-cost(x)});toast('Vente enregistrée');rr()}},'Vendu'),newAsk,el('button',{class:'btn',onclick:()=>{priceDrop(x,+newAsk.value||0,rr)}},'Baisser prix'),boost,el('button',{class:'btn',onclick:()=>{const amount=+boost.value||0;Store.updateList('vinted_items',x.id,{boost:(+x.boost||0)+amount,status:'boosted',boosts:[...(x.boosts||[]),{date:Store.today(),amount}]});toast('Boost enregistré');rr()}},'Boost')]));c.append(el('div',{class:'row'},[el('button',{class:'btn green',onclick:()=>{Store.updateList('vinted_items',x.id,applyDecision(x));toast('Décision appliquée');rr()}},'Appliquer'),el('button',{class:'btn danger',onclick:()=>{Store.updateList('vinted_items',x.id,{status:'abandoned',abandonedAt:Store.today()});toast('Abandonné');rr()}},'Abandon'),el('button',{class:'btn',onclick:()=>{Store.updateList('vinted_items',x.id,{status:'listed'});toast('Remis actif');rr()}},'Réactiver')]));return c}
function actionLine(x,rr){const d=decision(x),s=suggested(x);const c=el('div',{class:'exercise '+risk(x)});c.append(el('div',{class:'row'},[el('span',{class:'pill'},d.prio),el('span',{class:'pill'},d.label),el('b',{},(x.brand?x.brand+' · ':'')+(x.name||'Article'))]));c.append(el('div',{class:'small muted'},days(x)+'j · '+d.why+' · actuel '+euro(x.asking||0)+' · conseillé '+euro(s)+' · potentiel '+euro(potential(x))));c.append(el('button',{class:'btn green',onclick:()=>{Store.updateList('vinted_items',x.id,applyDecision(x));toast('Action appliquée');rr()}},'Appliquer action'));return c}
function actions(root,rr){root.append(card('Actions Vinted du jour','Tri agressif: abandonner / baisser / booster / garder.'));items().filter(x=>x.status!=='sold'&&x.status!=='abandoned').sort((a,b)=>decision(b).score-decision(a).score).forEach(x=>root.append(actionLine(x,rr)))}
function stock(root,rr){const list=items().filter(x=>x.status!=='sold');root.append(summary(list));const buckets=[['N1 critique',x=>['ABANDONNER','PRIX MANQUANT'].includes(decision(x).label)],['À baisser',x=>decision(x).label==='BAISSER'],['À booster',x=>decision(x).label==='BOOSTER'],['À garder',x=>decision(x).label==='GARDER'],['Abandonnés',x=>x.status==='abandoned']];buckets.forEach(([title,fn])=>{const group=list.filter(fn);if(!group.length)return;const c=card(title,group.length+' articles');group.sort((a,b)=>decision(b).score-decision(a).score||days(b)-days(a)).forEach(x=>c.append(actionLine(x,rr)));root.append(c)})}
function finance(root,rr){const f=financeData();root.append(financeSummary(f));const c=card('Finance · paramètres','Charges fixes + objectif épargne.');const fields=['income','rent','energy','internet','phone','gym','insurance','contribution','other','savingsGoalPct'];const inputs={};fields.forEach(k=>{inputs[k]=input(label(k),'number',f[k]||0);c.append(inputs[k])});c.append(el('button',{class:'btn green',onclick:()=>{fields.forEach(k=>f[k]=+inputs[k].value||0);Store.set('finance_month',f);toast('Finance sauvée');rr()}},'Sauver finance'));root.append(c);root.append(savingsPanel(rr));root.append(savingsHistory())}
function financeData(){const d=Store.get('finance_month',{income:2300,rent:665,energy:100,internet:70,phone:15,gym:30,insurance:115,contribution:500,other:0,savingsGoalPct:20});const charges=(+d.rent||0)+(+d.energy||0)+(+d.internet||0)+(+d.phone||0)+(+d.gym||0)+(+d.insurance||0)+(+d.contribution||0)+(+d.other||0),target=Math.round((+d.income||0)*(+d.savingsGoalPct||0)/100);return{...d,charges,savingsTarget:target,freeBeforeSavings:(+d.income||0)-charges,freeAfterSavings:(+d.income||0)-charges-target}}
function financeSummary(f){const m=savingsMonth(f);const g=el('div',{class:'grid'});g.append(kpi('Revenu',euro(f.income),'mensuel'));g.append(kpi('Charges',euro(f.charges),'fixes',f.charges>f.income*.75?'danger':'warn'));g.append(kpi('Libre avant épargne',euro(f.freeBeforeSavings),'revenu - charges',f.freeBeforeSavings<0?'danger':'ok'));g.append(kpi('Épargne cible',euro(m.target),'mensuelle'));g.append(kpi('Épargné',euro(m.done),'ce mois',m.done>=m.target?'ok':'warn'));g.append(kpi('Libre final',euro(f.freeAfterSavings),'après cible',f.freeAfterSavings<0?'danger':f.freeAfterSavings<200?'warn':'ok'));return g}
function savingsPanel(rr){const f=financeData(),m=savingsMonth(f);const c=card('Épargne mensuelle','Cible '+euro(m.target)+' · déjà '+euro(m.done)+' · reste '+euro(Math.max(0,m.target-m.done)));c.className+=' '+(m.done>=m.target?'ok':m.done?'warn':'danger');const amount=input('épargne ajoutée €','number'),note=input('note');c.append(el('div',{class:'row'},[amount,note,el('button',{class:'btn green',onclick:()=>{Store.push('savings_history',{month:currentMonth(),amount:+amount.value||0,note:note.value,date:Store.today()});toast('Épargne enregistrée');rr()}},'Ajouter épargne')]));return c}
function savingsHistory(){const h=card('Historique épargne','Derniers mouvements.');Store.get('savings_history',[]).slice(-18).reverse().forEach(x=>h.append(el('div',{class:'exercise'},(x.date||'-')+' · '+x.month+' · '+euro(x.amount)+' · '+(x.note||''))));return h}
function savingsMonth(f=financeData()){const month=currentMonth();const done=Store.get('savings_history',[]).filter(x=>x.month===month).reduce((a,x)=>a+(+x.amount||0),0);return{month,target:f.savingsTarget,done}}
function currentMonth(){return new Date().toISOString().slice(0,7)}function priceDrop(x,value,rr){const to=+value||0;Store.updateList('vinted_items',x.id,{asking:to,status:'price_drop',priceDrops:[...(x.priceDrops||[]),{date:Store.today(),from:+x.asking||0,to}]});toast('Prix baissé');rr()}
function label(f){return{income:'revenu',rent:'loyer',energy:'énergie',internet:'internet',phone:'téléphone',gym:'salle sport',insurance:'assurance',contribution:'contribution',other:'autres',savingsGoalPct:'épargne cible %'}[f]||f}
