import { DAILY_DOMAINS, PRACTICE_SITES, PRACTICE_QUEUE } from '../assets/js/practice-catalog.js';
import { BOOKS } from '../assets/js/study-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let domain='coding';
const domains=()=>[...DAILY_DOMAINS,'sql','web','nl'];
const S=()=>Store.get('practice_state',{});
const W=s=>Store.set('practice_state',s);
const D=s=>{s[domain]=s[domain]||{bookIndex:0,books:{},index:0,done:{},notes:{}};s[domain].books=s[domain].books||{};s[domain].done=s[domain].done||{};return s[domain]};
export function renderPractice(root,rr){root.append(card('Practice quotidien','Livres + exercices par domaine. Coding, IA, IoT, Réparation: étude et pratique tous les jours.'));root.append(subTabs(domains().map(x=>({id:x,label:x.toUpperCase()})),domain,id=>{domain=id;rr()}));resume(root);books(root,rr);sites(root,rr);queue(root,rr)}
function resume(root){const s=D(S());const b=BOOKS[domain]||[],q=PRACTICE_QUEUE[domain]||[];root.append(card('Reprise '+domain.toUpperCase(),'Livre: '+(b[s.bookIndex]||'terminé')+' · Exercice: '+(q[s.index]||'terminé')))}
function books(root,rr){const all=S(),s=D(all),b=BOOKS[domain]||[];const c=card('Étude / livres '+domain.toUpperCase(),'Un livre actif. Mets le total pages, valide les pages faites, puis débloque le suivant.');if(!b.length)c.append(el('div',{class:'exercise'},'Aucun livre configuré.'));b.forEach((name,i)=>{const p=s.books[name]||{current:0,total:0,done:false};const locked=i>s.bookIndex,done=p.done;const row=el('div',{class:'exercise '+(done?'ok':locked?'warn':'')});row.append(el('div',{class:'exercise-title'},(done?'✅ ':locked?'🔒 ':'📘 ')+name));row.append(el('div',{class:'small muted'},p.current+'/'+(p.total||'?')+' pages'));row.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct(p.current,p.total)+'%'})));if(!locked&&!done){const total=input('total pages',p.total||''),add=input('+ pages','');row.append(el('div',{class:'row'},[total,add,el('button',{class:'btn',onclick:()=>{saveBook(all,s,name,+add.value||0,+total.value||0,false);toast('Pages sauvées');rr()}},'Valider pages'),el('button',{class:'btn green',onclick:()=>{saveBook(all,s,name,+add.value||0,+total.value||0,true);toast('Livre terminé');rr()}},'Terminer livre')]))}c.append(row)});root.append(c)}
function saveBook(all,s,name,delta,total,finish){const p=s.books[name]||{current:0,total:0,done:false};p.total=total||p.total||0;p.current=finish?(p.total||p.current+delta):p.current+delta;if(finish||(p.total&&p.current>=p.total)){p.done=true;s.bookIndex=Math.min((s.bookIndex||0)+1,(BOOKS[domain]||[]).length)}s.books[name]=p;all[domain]=s;W(all);Store.push('study_activity',{domain,kind:'book',title:name,delta,total:p.total,finished:p.done,date:Store.today()})}
function sites(root,rr){const c=card('Sites / challenges '+domain.toUpperCase(),'Ajout rapide au matériel.');(PRACTICE_SITES[domain]||[]).forEach(x=>c.append(el('div',{class:'exercise'},[el('b',{},x[0]),el('div',{class:'small muted'},x[2]),el('button',{class:'btn',onclick:()=>{Store.push('study_materials',{course:domain,source:'site',title:x[0],url:x[1],current:0,total:0,status:'active'});toast('Site ajouté');rr()}},'Ajouter site')])));root.append(c)}
function queue(root,rr){const all=S(),s=D(all),q=PRACTICE_QUEUE[domain]||[];const c=card('File exercices '+domain.toUpperCase(),'Un exercice actif. Valide pour débloquer le suivant.');q.forEach((name,i)=>{const done=s.done[name],locked=i>s.index;const row=el('div',{class:'exercise '+(done?'ok':locked?'warn':'')});row.append(el('div',{class:'exercise-title'},(done?'✅ ':locked?'🔒 ':'🎯 ')+name));if(!locked&&!done){const note=el('input',{class:'input',placeholder:'note / erreur'});row.append(el('button',{class:'btn green',onclick:()=>{s.done[name]=true;s.notes[name]=note.value;s.index=Math.min(s.index+1,q.length);all[domain]=s;W(all);Store.push('study_activity',{domain,kind:'exercise',title:name,note:note.value,date:Store.today()});toast('Exercice validé');rr()}},'Valider'));row.append(note)}c.append(row)});root.append(c)}
function input(p,v){return el('input',{class:'input',placeholder:p,type:'number',value:v,style:'max-width:150px'})}
function pct(a,b){return b?Math.min(100,Math.round((+a||0)/(+b||1)*100)):0}
