import { EPFC_YEAR1 } from '../assets/js/epfc-year1.js';
import { EPFC_DAILY_ROTATION } from '../assets/js/practice-catalog.js';
import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import { SPORT_CYCLE } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, toast, isSimple } from '../assets/js/ui.js';
import { xpFor } from './game.js';
const SUPPS={morning:[['creatine','Creatine','3-5 g'],['vitaminD','Vitamine D3','1000-2000 UI'],['omega3','Omega-3','1-2 g EPA+DHA'],['zinc','Zinc','10-15 mg optionnel']],focus:[['caffeine','Cafeine','100-200 mg'],['theanine','L-theanine','100-200 mg']],evening:[['magnesium','Magnesium glycinate','200-400 mg']]};
export function renderRoutine(root,rr){const d=get(),raw=makePlan(d.cfg),fit=fitPlan(raw,d.cfg),plan=schedule(fit.plan,d.cfg),next=plan.find(x=>!d.done[x.id]);root.append(command(d,plan,fit,next,rr));root.append(config(d,rr));const grid=el('div',{class:'grid'});grid.append(timeline(plan,d,rr));if(!isSimple())grid.append(sidePanel(plan,d,fit,rr));root.append(grid);if(!isSimple()&&fit.dropped.length)root.append(droppedCard(fit.dropped));if(!isSimple())root.append(notes(d,rr));}
function key(){return 'routine_'+Store.today()}function get(){return Store.get(key(),{cfg:{work:false,workStart:'09:00',workEnd:'17:30',school:false,schoolStart:'18:00',schoolEnd:'21:30',fatigue:3,wake:'07:00',sleep:'23:30',commuteMin:45,mealsMin:75},done:{},notes:''})}function set(d){Store.set(key(),d)}
function command(d,plan,fit,next,rr){const n=plan.filter(x=>d.done[x.id]).length,doneXp=plan.filter(x=>d.done[x.id]).reduce((a,x)=>a+xpFor(x.id),0),maxXp=plan.reduce((a,x)=>a+xpFor(x.id),0),pct=Math.round(n/Math.max(1,plan.length)*100);const c=card('Routine · timeline opérationnelle',next?'Prochaine action: '+next.time+' · '+next.title:'Plan terminé.','span-12');c.className+=' '+(next?'warn':'ok');c.append(el('div',{class:'grid'},[mini('Blocs',n+'/'+plan.length,pct+'%'),mini('XP',doneXp+'/'+maxXp,'validé'),mini('Temps',fit.planned+'/'+fit.budget+' min','planifié'),!isSimple()?mini('Fatigue',String(d.cfg.fatigue||3)+'/5',d.cfg.work?'travail':'libre'):null].filter(Boolean)));c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct+'%'})));if(next)c.append(el('button',{class:'btn green',onclick:()=>{d.done[next.id]=true;set(d);Store.push('study_activity',{domain:'routine',kind:next.p,title:next.title,time:next.time,status:'done',date:Store.today()});toast('Prochaine action validée');rr()}},'Valider prochaine action'));return c}
function mini(t,v,s){const c=card(t,s,'span-4');c.append(el('div',{class:'metric'},v));return c}
function config(d,rr){const c=card('Journée','Active uniquement ce qui existe aujourd’hui. Les heures disparaissent si OFF.');const cfg=d.cfg;const work=check(cfg.work),school=check(cfg.school),ws=inp('début','time',cfg.workStart),we=inp('fin','time',cfg.workEnd),ss=inp('début','time',cfg.schoolStart),se=inp('fin','time',cfg.schoolEnd),fat=sel(['1','2','3','4','5'],String(cfg.fatigue||3)),wake=inp('réveil','time',cfg.wake||'07:00'),sleep=inp('sommeil','time',cfg.sleep||'23:30'),comm=inp('transport min','number',cfg.commuteMin??45),meals=inp('repas/admin min','number',cfg.mealsMin??75);c.append(el('div',{class:'grid'},[toggleBlock('Travail',work,[ws,we]),toggleBlock('Cours / école',school,[ss,se]),simpleBlock('Fatigue',fat)]));if(!isSimple()){const adv=el('details',{class:'exercise'});adv.append(el('summary',{class:'exercise-title'},'Avancé: sommeil / transport / repas'));adv.append(el('div',{class:'row'},[wake,sleep,comm,meals]));c.append(adv)}c.append(el('button',{class:'btn green',onclick:()=>{d.cfg={work:work.checked,workStart:ws.value,workEnd:we.value,school:school.checked,schoolStart:ss.value,schoolEnd:se.value,fatigue:+fat.value||3,wake:wake.value,sleep:sleep.value,commuteMin:+comm.value||0,mealsMin:+meals.value||0};d.done={};set(d);toast('Routine recalculée');rr()}},'Sauver et calculer'));return c}
function toggleBlock(title,box,fields){const b=el('div',{class:'exercise span-4'}),status=el('span',{class:'pill'},box.checked?'ON':'OFF'),body=el('div',{class:'row'});fields.forEach(f=>body.append(f));function sync(){status.textContent=box.checked?'ON':'OFF';body.style.display=box.checked?'flex':'none'}box.addEventListener('change',sync);b.append(el('div',{class:'row'},[el('span',{class:'pill'},title),box,status]),body);sync();return b}
function simpleBlock(title,field){const b=el('div',{class:'exercise span-4'});b.append(el('div',{class:'row'},[el('span',{class:'pill'},title),field]));return b}
function timeline(plan,d,rr){const c=card('Timeline du jour','Ordre réel, horaires, priorité, XP.',isSimple()?'span-12':'span-8');plan.slice(0,isSimple()?8:plan.length).forEach((x,i)=>c.append(row(x,i,d,rr)));if(isSimple()&&plan.length>8)c.append(el('div',{class:'small muted'},'Mode simple: '+(plan.length-8)+' blocs masqués. Passe en Expert pour tout voir.'));return c}
function row(x,i,d,rr){const ok=!!d.done[x.id],cls=ok?'ok':x.p==='N1'?'danger':x.p==='N2'?'warn':'';const r=el('div',{class:'exercise '+cls});r.append(el('div',{class:'row'},[el('span',{class:'pill'},String(i+1).padStart(2,'0')),el('span',{class:'pill'},x.p),!isSimple()?el('span',{class:'pill'},xpFor(x.id)+' XP'):null,el('span',{class:'pill'},x.time||'-'),el('b',{},x.title)].filter(Boolean)));r.append(el('div',{class:'small muted'},x.desc));if(x.suppGroup&&!isSimple())r.append(suppBlock(x.suppGroup,rr));r.append(el('button',{class:'btn '+(ok?'green':''),onclick:()=>{d.done[x.id]=!ok;set(d);Store.push('study_activity',{domain:'routine',kind:x.p,title:x.title,time:x.time,status:d.done[x.id]?'done':'open',date:Store.today()});toast(d.done[x.id]?'Bloc validé':'Bloc rouvert');rr()}},ok?'Validé':'Valider'));return r}
function sidePanel(plan,d,fit,rr){const c=card('Contrôle mission','Vue compacte par priorité.','span-4');['N1','N2','N3'].forEach(p=>{const list=plan.filter(x=>x.p===p),done=list.filter(x=>d.done[x.id]).length;c.append(el('div',{class:'exercise '+(p==='N1'&&done<list.length?'danger':done?'ok':'')},[el('div',{class:'exercise-title'},p+' · '+done+'/'+list.length),el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+Math.round(done/Math.max(1,list.length)*100)+'%'}))]));});c.append(el('div',{class:'exercise'},'Temps disponible: '+fit.budget+' min · planifié: '+fit.planned+' min'));c.append(el('button',{class:'btn',onclick:()=>{d.done={};set(d);toast('Routine remise à zéro');rr()}},'Reset validations du jour'));return c}
function makePlan(cfg){const ep=epfcToday(),f=+cfg.fatigue||3,heavy=cfg.work&&cfg.school,dead=f>=5,tired=f>=4,focusStart=pickStart(cfg);let a=[B('supp_morning','N1','Supplements matin','Créatine + D3 + Oméga-3 + Zinc optionnel','08:00',5,'morning'),B('brief','N1','Briefing','Lire la reprise. 5 min','',5),B('epfc','N1','EPFC du jour',ep.code+' · '+ep.title+' → '+epfcResume(ep.code),'',dead?15:tired||heavy?25:45),B('nl','N1','NL / SELOR',nlResume(),'',dead?5:tired||heavy?10:20),B('review','N1','Review reprise','Erreur, blocage, prochaine action.','',5),B('supp_evening','N1','Supplements soir','Magnésium glycinate','22:30',5,'evening')];if(cfg.work)a.splice(1,0,B('work','N1','Travail',cfg.workStart+' → '+cfg.workEnd,cfg.workStart+' → '+cfg.workEnd,0));if(cfg.school)a.splice(cfg.work?2:1,0,B('school','N1','Cours',cfg.schoolStart+' → '+cfg.schoolEnd,cfg.schoolStart+' → '+cfg.schoolEnd,0));if(!isLate(focusStart))a.splice(2,0,B('supp_focus','N2','Supplements focus','Caféine + L-théanine 30-60 min avant focus',addMin(focusStart,-30),5,'focus'));if(dead){a.push(B('chess','N3','Échecs','Mini bloc: 1 partie ou 5 puzzles · '+chessDesc(),'',10));return a}if(!tired){a.push(B('coding','N2','Coding',trk('coding'),'',20),B('ai','N2','IA',trk('ai'),'',20),B('iot','N2','IoT',trk('iot'),'',20),B('repair','N2','Réparation',trk('repair'),'',20));}else{a.push(B('coding','N2','Coding',trk('coding'),'',10),B('iot','N2','IoT',trk('iot'),'',10));}a.push(B('proof','N2','Preuve du jour','Note, lien, capture ou exercice validé.','',5));a.push(B('vinted','N2','Vinted urgent',vintedDesc(),'',10));a.push(B('chess','N3','Échecs',chessDesc(),'',15));a.push(B('reading','N3','Lecture scientifique',readingDesc(),'',20));a.push(B('sport','N3','Sport','Séance '+sportToday(),'',tired?15:45));a.push(B('admin','N3','Admin rapide','Préparer demain / argent.','',10));return a}
function B(id,p,title,desc,time='',min=5,suppGroup=''){return{id,p,title,desc,time,min,suppGroup}}
function fitPlan(plan,cfg){const budget=timeBudget(cfg).availablePersonal;let keep=[...plan],drop=[];const mins=a=>a.reduce((s,x)=>s+(+x.min||0),0);if((+cfg.fatigue||3)>=5)keep=keep.filter(x=>x.p==='N1'||x.id==='chess');while(mins(keep)>budget&&keep.some(x=>x.p==='N3')){const i=keep.map(x=>x.p).lastIndexOf('N3');drop.unshift(keep.splice(i,1)[0])}while(mins(keep)>budget&&keep.some(x=>x.p==='N2')){const i=keep.map(x=>x.p).lastIndexOf('N2');drop.unshift(keep.splice(i,1)[0])}return{plan:keep,dropped:drop,budget,planned:mins(keep)}}
function timeBudget(cfg){const awake=diffMin(cfg.wake||'07:00',cfg.sleep||'23:30'),work=cfg.work?diffMin(cfg.workStart,cfg.workEnd):0,school=cfg.school?diffMin(cfg.schoolStart,cfg.schoolEnd):0,commute=(cfg.work||cfg.school)?(+cfg.commuteMin||0):0,meals=+cfg.mealsMin||0;return{awake,work,school,commute,meals,availablePersonal:Math.max(20,awake-work-school-commute-meals)}}
function schedule(plan,cfg){let cursor=pickStart(cfg);return plan.map(b=>{if(b.time)return b;if(b.min===0)return b;let start=cursor,end=addMin(start,b.min||5);cursor=addMin(end,5);return{...b,time:start+' → '+end}})}
function droppedCard(list){const c=card('Blocs retirés automatiquement','Ils ne rentrent pas dans le temps disponible.');list.forEach(x=>c.append(el('div',{class:'exercise'},x.p+' · '+x.title+' · '+x.min+' min')));return c}
function suppBlock(group,rr){const data=Store.get('supplements_'+Store.today(),{});const box=el('div',{class:'exercise'});(SUPPS[group]||[]).forEach(s=>{const rec=data[s[0]]||{taken:false,dose:s[2],time:''};const dose=inp('dose','text',rec.dose),time=inp('heure','time',rec.time);box.append(el('div',{class:'exercise'},[el('b',{},s[1]),el('div',{class:'small muted'},s[2]),el('div',{class:'row'},[dose,time,el('button',{class:'btn '+(rec.taken?'green':''),onclick:()=>{data[s[0]]={taken:!rec.taken,dose:dose.value,time:time.value};Store.set('supplements_'+Store.today(),data);toast(data[s[0]].taken?'Pris':'Rouvert');rr()}},rec.taken?'Pris':'Marquer pris')])]))});return box}
function notes(d,rr){const c=card('Notes routine','Reprise exacte et blocages.');const t=el('textarea',{class:'input',rows:'3',placeholder:'reprise, blocage, prochaine action'},d.notes||'');c.append(t);c.append(el('button',{class:'btn green',onclick:()=>{d.notes=t.value;set(d);toast('Notes sauvegardées');rr()}},'Sauver notes'));return c}
function check(v){const x=el('input',{type:'checkbox'});x.checked=!!v;return x}function inp(p,t='text',v=''){return el('input',{class:'input',placeholder:p,type:t,value:v,style:'max-width:170px'})}function sel(items,v){const s=el('select',{class:'input',style:'max-width:170px'});items.forEach(x=>s.append(el('option',{value:x},x)));s.value=v;return s}
function pickStart(cfg){if(cfg.work&&cfg.school)return addMin(cfg.schoolEnd,20);if(cfg.work)return addMin(cfg.workEnd,30);if(cfg.school)return addMin(cfg.schoolEnd,20);return '09:00'}function isLate(t){return +String(t).split(':')[0]>=16}function toMin(t){let[a,b]=String(t||'00:00').split(':').map(Number);return a*60+b}function diffMin(a,b){let d=toMin(b)-toMin(a);if(d<0)d+=1440;return d}function addMin(t,m){let[a,b]=String(t||'09:00').split(':').map(Number);let x=a*60+b+m;while(x<0)x+=1440;while(x>=1440)x-=1440;return String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0')}
function vintedDesc(){const list=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned');const n30=list.filter(x=>age(x)>=30).length,n14=list.filter(x=>age(x)>=14).length;if(n30)return n30+' articles ≥30j: baisser, booster ou abandonner';if(n14)return n14+' articles ≥14j: baisser prix';return 'Vérifier stock, messages, prix, boosts si besoin'}function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}function chessDesc(){const h=Store.get('chess_elo_history',[]),last=h[h.length-1];return last?'ELO '+last.elo+' · 1 partie analysée ou 5 puzzles':'ELO à logger + 1 partie ou 5 puzzles'}function readingDesc(){const st=Store.get('reading_tracks',{});let active='choisir un parcours et lire 10-20 pages';Object.values(st).some(track=>Object.values(track.books||{}).some(b=>{if(!b.done&&b.current!==undefined){active=b.title+' · '+(b.current||0)+'/'+(b.total||'?')+' pages';return true}return false}));return active}
function epfcToday(){return courseByCode(EPFC_DAILY_ROTATION[dayIndex(new Date())%EPFC_DAILY_ROTATION.length])}function dayIndex(d){const start=new Date(d.getFullYear(),0,1);return Math.floor((d-start)/86400000)}function courseByCode(code){return EPFC_YEAR1.find(c=>c.code===code)||EPFC_YEAR1[0]}function epfcResume(code){const st=Store.get('epfc_y1_state',{})[code]||{};const r=courseByCode(code).resources[st.activeIndex||0];if(!r)return 'parcours terminé';const p=st.progress?.[r[0]]||{};return r[1]+' · '+(p.current||0)+'/'+(p.total||'?')+' '+r[3]}function trk(track){const s=Store.get('track_state',{})[track]||{};return 'Livre: '+((BOOKS[track]||[])[s.bookIndex||0]||'terminé')+' · Exercice: '+((EXERCISE_PACKS[track]||[])[s.exerciseIndex||0]||'terminé')}function nlResume(){const d=Store.get('nl_program',{level:'A1',target:'SELOR'});return d.level+' → '+d.target}function sportToday(){const c=Store.sportCycle(),diff=Math.floor((new Date(Store.today())-new Date(c.anchorDate))/86400000),start=SPORT_CYCLE.indexOf(c.anchorType);return SPORT_CYCLE[((start<0?0:start)+diff%SPORT_CYCLE.length+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
