import { EPFC_YEAR1 } from '../assets/js/epfc-year1.js';
import { EPFC_DAILY_ROTATION } from '../assets/js/practice-catalog.js';
import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import { SPORT_CYCLE } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, toast } from '../assets/js/ui.js';
import { xpFor } from './game.js';
const SUPPS={morning:[['creatine','Creatine','3-5 g'],['vitaminD','Vitamine D3','1000-2000 UI'],['omega3','Omega-3','1-2 g EPA+DHA'],['zinc','Zinc','10-15 mg optionnel']],focus:[['caffeine','Cafeine','100-200 mg'],['theanine','L-theanine','100-200 mg']],evening:[['magnesium','Magnesium glycinate','200-400 mg']]};
export function renderRoutine(root,rr){const d=get();root.append(config(d,rr));const raw=makePlan(d.cfg);const kept=fitPlan(raw,d.cfg);const plan=schedule(kept.plan,d.cfg);root.append(score(plan,d,kept));const g=el('div',{class:'grid'});plan.forEach(x=>g.append(tile(x,d,rr)));root.append(g);if(kept.dropped.length)root.append(droppedCard(kept.dropped));root.append(notes(d,rr));}
function key(){return 'routine_'+Store.today()}function get(){return Store.get(key(),{cfg:{work:false,workStart:'09:00',workEnd:'17:30',school:false,schoolStart:'18:00',schoolEnd:'21:30',fatigue:3,wake:'07:00',sleep:'23:30',commuteMin:45,mealsMin:75},done:{},notes:''})}function set(d){Store.set(key(),d)}
function config(d,rr){const c=card('Routine adaptative','Le planning respecte le temps disponible réel. Si ça ne rentre pas, les N3 puis N2 sautent automatiquement.');const cfg=d.cfg;const work=check(cfg.work),school=check(cfg.school),ws=inp('debut travail','time',cfg.workStart),we=inp('fin travail','time',cfg.workEnd),ss=inp('debut cours','time',cfg.schoolStart),se=inp('fin cours','time',cfg.schoolEnd),fat=sel(['1','2','3','4','5'],String(cfg.fatigue||3)),wake=inp('réveil','time',cfg.wake||'07:00'),sleep=inp('sommeil','time',cfg.sleep||'23:30'),comm=inp('transport min','number',cfg.commuteMin??45),meals=inp('repas/admin vital min','number',cfg.mealsMin??75);c.append(el('div',{class:'exercise'},[el('b',{},'Travail aujourd hui ?'),work,ws,we]));c.append(el('div',{class:'exercise'},[el('b',{},'Cours aujourd hui ?'),school,ss,se]));c.append(el('div',{class:'exercise'},[el('b',{},'Fatigue 1-5'),fat,wake,sleep,comm,meals]));c.append(el('button',{class:'btn green',onclick:()=>{d.cfg={work:work.checked,workStart:ws.value,workEnd:we.value,school:school.checked,schoolStart:ss.value,schoolEnd:se.value,fatigue:+fat.value||3,wake:wake.value,sleep:sleep.value,commuteMin:+comm.value||0,mealsMin:+meals.value||0};d.done={};set(d);toast('Routine recalculée');rr()}},'Sauver et recalculer'));return c}
function makePlan(cfg){const ep=epfcToday(),f=+cfg.fatigue||3,heavy=cfg.work&&cfg.school,dead=f>=5,tired=f>=4,focusStart=pickStart(cfg);let a=[B('supp_morning','N1','Supplements matin','Creatine + D3 + Omega-3 + Zinc optionnel','08:00',5,'morning'),B('brief','N1','Briefing','Lire la reprise. 5 min','',5),B('epfc','N1','EPFC du jour',ep.code+' · '+ep.title+' → '+epfcResume(ep.code),'',dead?15:tired||heavy?25:45),B('nl','N1','NL / SELOR',nlResume(),'',dead?5:tired||heavy?10:20),B('review','N1','Review reprise','Erreur, blocage, prochaine action.','',5),B('supp_evening','N1','Supplements soir','Magnesium glycinate','22:30',5,'evening')];if(cfg.work)a.splice(1,0,B('work','N1','Travail',cfg.workStart+' -> '+cfg.workEnd,cfg.workStart+' -> '+cfg.workEnd,0));if(cfg.school)a.splice(cfg.work?2:1,0,B('school','N1','Cours',cfg.schoolStart+' -> '+cfg.schoolEnd,cfg.schoolStart+' -> '+cfg.schoolEnd,0));if(!isLate(focusStart))a.splice(2,0,B('supp_focus','N2','Supplements focus','Cafeine + L-theanine 30-60 min avant focus',addMin(focusStart,-30),5,'focus'));if(dead){a.push(B('chess','N3','Echecs','Mini bloc: 1 partie ou 5 puzzles · '+chessDesc(),'',10));return a}if(!tired){a.push(B('coding','N2','Coding',trk('coding'),'',20),B('ai','N2','IA',trk('ai'),'',20),B('iot','N2','IoT',trk('iot'),'',20),B('repair','N2','Reparation',trk('repair'),'',20));}else{a.push(B('coding','N2','Coding',trk('coding'),'',10),B('iot','N2','IoT',trk('iot'),'',10));}a.push(B('proof','N2','Preuve du jour','Note, lien, capture ou exercice valide.','',5));a.push(B('vinted','N2','Vinted urgent',vintedDesc(),'',10));a.push(B('chess','N3','Echecs',chessDesc(),'',15));a.push(B('reading','N3','Lecture scientifique',readingDesc(),'',20));a.push(B('sport','N3','Sport','Seance '+sportToday(),'',tired?15:45));a.push(B('admin','N3','Admin rapide','Preparer demain / argent.','',10));return a}
function B(id,p,title,desc,time='',min=5,suppGroup=''){return{id,p,title,desc,time,min,suppGroup}}
function fitPlan(plan,cfg){const budget=timeBudget(cfg).availablePersonal;let keep=[...plan],drop=[];const mins=a=>a.reduce((s,x)=>s+(+x.min||0),0);if((+cfg.fatigue||3)>=5)keep=keep.filter(x=>x.p==='N1'||x.id==='chess');while(mins(keep)>budget&&keep.some(x=>x.p==='N3')){const i=keep.map(x=>x.p).lastIndexOf('N3');drop.unshift(keep.splice(i,1)[0])}while(mins(keep)>budget&&keep.some(x=>x.p==='N2')){const i=keep.map(x=>x.p).lastIndexOf('N2');drop.unshift(keep.splice(i,1)[0])}return{plan:keep,dropped:drop,budget,planned:mins(keep)}}
function timeBudget(cfg){const awake=diffMin(cfg.wake||'07:00',cfg.sleep||'23:30');const work=cfg.work?diffMin(cfg.workStart,cfg.workEnd):0,school=cfg.school?diffMin(cfg.schoolStart,cfg.schoolEnd):0;const commute=(cfg.work||cfg.school)?(+cfg.commuteMin||0):0,meals=+cfg.mealsMin||0;return{awake,work,school,commute,meals,availablePersonal:Math.max(20,awake-work-school-commute-meals)}}
function schedule(plan,cfg){let cursor=pickStart(cfg);return plan.map(b=>{if(b.time)return b;if(b.min===0)return b;let start=cursor,end=addMin(start,b.min||5);cursor=addMin(end,5);return{...b,time:start+' -> '+end}})}
function pickStart(cfg){if(cfg.work&&cfg.school)return addMin(cfg.schoolEnd,20);if(cfg.work)return addMin(cfg.workEnd,30);if(cfg.school)return addMin(cfg.schoolEnd,20);return '09:00'}function isLate(t){const h=+String(t).split(':')[0];return h>=16}function toMin(t){let[a,b]=String(t||'00:00').split(':').map(Number);return a*60+b}function diffMin(a,b){let d=toMin(b)-toMin(a);if(d<0)d+=1440;return d}function addMin(t,m){let[a,b]=String(t||'09:00').split(':').map(Number);let x=a*60+b+m;while(x<0)x+=1440;while(x>=1440)x-=1440;return String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0')}
function score(plan,d,fit){const n=plan.filter(x=>d.done[x.id]).length,doneXp=plan.filter(x=>d.done[x.id]).reduce((a,x)=>a+xpFor(x.id),0),maxXp=plan.reduce((a,x)=>a+xpFor(x.id),0);const c=card('Plan du jour','Validé '+n+'/'+plan.length+' · '+doneXp+'/'+maxXp+' XP · temps perso '+fit.planned+'/'+fit.budget+' min');c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+Math.round(n/plan.length*100)+'%'})));return c}
function droppedCard(list){const c=card('Blocs supprimés automatiquement','Ils ne rentrent pas dans le temps disponible. Ils ne comptent pas contre toi.');list.forEach(x=>c.append(el('div',{class:'exercise'},x.p+' · '+x.title+' · '+x.min+' min')));return c}
function tile(x,d,rr){const ok=!!d.done[x.id];const cls=x.p==='N1'?'danger':x.p==='N2'?'warn':'ok';const c=card(x.p+' · '+xpFor(x.id)+' XP · '+x.time+' · '+x.title,x.desc,x.p==='N1'?'span-6':'span-4');c.className+=' '+cls+' '+(ok?'ok':'');if(x.suppGroup)c.append(suppBlock(x.suppGroup,rr));c.append(el('button',{class:'btn '+(ok?'green':''),onclick:()=>{d.done[x.id]=!ok;set(d);Store.push('study_activity',{domain:'routine',kind:x.p,title:x.title,time:x.time,status:d.done[x.id]?'done':'open',date:Store.today()});toast(d.done[x.id]?'Bloc valide':'Bloc rouvert');rr()}},ok?'Valide':'Valider'));return c}
function suppBlock(group,rr){const data=Store.get('supplements_'+Store.today(),{});const box=el('div',{class:'exercise'});(SUPPS[group]||[]).forEach(s=>{const rec=data[s[0]]||{taken:false,dose:s[2],time:''};const dose=inp('dose','text',rec.dose),time=inp('heure','time',rec.time);box.append(el('div',{class:'exercise'},[el('b',{},s[1]),el('div',{class:'small muted'},s[2]),el('div',{class:'row'},[dose,time,el('button',{class:'btn '+(rec.taken?'green':''),onclick:()=>{data[s[0]]={taken:!rec.taken,dose:dose.value,time:time.value};Store.set('supplements_'+Store.today(),data);toast(data[s[0]].taken?'Pris':'Rouvert');rr()}},rec.taken?'Pris':'Marquer pris')])]))});return box}
function vintedDesc(){const list=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned');const n30=list.filter(x=>age(x)>=30).length,n14=list.filter(x=>age(x)>=14).length;if(n30)return n30+' articles >=30j: baisser, booster ou abandonner';if(n14)return n14+' articles >=14j: baisser prix';return 'Verifier stock, messages, prix, boosts si besoin'}function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}
function chessDesc(){const h=Store.get('chess_elo_history',[]),last=h[h.length-1];return last?'ELO '+last.elo+' · prochaine action: 1 partie analysee ou 5 puzzles':'ELO a logger + 1 partie ou 5 puzzles'}
function readingDesc(){const st=Store.get('reading_tracks',{});let active='choisir un parcours et lire 10-20 pages';Object.values(st).some(track=>Object.values(track.books||{}).some(b=>{if(!b.done&&b.current!==undefined){active=b.title+' · '+(b.current||0)+'/'+(b.total||'?')+' pages';return true}return false}));return active}
function notes(d,rr){const c=card('Notes routine','Reprise exacte et blocages.');const t=el('textarea',{class:'input',rows:'4',placeholder:'reprise, blocage, prochaine action'},d.notes||'');c.append(t);c.append(el('button',{class:'btn green',onclick:()=>{d.notes=t.value;set(d);toast('Notes sauvegardees');rr()}},'Sauver notes'));return c}
function check(v){const x=el('input',{type:'checkbox'});x.checked=!!v;return x}function inp(p,t='text',v=''){return el('input',{class:'input',placeholder:p,type:t,value:v,style:'max-width:170px'})}function sel(items,v){const s=el('select',{class:'input',style:'max-width:170px'});items.forEach(x=>s.append(el('option',{value:x},x)));s.value=v;return s}
function epfcToday(){return courseByCode(EPFC_DAILY_ROTATION[dayIndex(new Date())%EPFC_DAILY_ROTATION.length])}function dayIndex(d){const start=new Date(d.getFullYear(),0,1);return Math.floor((d-start)/86400000)}function courseByCode(code){return EPFC_YEAR1.find(c=>c.code===code)||EPFC_YEAR1[0]}
function epfcResume(code){const st=Store.get('epfc_y1_state',{})[code]||{};const r=courseByCode(code).resources[st.activeIndex||0];if(!r)return 'parcours termine';const p=st.progress?.[r[0]]||{};return r[1]+' · '+(p.current||0)+'/'+(p.total||'?')+' '+r[3]}
function trk(track){const s=Store.get('track_state',{})[track]||{};return 'Livre: '+((BOOKS[track]||[])[s.bookIndex||0]||'termine')+' · Exercice: '+((EXERCISE_PACKS[track]||[])[s.exerciseIndex||0]||'termine')}function nlResume(){const d=Store.get('nl_program',{level:'A1',target:'SELOR'});return d.level+' -> '+d.target}
function sportToday(){const c=Store.sportCycle();const diff=Math.floor((new Date(Store.today())-new Date(c.anchorDate))/86400000);const start=SPORT_CYCLE.indexOf(c.anchorType);return SPORT_CYCLE[((start<0?0:start)+diff%SPORT_CYCLE.length+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
