import { FEATURES, CERTS } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='health';
const PREFIX='ud5_';
const LEGACY_PREFIXES=['dashv2_','ultimate_','dashboard_','old_'];
const LEGACY_WORDS=['nutrition','practice','patch','legacy','old','demo'];
const GROUPS={today:['home_','today_','routine_','fuel_','supplements_'],study:['epfc_y1_state','track_state','study_materials','study_exercises','study_activity','study_mission_','nl_program','certifications','proofs','exam_targets','error_bank'],sport:['sport_cycle','sport_sessions','sport_draft_','bodyweight_progress','bodyweight_tests','flexibility_progress','sport_monthly_tests'],money:['vinted_items','finance_month','savings_history'],leisure:['chess_elo_history','chess_games','chess_goal','reading_tracks','reading_activity','leisure_books'],settings:['ui_mode','sport_mode','route','last_backup_meta','production_test_'],logs:['log_','tasks_']};
const LABELS={today:'aujourd’hui',study:'étude',sport:'sport',money:'argent',leisure:'loisir',settings:'réglages',logs:'journaux',other:'autres'};
export function renderSettings(root,refresh){root.append(subTabs([{id:'health',label:'Santé'},{id:'tests',label:'Tests'},{id:'backup',label:'Sauvegarde'},{id:'import',label:'Import'},{id:'reset',label:'Reset ciblé'},{id:'cleanup',label:'Nettoyage ancien'},{id:'diagnostic',label:'Diagnostic'}],panel,id=>{panel=id;refresh()}));if(panel==='tests')return testsPanel(root,refresh);if(panel==='backup')return backup(root);if(panel==='import')return importPanel(root,refresh);if(panel==='reset')return resetPanel(root,refresh);if(panel==='cleanup')return cleanupPanel(root,refresh);if(panel==='diagnostic')return diagnostic(root);health(root,refresh)}
function health(root,refresh){const s=systemState();const grid=el('div',{class:'grid'});grid.append(kpi('Santé système',s.score+'/100',s.status,s.score<60?'danger':s.score<85?'warn':'ok'));grid.append(kpi('Stockage',fmtBytes(s.bytes),s.keys+' clés ud5',s.bytes>3500000?'warn':'ok'));grid.append(kpi('Ancien',String(s.legacy.length),s.legacy.length?'à nettoyer':'RAS',s.legacy.length?'danger':'ok'));grid.append(kpi('Inconnu',String(s.unknown.length),s.unknown.length?'à vérifier':'RAS',s.unknown.length?'warn':'ok'));grid.append(kpi('Sauvegarde',s.backupSize?fmtBytes(s.backupSize):'0','export actuel'));grid.append(kpi('Modules actifs',s.activeModules+'/'+Object.keys(GROUPS).length,'groupes avec données',s.activeModules<4?'warn':'ok'));root.append(grid);root.append(healthActions(refresh));root.append(moduleHealth());root.append(systemReport())}
function testsPanel(root,refresh){const tests=runProductionTests();const pass=tests.filter(x=>x.ok).length;const c=card('Tests production','Passés '+pass+'/'+tests.length+' · dernière exécution '+new Date().toLocaleString('fr-BE'));c.className+=' '+(pass===tests.length?'ok':pass>=tests.length-2?'warn':'danger');c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+Math.round(pass/Math.max(1,tests.length)*100)+'%'})));tests.forEach(t=>c.append(testRow(t)));c.append(el('div',{class:'row'},[el('button',{class:'btn green',onclick:()=>{Store.set('production_test_last',{date:new Date().toISOString(),pass,total:tests.length,tests});toast('Tests production enregistrés');refresh()}},'Enregistrer résultat'),el('button',{class:'btn',onclick:()=>navigator.clipboard.writeText(JSON.stringify({date:new Date().toISOString(),pass,total:tests.length,tests},null,2)).then(()=>toast('Rapport tests copié'))},'Copier rapport')]));root.append(c);root.append(manualChecklist())}
function runProductionTests(){const s=systemState(),route=localStorage.getItem(PREFIX+'route'),mode=localStorage.getItem(PREFIX+'ui_mode'),sportMode=localStorage.getItem(PREFIX+'sport_mode'),routine=Store.get('routine_'+Store.today(),{cfg:{},done:{}}),backup=readJson(PREFIX+'last_backup_meta',{});const validRoutes=['home','routine','stats','sport','study','money','leisure','settings'];return[
 {id:'route',ok:!route||validRoutes.includes(route),label:'Route valide',detail:route||'home par défaut'},
 {id:'ui_mode',ok:!mode||['simple','expert'].includes(mode),label:'Mode UI valide',detail:mode||'simple par défaut'},
 {id:'sport_mode',ok:!sportMode||['quick','detail'].includes(sportMode),label:'Mode sport valide',detail:sportMode||'quick par défaut'},
 {id:'storage',ok:s.bytes<3500000,label:'Stockage sous seuil',detail:fmtBytes(s.bytes)+' / 3.5 MB'},
 {id:'legacy',ok:s.legacy.length===0,label:'Aucune ancienne clé critique',detail:String(s.legacy.length)},
 {id:'unknown',ok:s.unknown.length===0,label:'Aucune clé ud5 inconnue',detail:String(s.unknown.length)},
 {id:'backup',ok:!!backup.bytes,label:'Sauvegarde déjà faite',detail:backup.bytes?fmtBytes(backup.bytes):'aucune'},
 {id:'routine_flags',ok:routineTemplateClean(routine.cfg||{}),label:'Routine flags propres',detail:'template '+(routine.cfg?.template||'-')+' · exam '+!!routine.cfg?.exam+' · cash '+!!routine.cfg?.cash},
 {id:'modules_data',ok:s.activeModules>=4,label:'Modules actifs suffisants',detail:s.activeModules+'/'+Object.keys(GROUPS).length},
 {id:'features',ok:FEATURES.length>0&&CERTS.length>0,label:'Données catalogue chargées',detail:'features '+FEATURES.length+' · certs '+CERTS.length}
]}
function routineTemplateClean(cfg){if(!cfg?.template)return true;if(cfg.template!=='examen'&&cfg.exam)return false;if(cfg.template!=='cash'&&cfg.cash)return false;return true}
function testRow(t){const r=el('div',{class:'exercise '+(t.ok?'ok':'danger')});r.append(el('div',{class:'row'},[el('span',{class:'pill'},t.ok?'OK':'FAIL'),el('b',{},t.label)]));r.append(el('div',{class:'small muted'},t.detail));return r}
function manualChecklist(){const c=card('Checklist manuelle production','À faire après déploiement Netlify.');['Ouvrir le site en navigation normale','Système > Santé > Sauvegarder maintenant','Routine > passer Examen puis Travail: bloc examen doit disparaître','Routine > passer Cash puis Repos: bloc finance doit disparaître','Sport > Mode rapide > enregistrer une séance test','Étude > Mode rapide > valider 25 min','Argent > ajouter un article test puis le supprimer/abandonner','Loisir > Échecs > ajouter ELO test','Stats > vérifier score global et domaines','Système > Tests > tous les tests OK'].forEach((x,i)=>c.append(el('div',{class:'exercise'},(i+1)+'. '+x)));return c}
function healthActions(refresh){const c=card('Actions système','Opérations sûres. Pas de suppression automatique sans confirmation.');c.append(el('div',{class:'row'},[el('button',{class:'btn green',onclick:()=>{const data=Store.exportJson();localStorage.setItem(PREFIX+'last_backup_meta',JSON.stringify({date:Store.today(),bytes:data.length}));navigator.clipboard.writeText(data).then(()=>toast('Sauvegarde copiée + meta enregistrée'))}},'Sauvegarder maintenant'),el('button',{class:'btn',onclick:()=>hardRefresh(refresh)},'Vider caches + SW')]));return c}
function moduleHealth(){const c=card('Santé par module','Présence des données par groupe.');const keys=localKeys().map(k=>k.replace(PREFIX,''));Object.entries(GROUPS).forEach(([g,prefixes])=>{const count=keys.filter(k=>matchAny(k,prefixes)).length;const cls=count?'ok':'warn';c.append(el('div',{class:'exercise '+cls},(LABELS[g]||g)+' · '+count+' clés'))});return c}
function systemReport(){const s=systemState();const c=card('Rapport système','Résumé copiable pour audit.');const txt=el('textarea',{class:'input',rows:'8'},JSON.stringify({date:Store.today(),score:s.score,keys:s.keys,bytes:s.bytes,legacy:s.legacy,unknown:s.unknown,counts:s.counts},null,2));c.append(txt);c.append(el('button',{class:'btn green',onclick:()=>navigator.clipboard.writeText(txt.value).then(()=>toast('Rapport copié'))},'Copier rapport'));return c}
function backup(root){let data='';try{data=Store.exportJson()}catch(e){data=JSON.stringify({error:'export_failed',message:String(e)},null,2)}const c=card('Sauvegarde complète','Copie tout le stockage du dashboard avant modification.');const t=el('textarea',{class:'input',rows:'14'},data);c.append(t);c.append(el('div',{class:'row'},[el('button',{class:'btn green',onclick:()=>{localStorage.setItem(PREFIX+'last_backup_meta',JSON.stringify({date:Store.today(),bytes:data.length}));navigator.clipboard.writeText(data).then(()=>toast('Sauvegarde copiée'))}},'Copier sauvegarde'),el('button',{class:'btn',onclick:()=>download(data)},'Télécharger JSON')]));root.append(c)}
function importPanel(root,refresh){const c=card('Importer une sauvegarde','Colle un export JSON. Seules les clés ud5_ sont importées.');const t=el('textarea',{class:'input',rows:'14',placeholder:'Coller sauvegarde JSON ici'});c.append(t);c.append(el('button',{class:'btn green',onclick:()=>{try{const obj=JSON.parse(t.value);let n=0;Object.entries(obj).forEach(([k,v])=>{if(k.startsWith(PREFIX)){localStorage.setItem(k,JSON.stringify(v));n++}});toast('Import réussi: '+n+' clés');refresh()}catch(e){toast('JSON invalide')}}},'Importer'));root.append(c)}
function resetPanel(root,refresh){const c=card('Reset ciblé','Efface seulement la zone choisie. Pas de reset total accidentel.');Object.keys(GROUPS).forEach(g=>c.append(el('button',{class:'btn danger',onclick:()=>{resetGroup(g);toast('Reset '+(LABELS[g]||g)+' terminé');refresh()}},'Reset '+(LABELS[g]||g))));c.append(el('div',{class:'exercise'},'Reset total volontaire: écrire RESET puis cliquer.'));const confirm=el('input',{class:'input',placeholder:'RESET'});c.append(confirm);c.append(el('button',{class:'btn danger',onclick:()=>{if(confirm.value==='RESET'){resetAll();toast('Reset total terminé');refresh()}else toast('Écris RESET exactement')}},'Reset total'));root.append(c)}
function cleanupPanel(root,refresh){const legacy=legacyKeys(),unknown=unknownUd5Keys();const c=card('Nettoyage ancien sécurisé','Anciennes clés supprimables. Clés ud5 inconnues: affichage seulement.');c.append(el('div',{class:'exercise '+(legacy.length?'danger':'ok')},'Anciennes clés détectées: '+legacy.length));c.append(el('div',{class:'exercise '+(unknown.length?'warn':'ok')},'Clés ud5 inconnues: '+unknown.length+' · suppression désactivée par sécurité'));const confirm=el('input',{class:'input',placeholder:'DELETE LEGACY'});c.append(confirm);c.append(el('div',{class:'row'},[el('button',{class:'btn danger',onclick:()=>{if(confirm.value!=='DELETE LEGACY')return toast('Écris DELETE LEGACY');legacy.forEach(k=>localStorage.removeItem(k));toast('Anciennes clés supprimées: '+legacy.length);refresh()}},'Supprimer anciennes clés'),el('button',{class:'btn green',onclick:()=>hardRefresh(refresh)},'Vider caches + SW')]));root.append(c);const l=card('Anciennes clés','Liste hors ud5_ seulement.');legacy.forEach(k=>l.append(el('div',{class:'small muted'},k)));root.append(l);const u=card('Clés ud5 inconnues','Non supprimées automatiquement.');unknown.forEach(k=>u.append(el('div',{class:'small muted'},k)));root.append(u)}
function diagnostic(root){const s=systemState();const c=card('Diagnostic stockage','Clés locales ud5: '+s.keys+' · taille '+fmtBytes(s.bytes)+' · préfixe '+PREFIX);Object.entries(s.counts).forEach(([k,v])=>c.append(el('div',{class:'exercise'},(LABELS[k]||k)+' · '+v+' clés')));c.append(el('div',{class:'exercise'},'Registre fonctionnalités: '+FEATURES.length+' · Certifs: '+CERTS.length));c.append(el('div',{class:'exercise'},'Anciennes clés hors ud5: '+s.legacy.length));root.append(c);const list=card('Clés détectées','Contrôle brut.');[...localKeys(),...legacyKeys()].sort().forEach(k=>list.append(el('div',{class:'small muted'},k)));root.append(list)}
function systemState(){const keys=localKeys(),legacy=legacyKeys(),unknown=unknownUd5Keys(),counts={today:0,study:0,sport:0,money:0,leisure:0,settings:0,logs:0,other:0};let bytes=0;keys.forEach(k=>{const short=k.replace(PREFIX,'');const g=Object.keys(GROUPS).find(x=>matchAny(short,GROUPS[x]));counts[g||'other']++;bytes+=String(localStorage.getItem(k)||'').length+k.length});const activeModules=Object.values(counts).filter(v=>v>0).length;const backupMeta=readJson(PREFIX+'last_backup_meta',{});let score=100;if(legacy.length)score-=25;if(unknown.length)score-=10;if(bytes>3500000)score-=15;if(counts.today===0)score-=10;if(counts.study===0)score-=10;if(counts.sport===0)score-=5;if(counts.money===0)score-=5;if(!backupMeta.bytes)score-=10;score=Math.max(0,score);return{score,status:score>=85?'OK':score>=60?'À surveiller':'Action requise',keys:keys.length,bytes,legacy,unknown,counts,activeModules,backupSize:backupMeta.bytes||0}}
function kpi(t,v,s,cls=''){const c=card(t,s,'span-4 '+cls);c.append(el('div',{class:'metric'},v));return c}
function allKeys(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k)out.push(k)}return out}
function localKeys(){return allKeys().filter(k=>k.startsWith(PREFIX))}
function legacyKeys(){return allKeys().filter(k=>!k.startsWith(PREFIX)&&(LEGACY_PREFIXES.some(p=>k.startsWith(p))||LEGACY_WORDS.some(w=>k.toLowerCase().includes(w))))}
function unknownUd5Keys(){return localKeys().filter(k=>{const short=k.replace(PREFIX,'');return !Object.keys(GROUPS).some(g=>matchAny(short,GROUPS[g]))})}
function matchAny(k,arr){return arr.some(p=>k===p||k.startsWith(p))}
function resetGroup(g){localKeys().forEach(k=>{const short=k.replace(PREFIX,'');if(matchAny(short,GROUPS[g]))localStorage.removeItem(k)})}
function resetAll(){localKeys().forEach(k=>localStorage.removeItem(k))}
async function hardRefresh(refresh){let n=0;if('caches'in window){const names=await caches.keys();for(const name of names){await caches.delete(name);n++}}if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){await r.unregister();n++}}toast('Caches/SW nettoyés: '+n);refresh()}
function readJson(k,fallback){try{return JSON.parse(localStorage.getItem(k)||'')||fallback}catch(e){return fallback}}
function fmtBytes(n){n=+n||0;if(n<1024)return n+' B';if(n<1024*1024)return Math.round(n/1024)+' KB';return(Math.round(n/1024/1024*10)/10)+' MB'}
function download(data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='ultimate-dashboard-backup-'+Store.today()+'.json';a.click();URL.revokeObjectURL(a.href)}
