import { FEATURES, CERTS } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='health';
const PREFIX='ud5_';
const GROUPS={today:['home_','today_','routine_','fuel_','supplements_','action_state_','day_mode_'],study:['epfc_y1_state','track_state','study_','nl_program','certifications','proofs','exam_targets','error_bank'],sport:['sport_','bodyweight_','flexibility_'],money:['vinted_items','finance_month','savings_history'],leisure:['chess_','reading_','leisure_'],settings:['ui_mode','sport_mode','route','__meta','last_backup_meta','backup_'],logs:['log_','tasks_','action_events']};
export function renderSettings(root,refresh){root.append(subTabs([{id:'health',label:'Santé système'},{id:'backup',label:'Sauvegarde'},{id:'security',label:'Sécurité'},{id:'reset',label:'Reset'},{id:'diagnostic',label:'Diagnostic'}],panel,id=>{panel=id;refresh()}));({health,backup,security,reset,diagnostic}[panel]||health)(root,refresh)}
function health(root,refresh){const s=state();const grid=el('div',{class:'grid'});grid.append(kpi('Santé système',s.score+'/100',s.status,s.score<60?'danger':s.score<85?'warn':'ok'),kpi('Version',window.UD5_VERSION||Store.APP_VERSION||'-','schema '+(s.meta.schemaVersion||'-')),kpi('Stockage',fmt(s.bytes),s.keys+' clés',s.bytes>3500000?'warn':'ok'),kpi('Invalid JSON',String(s.invalid.length),s.invalid.length?'à réparer':'RAS',s.invalid.length?'danger':'ok'),kpi('Backups',String(s.backups),'exports locaux'),kpi('Features',FEATURES.length+' / '+CERTS.length,'catalogues'));root.append(grid);const c=card('Actions sûres','Backup avant opération. Pas de suppression invisible.');c.append(el('div',{class:'row'},[btn('Backup maintenant',()=>{const key=Store.backup('manual');toast('Backup créé: '+key)},'green'),btn('Copier export',()=>navigator.clipboard.writeText(Store.exportJson()).then(()=>toast('Export copié'))),btn('Hard refresh',()=>hardRefresh(refresh))]));root.append(c);root.append(moduleHealth())}
function backup(root){const data=Store.exportJson(),c=card('Sauvegarde complète','Copie ou télécharge avant modification.');const t=el('textarea',{class:'input',rows:'14'},data);c.append(t);c.append(el('div',{class:'row'},[btn('Copier',()=>navigator.clipboard.writeText(t.value).then(()=>toast('Sauvegarde copiée')),'green'),btn('Télécharger JSON',()=>download(t.value))]));root.append(c);const i=card('Importer','Colle un export ud5_.');const area=el('textarea',{class:'input',rows:'10',placeholder:'JSON'});i.append(area,btn('Importer',()=>{try{const n=Store.importJson(area.value);toast('Import: '+n+' clés')}catch(error){toast('JSON invalide')}} ,'green'));root.append(i)}
function security(root){const c=card('Sécurité données','LocalStorage = stockage local navigateur. Ne mets pas de clé API ni données sensibles non chiffrées.','danger');c.append(el('div',{class:'exercise'},'Règles: backup régulier · pas de secret client · purge urgence disponible · CSP dans netlify.toml.'));c.append(el('div',{class:'row'},[btn('Purge urgence',()=>{const ok=prompt('Écrire PURGE pour tout effacer');if(ok==='PURGE'){Store.backup('pre_purge');Store.purgeAll();toast('Purge effectuée')}else toast('Annulé')},'danger'),btn('Rapport stockage',()=>navigator.clipboard.writeText(JSON.stringify(state(),null,2)).then(()=>toast('Rapport copié')))]));root.append(c)}
function reset(root,refresh){const c=card('Reset ciblé','Efface uniquement le groupe choisi.');Object.keys(GROUPS).forEach(group=>c.append(btn('Reset '+group,()=>{Store.backup('pre_reset_'+group);localKeys().forEach(key=>{const clean=key.replace(PREFIX,'');if(GROUPS[group].some(prefix=>clean===prefix||clean.startsWith(prefix)))localStorage.removeItem(key)});toast('Reset '+group);refresh()},'danger')));root.append(c)}
function diagnostic(root){const s=state();const c=card('Diagnostic brut','Version, clés, taille, groupes.');c.append(el('textarea',{class:'input',rows:'14'},JSON.stringify(s,null,2)));root.append(c)}
function moduleHealth(){const c=card('Modules actifs','Présence données par groupe.');const cleanKeys=localKeys().map(key=>key.replace(PREFIX,''));Object.entries(GROUPS).forEach(([group,prefixes])=>{const n=cleanKeys.filter(key=>prefixes.some(prefix=>key===prefix||key.startsWith(prefix))).length;c.append(el('div',{class:'exercise '+(n?'ok':'warn')},group+' · '+n+' clés'))});return c}
function state(){const rep=Store.storageReport(),counts={};localKeys().forEach(key=>{const clean=key.replace(PREFIX,''),group=Object.keys(GROUPS).find(name=>GROUPS[name].some(prefix=>clean===prefix||clean.startsWith(prefix)))||'other';counts[group]=(counts[group]||0)+1});let score=100;if(rep.invalid.length)score-=30;if(rep.bytes>3500000)score-=15;if(!rep.meta?.schemaVersion)score-=20;if(!rep.backups)score-=10;score=Math.max(0,score);return{score,status:score>=85?'OK':score>=60?'À surveiller':'Action requise',...rep,counts}}
function localKeys(){const out=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith(PREFIX))out.push(key)}return out}
async function hardRefresh(refresh){let n=0;if('caches'in window){for(const name of await caches.keys()){await caches.delete(name);n++}}if('serviceWorker'in navigator){for(const registration of await navigator.serviceWorker.getRegistrations()){await registration.unregister();n++}}toast('Caches/SW nettoyés: '+n);refresh()}
function download(data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='ultimate-dashboard-backup-'+Store.today()+'.json';a.click();URL.revokeObjectURL(a.href)}
function kpi(title,value,sub,cls=''){const c=card(title,sub,'span-4 '+cls);c.append(el('div',{class:'metric'},value));return c}
function btn(label,onClick,cls=''){return el('button',{class:'btn '+cls,onclick:onClick},label)}
function fmt(value){const n=+value||0;if(n<1024)return n+' B';if(n<1048576)return Math.round(n/1024)+' KB';return(n/1048576).toFixed(2)+' MB'}
