import { SPORT_LIBRARY, SPORT_PROGRAM, SPORT_CYCLE, FLEX_LEVELS } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='today',cat='all';
function cycleType(){const c=Store.sportCycle();const d=Math.floor((new Date(Store.today())-new Date(c.anchorDate))/86400000);const s=SPORT_CYCLE.indexOf(c.anchorType);return SPORT_CYCLE[((s<0?0:s)+d%SPORT_CYCLE.length+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
function byId(id){return SPORT_LIBRARY.find(e=>e.id===id)}
function sessions(){return Store.sportSessions()}
function hist(id){return sessions().filter(s=>s.exercises&&s.exercises[id]).map(s=>({date:s.date,type:s.sessionType,...s.exercises[id]}))}
function best(id){const h=hist(id);let top={score:0,text:'aucun log'};h.forEach(x=>{const kg=+x.kg||0,reps=+x.reps||0,sets=+x.sets||0,sec=+x.sec||0;const score=kg*reps*sets+sec;if(score>top.score)top={score,text:(kg?kg+'kg ':'')+(sets?sets+'x':'')+(reps?reps+' reps ':'')+(sec?sec+' sec':'')+' · '+x.date}});return top.text}
export function renderSport(root,rr){root.append(el('div',{class:'row'},[el('span',{class:'pill'},'Cycle: '+cycleType()),btn('Reset Push1',()=>{Store.setSportCycle({anchorDate:Store.today(),anchorType:'push1'});rr()}),btn('Reset Pull1',()=>{Store.setSportCycle({anchorDate:Store.today(),anchorType:'pull1'});rr()}),btn('Reset Legs1',()=>{Store.setSportCycle({anchorDate:Store.today(),anchorType:'legs1'});rr()})]));root.append(subTabs([{id:'today',label:'Séance'},{id:'records',label:'Records'},{id:'library',label:'Bibliothèque'},{id:'bodyweight',label:'Poids du corps'},{id:'flex',label:'Souplesse'},{id:'history',label:'Historique'},{id:'tests',label:'Tests'}],panel,id=>{panel=id;rr()}));const box=el('div');root.append(box);({today,records,library,bodyweight,flex,history,tests}[panel]||today)(box,rr)}
function today(root,rr){const type=cycleType(),draft=Store.sportDraft();const ids=SPORT_PROGRAM[type]||[];const c=card('Séance du jour · '+type,'Log: sets, reps, kg, secondes, RPE, douleur. Douleur ≥7 = pain_stop.');ids.forEach(id=>c.append(exercise(byId(id),draft,true)));const notes=el('textarea',{class:'input',rows:'3',placeholder:'Notes séance / douleur / énergie',value:draft.notes||''});notes.addEventListener('change',()=>Store.setSportDraft(Store.today(),{notes:notes.value}));c.append(notes);c.append(el('div',{class:'row'},[btn('Sauver terminée',()=>saveSession('completed',rr),'green'),btn('Sautée',()=>saveSession('skipped',rr)),btn('Deload',()=>saveSession('deload',rr))]));root.append(summaryCard());root.append(c)}
function exercise(ex,draft,log=false){if(!ex)return el('div',{class:'exercise danger'},'Exercice manquant');const saved=draft.exercises?.[ex.id]||{};const d=el('div',{class:'exercise '+(ex.c7Risk==='medium'?'warn':'')});d.append(el('div',{class:'exercise-title'},ex.name));d.append(el('div',{class:'exercise-meta'},[pill(ex.category),pill(ex.equipment),pill('C7 '+ex.c7Risk),pill(ex.difficulty)]));d.append(el('div',{class:'small muted'},'Record: '+best(ex.id)));d.append(el('div',{class:'small muted'},'Règle: '+ex.progressionRule));if(log){const row=el('div',{class:'row'});['sets','reps','kg','sec','rpe','pain'].forEach(p=>{const input=el('input',{class:'input',placeholder:p,type:'number',style:'max-width:92px',value:saved[p]||''});input.addEventListener('change',()=>{const cur=Store.sportDraft();cur.exercises=cur.exercises||{};cur.exercises[ex.id]={...(cur.exercises[ex.id]||{}),[p]:input.value};Store.setSportDraft(Store.today(),cur)});row.append(input)});d.append(row)}return d}
function saveSession(status,rr){const draft=Store.sportDraft();const vals=Object.values(draft.exercises||{});const maxPain=Math.max(0,...vals.map(x=>Number(x.pain||0)));const final=maxPain>=7?'pain_stop':status;Store.addSportSession({date:Store.today(),sessionType:cycleType(),status:final,exercises:draft.exercises||{},notes:draft.notes||'',globalPainLevel:maxPain});Store.setSportDraft(Store.today(),{});toast(final==='pain_stop'?'Pain stop enregistré':'Séance sauvegardée');rr()}
function summaryCard(){const all=sessions(),last=all[all.length-1];return card('Résumé sport','Séances: '+all.length+' · dernière: '+(last?last.date+' '+last.sessionType+' '+last.status:'aucune'))}
function records(root){const c=card('Records par exercice','Basé sur tes logs sauvegardés.');SPORT_LIBRARY.filter(e=>hist(e.id).length).forEach(e=>c.append(el('div',{class:'exercise'},e.name+' · '+best(e.id)+' · logs '+hist(e.id).length)));root.append(c)}
function library(root,rr){const cats=['all','push','pull','legs','core','bodyweight','mobility','warmup'];root.append(subTabs(cats.map(x=>({id:x,label:x})),cat,id=>{cat=id;rr()}));const list=SPORT_LIBRARY.filter(e=>cat==='all'||e.category===cat);root.append(card('Bibliothèque','Total '+SPORT_LIBRARY.length+' · catégorie '+cat));list.forEach(e=>root.append(exercise(e,{},false)))}
function bodyweight(root){const data=Store.bodyweight();const c=card('Poids du corps','Niveaux 0-5 + meilleur score + date test.');['pushups','pullups','dips','legs','core','mobility'].forEach(f=>{const row=el('div',{class:'exercise'});row.append(el('b',{},f));const lvl=input('niveau 0-5',data[f]?.level||''),bestv=input('meilleur score',data[f]?.best||'');row.append(el('div',{class:'row'},[lvl,bestv,btn('Sauver',()=>{data[f]={level:+lvl.value||0,best:+bestv.value||0,lastTestDate:Store.today()};Store.setBodyweight(data);Store.addBodyweightTest({date:Store.today(),family:f,level:data[f].level,best:data[f].best});toast('Test sauvé')},'green')]));c.append(row)});root.append(c)}
function flex(root){const c=card('Souplesse','Niveaux + mesures.');FLEX_LEVELS.forEach(l=>c.append(el('div',{class:'exercise'},'Niveau '+l.level+' · '+l.label+' · '+l.routineMin+' min · '+l.milestones.join(' / '))));const fields=['forwardFoldCm','pikeCm','straddleDeg','frontSplitRightCm','frontSplitLeftCm','middleSplitCm','deepSquatSec','bridgeScore'],inputs={};fields.forEach(f=>{inputs[f]=input(f,'');c.append(inputs[f])});c.append(btn('Sauver mesures',()=>{const m={date:Store.today()};fields.forEach(f=>m[f]=inputs[f].value?+inputs[f].value:null);Store.addFlexMeasurement(m);toast('Mesures sauvées')},'green'));root.append(c)}
function history(root){const c=card('Historique','Dernières séances.');sessions().slice(-40).reverse().forEach(s=>c.append(el('div',{class:'exercise '+(s.status==='pain_stop'?'danger':'')},s.date+' · '+s.sessionType+' · '+s.status+' · douleur '+(s.globalPainLevel??0)+' · exos '+Object.keys(s.exercises||{}).length)));root.append(c)}
function tests(root){const c=card('Tests mensuels','Pompes, plank, dead hang, squat, poids.');const fields=['pushupsMax','plankSec','deadHangSec','deepSquatSec','bodyweightKg'],inputs={};fields.forEach(f=>{inputs[f]=input(f,'');c.append(inputs[f])});c.append(btn('Sauver test',()=>{const t={date:Store.today()};fields.forEach(f=>t[f]=inputs[f].value?+inputs[f].value:null);Store.addSportMonthlyTest(t);toast('Test mensuel sauvé')},'green'));Store.sportMonthlyTests().slice(-6).reverse().forEach(t=>c.append(el('div',{class:'exercise'},t.date+' · pompes '+(t.pushupsMax??'-')+' · plank '+(t.plankSec??'-')+'s · poids '+(t.bodyweightKg??'-'))));root.append(c)}
function pill(x){return el('span',{class:'pill'},x)}function btn(label,fn,cls=''){return el('button',{class:'btn '+cls,onclick:fn},label)}function input(p,v){return el('input',{class:'input',placeholder:p,type:'number',value:v,style:'max-width:140px'})}
