import { SPORT_LIBRARY, SPORT_PROGRAM, SPORT_CYCLE, FLEX_LEVELS } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='today',cat='all';
function cycleType(){const c=Store.sportCycle();const d=Math.floor((new Date(Store.today())-new Date(c.anchorDate))/86400000);const s=SPORT_CYCLE.indexOf(c.anchorType);return SPORT_CYCLE[((s<0?0:s)+d%SPORT_CYCLE.length+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
function byId(id){return SPORT_LIBRARY.find(e=>e.id===id)}function sessions(){return Store.sportSessions()}function normalizeExerciseLog(x){if(!x)return[];if(Array.isArray(x.performedSets))return x.performedSets;return Array.from({length:+x.sets||1},()=>({reps:x.reps||'',kg:x.kg||'',sec:x.sec||'',rpe:x.rpe||'',pain:x.pain||0}))}
function hist(id){return sessions().filter(s=>s.exercises&&s.exercises[id]).flatMap(s=>normalizeExerciseLog(s.exercises[id]).map((set,i)=>({date:s.date,type:s.sessionType,set:i+1,...set})))}
function lastExercise(id){const all=sessions().filter(s=>s.exercises&&s.exercises[id]).slice(-1)[0];return all?{session:all,sets:normalizeExerciseLog(all.exercises[id])}:null}
function best(id){const h=hist(id);let top={score:0,text:'aucun log'};h.forEach(x=>{const kg=+x.kg||0,reps=+x.reps||0,sec=+x.sec||0,score=kg*reps+reps+sec;if(score>top.score)top={score,text:'S'+x.set+' · '+(kg?kg+'kg · ':'')+(reps?reps+' reps · ':'')+(sec?sec+' sec · ':'')+x.date}});return top.text}
function rx(ex,i,type){if(type==='rest'||ex.category==='warmup')return{sets:2,repsTarget:'12',repsDefault:12,secDefault:30,rpe:5,pain:0,label:'RECOVERY',visible:'2 tours · 12 reps · 30 sec · RPE 5'};if(ex.category==='mobility')return{sets:2,repsTarget:'',repsDefault:'',secDefault:45,rpe:4,pain:0,label:'MOBILITY',visible:'2 séries · 45 sec · RPE 4'};if(ex.category==='core')return{sets:3,repsTarget:'10',repsDefault:10,secDefault:30,rpe:7,pain:0,label:'CORE',visible:'3 séries · 10 reps ou 30 sec · RPE 7'};if(i<2)return{sets:4,repsTarget:'6-10',repsDefault:8,secDefault:'',rpe:8,pain:0,label:'MAIN',visible:'4 séries · 6-10 reps · RPE 8'};if(i<6)return{sets:3,repsTarget:'8-12',repsDefault:10,secDefault:'',rpe:8,pain:0,label:'ACCESSORY',visible:'3 séries · 8-12 reps · RPE 8'};return{sets:3,repsTarget:'12-15',repsDefault:12,secDefault:'',rpe:7,pain:0,label:'FINISH',visible:'3 séries · 12-15 reps · RPE 7'}}
function defaultSets(r){return Array.from({length:r.sets},()=>({reps:r.repsDefault||'',kg:'',sec:r.secDefault||'',rpe:r.rpe||'',pain:0}))}function prescription(r){return{sets:r.sets,repsTarget:r.repsTarget,secTarget:r.secDefault,rpe:r.rpe,label:r.label,visible:r.visible}}
function targetMax(r){const m=String(r.repsTarget||'').match(/-(\d+)/);return m?+m[1]:(+r.repsTarget||+r.repsDefault||0)}function targetMin(r){const m=String(r.repsTarget||'').match(/(\d+)/);return m?+m[1]:(+r.repsDefault||0)}
function progressionAdvice(exId,r){const last=lastExercise(exId);if(!last)return'Première séance propre. Respecte la prescription.';const sets=last.sets||[],pain=Math.max(0,...sets.map(s=>+s.pain||0)),rpe=Math.max(0,...sets.map(s=>+s.rpe||0));if(pain>=7)return'DELOAD: douleur ≥7. Stop / alternative.';if(pain>=4)return'Maintien prudent. Même charge, technique stricte.';const reps=sets.map(s=>+s.reps||0).filter(Boolean),kg=sets.map(s=>+s.kg||0).filter(Boolean),sec=sets.map(s=>+s.sec||0).filter(Boolean);const max=targetMax(r),min=targetMin(r);if(sec.length&&!reps.length)return sec.every(x=>x>=+r.secDefault)?'+5 sec ou variante plus dure.':'Atteindre '+(r.secDefault||30)+' sec sur toutes les séries.';if(!reps.length)return'Remplir les reps réelles pour calcul automatique.';const allTop=max&&reps.length>=r.sets&&reps.every(x=>x>=max),allMin=min&&reps.length>=r.sets&&reps.every(x=>x>=min),load=kg.length?Math.max(...kg):0;if(allTop&&load)return'+2,5 kg ou +5% charge.';if(allTop)return'Variante plus dure ou +1 série contrôlée.';if(allMin){const idx=reps.findIndex(x=>x<max);return'Série '+(idx>=0?idx+1:reps.length)+' → '+Math.min(max,(reps[idx]||min)+1)+' reps.'}if(rpe>=9)return'Maintien: RPE trop haut.';return'Atteindre minimum '+min+' reps partout.'}
export function renderSport(root,rr){root.append(cycleControl(rr));root.append(subTabs([{id:'today',label:'Séance'},{id:'progression',label:'Progression'},{id:'records',label:'Records'},{id:'library',label:'Bibliothèque'},{id:'bodyweight',label:'Poids du corps'},{id:'flex',label:'Souplesse'},{id:'history',label:'Historique'},{id:'tests',label:'Tests'}],panel,id=>{panel=id;rr()}));const box=el('div');root.append(box);({today,progression,records,library,bodyweight,flex,history,tests}[panel]||today)(box,rr)}
function cycleControl(rr){const start=el('select',{class:'input',style:'max-width:190px'});SPORT_CYCLE.forEach(x=>start.append(el('option',{value:x},x)));start.value=cycleType();return el('div',{class:'row'},[el('span',{class:'pill'},'CYCLE · '+cycleType()),start,btn('RESET CYCLE',()=>{Store.setSportCycle({anchorDate:Store.today(),anchorType:start.value});toast('Cycle redémarré: '+start.value);rr()},'green')])}
function today(root,rr){const type=cycleType(),draft=Store.sportDraft(),ids=SPORT_PROGRAM[type]||[],all=sessions(),last=all[all.length-1];root.append(sessionHero(type,ids,last));const grid=el('div',{class:'grid'});const main=card('Workout protocol','Séries en lignes compactes. Zéro chevauchement.','span-8');ids.forEach((id,i)=>main.append(exercise(byId(id),draft,true,i,type)));const side=card('Session control','Enregistrement séance.','span-4');const notes=el('textarea',{class:'input',rows:'5',placeholder:'Notes séance / douleur / énergie',value:draft.notes||''});notes.addEventListener('change',()=>Store.setSportDraft(Store.today(),{notes:notes.value}));side.append(el('div',{class:'exercise'},'Dernière: '+(last?last.date+' · '+last.sessionType+' · '+last.status:'aucune')));side.append(el('div',{class:'exercise'},'Exercices: '+ids.length+' · séries prévues: '+plannedSets(ids,type)));side.append(notes);side.append(el('div',{class:'row'},[btn('Terminée',()=>saveSession('completed',rr),'green'),btn('Sautée',()=>saveSession('skipped',rr)),btn('Deload',()=>saveSession('deload',rr),'warn')]));grid.append(main,side);root.append(grid)}
function sessionHero(type,ids,last){const c=card('Sport · '+type,'Progression pilotée par séries réelles.');c.className+=' module-hero';c.append(el('div',{class:'grid'},[mini('Exercices',String(ids.length),'programme'),mini('Séries',String(plannedSets(ids,type)),'prévu'),mini('Dernière',last?last.status:'aucune',last?last.date:'historique vide')]));return c}
function mini(t,v,s){const c=card(t,s,'span-4 compact-card');c.append(el('div',{class:'metric'},v));return c}
function plannedSets(ids,type){return ids.reduce((a,id,i)=>{const ex=byId(id);return a+(ex?rx(ex,i,type).sets:0)},0)}
function exercise(ex,draft,log=false,index=0,type=cycleType()){if(!ex)return el('div',{class:'exercise danger'},'Exercice manquant');const r=rx(ex,index,type),saved=draft.exercises?.[ex.id]||{},sets=saved.performedSets||defaultSets(r),advice=progressionAdvice(ex.id,r),risk=ex.c7Risk==='medium'?'warn':'';const d=el('div',{class:'exercise '+risk});d.append(el('div',{class:'row'},[el('span',{class:'pill'},String(index+1).padStart(2,'0')),el('span',{class:'pill'},r.label),el('span',{class:'pill'},ex.category),el('b',{},ex.name)]));d.append(el('div',{class:'small'},r.visible+' · Record: '+best(ex.id)));d.append(el('div',{class:'exercise-title'},advice));if(log){d.append(setList(ex.id,sets,r));d.append(el('div',{class:'row'},[btn('Reset séries',()=>{const cur=Store.sportDraft();cur.exercises=cur.exercises||{};cur.exercises[ex.id]={prescription:prescription(r),performedSets:defaultSets(r)};Store.setSportDraft(Store.today(),cur);toast('Séries réinitialisées')})]))}else{d.append(el('div',{class:'small'},'Règle: '+ex.progressionRule))}return d}
function setList(exId,sets,r){const wrap=el('div',{class:'set-list'});sets.forEach((s,i)=>wrap.append(setRow(exId,i,s,r)));return wrap}
function setRow(exId,i,setData,r){const row=el('div',{class:'set-row'});row.append(el('div',{class:'set-index'},'S'+(i+1)+'/'+r.sets));[['reps','Reps'],['kg','Kg'],['sec','Sec'],['rpe','RPE'],['pain','Pain']].forEach(([k,label])=>row.append(miniField(label,setData[k]??'',v=>saveSet(exId,i,k,v,r))));return row}
function miniField(label,v,fn){const w=el('label',{class:'field-mini'});w.append(el('span',{},label));const n=el('input',{placeholder:label,type:'number',value:v});n.addEventListener('change',()=>fn(n.value));w.append(n);return w}
function saveSet(exId,i,k,v,r){const cur=Store.sportDraft();cur.exercises=cur.exercises||{};cur.exercises[exId]=cur.exercises[exId]||{prescription:prescription(r),performedSets:defaultSets(r)};cur.exercises[exId].performedSets=cur.exercises[exId].performedSets||defaultSets(r);cur.exercises[exId].performedSets[i]=cur.exercises[exId].performedSets[i]||{};cur.exercises[exId].performedSets[i][k]=v;Store.setSportDraft(Store.today(),cur)}
function saveSession(status,rr){const draft=Store.sportDraft(),type=cycleType(),ids=SPORT_PROGRAM[type]||[],exercises={};ids.forEach((id,i)=>{const ex=byId(id);if(!ex)return;const r=rx(ex,i,type),saved=draft.exercises?.[id]||{};exercises[id]={prescription:prescription(r),performedSets:saved.performedSets||defaultSets(r),nextAdvice:progressionAdvice(id,r)}});const allSets=Object.values(exercises).flatMap(x=>x.performedSets||[]),maxPain=Math.max(0,...allSets.map(x=>Number(x.pain||0))),final=maxPain>=7?'pain_stop':status;Store.addSportSession({date:Store.today(),sessionType:type,status:final,exercises,notes:draft.notes||'',globalPainLevel:maxPain});Store.setSportDraft(Store.today(),{});toast(final==='pain_stop'?'Pain stop enregistré':'Séance sauvegardée');rr()}
function progression(root){const list=SPORT_LIBRARY.filter(e=>hist(e.id).length);const c=card('Progression automatique',list.length+' exercices avec historique.');list.forEach(e=>{const i=Math.max(0,(SPORT_PROGRAM[cycleType()]||[]).indexOf(e.id)),r=rx(e,i,cycleType());c.append(el('div',{class:'exercise'},[el('div',{class:'row'},[el('span',{class:'pill'},e.category),el('b',{},e.name)]),el('div',{class:'small'},best(e.id)),el('div',{class:'exercise-title'},progressionAdvice(e.id,r))]))});root.append(c)}
function records(root){const c=card('Records par exercice','Basé sur les séries réellement loggées.');SPORT_LIBRARY.filter(e=>hist(e.id).length).forEach(e=>c.append(el('div',{class:'exercise'},[el('b',{},e.name),el('div',{class:'small'},best(e.id)+' · séries loggées '+hist(e.id).length)])));root.append(c)}
function library(root,rr){const cats=['all','push','pull','legs','core','bodyweight','mobility','warmup'];root.append(subTabs(cats.map(x=>({id:x,label:x})),cat,id=>{cat=id;rr()}));const list=SPORT_LIBRARY.filter(e=>cat==='all'||e.category===cat);const c=card('Bibliothèque','Total '+SPORT_LIBRARY.length+' · catégorie '+cat);list.forEach((e,i)=>c.append(exercise(e,{},false,i,cycleType())));root.append(c)}
function bodyweight(root){const data=Store.bodyweight();const c=card('Poids du corps','Niveaux 0-5 + meilleur score + date test.');['pushups','pullups','dips','legs','core','mobility'].forEach(f=>{const row=el('div',{class:'exercise'});row.append(el('b',{},f));const lvl=input('niveau 0-5',data[f]?.level||''),bestv=input('meilleur score',data[f]?.best||'');row.append(el('div',{class:'row'},[lvl,bestv,btn('Sauver',()=>{data[f]={level:+lvl.value||0,best:+bestv.value||0,lastTestDate:Store.today()};Store.setBodyweight(data);Store.addBodyweightTest({date:Store.today(),family:f,level:data[f].level,best:data[f].best});toast('Test sauvé')},'green')]));c.append(row)});root.append(c)}
function flex(root){const c=card('Souplesse','Niveaux + mesures.');FLEX_LEVELS.forEach(l=>c.append(el('div',{class:'exercise'},'Niveau '+l.level+' · '+l.label+' · '+l.routineMin+' min · '+l.milestones.join(' / '))));const fields=['forwardFoldCm','pikeCm','straddleDeg','frontSplitRightCm','frontSplitLeftCm','middleSplitCm','deepSquatSec','bridgeScore'],inputs={};fields.forEach(f=>{inputs[f]=input(f,'');c.append(inputs[f])});c.append(btn('Sauver mesures',()=>{const m={date:Store.today()};fields.forEach(f=>m[f]=inputs[f].value?+inputs[f].value:null);Store.addFlexMeasurement(m);toast('Mesures sauvées')},'green'));root.append(c)}
function history(root){const c=card('Historique','Dernières séances.');sessions().slice(-40).reverse().forEach(s=>{const setCount=Object.values(s.exercises||{}).flatMap(x=>normalizeExerciseLog(x)).length;c.append(el('div',{class:'exercise '+(s.status==='pain_stop'?'danger':'')},s.date+' · '+s.sessionType+' · '+s.status+' · douleur '+(s.globalPainLevel??0)+' · séries '+setCount))});root.append(c)}
function tests(root){const c=card('Tests mensuels','Pompes, plank, dead hang, squat, poids.');const fields=['pushupsMax','plankSec','deadHangSec','deepSquatSec','bodyweightKg'],inputs={};fields.forEach(f=>{inputs[f]=input(f,'');c.append(inputs[f])});c.append(btn('Sauver test',()=>{const t={date:Store.today()};fields.forEach(f=>t[f]=inputs[f].value?+inputs[f].value:null);Store.addSportMonthlyTest(t);toast('Test mensuel sauvé')},'green'));Store.sportMonthlyTests().slice(-6).reverse().forEach(t=>c.append(el('div',{class:'exercise'},t.date+' · pompes '+(t.pushupsMax??'-')+' · plank '+(t.plankSec??'-')+'s · poids '+(t.bodyweightKg??'-'))));root.append(c)}
function btn(label,fn,cls=''){return el('button',{class:'btn '+cls,onclick:fn},label)}function input(p,v){return el('input',{class:'input',placeholder:p,type:'number',value:v,style:'max-width:140px'})}
