import { SPORT_LIBRARY, SPORT_PROGRAM, SPORT_CYCLE, FLEX_LEVELS } from '../assets/js/data.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='today',cat='all';
function cycleType(){const c=Store.sportCycle();const d=Math.floor((new Date(Store.today())-new Date(c.anchorDate))/86400000);const s=SPORT_CYCLE.indexOf(c.anchorType);return SPORT_CYCLE[((s<0?0:s)+d%SPORT_CYCLE.length+SPORT_CYCLE.length)%SPORT_CYCLE.length]}
function byId(id){return SPORT_LIBRARY.find(e=>e.id===id)}
function sessions(){return Store.sportSessions()}
function normalizeExerciseLog(x){if(!x)return[];if(Array.isArray(x.performedSets))return x.performedSets;return Array.from({length:+x.sets||1},()=>({reps:x.reps||'',kg:x.kg||'',sec:x.sec||'',rpe:x.rpe||'',pain:x.pain||0}))}
function hist(id){return sessions().filter(s=>s.exercises&&s.exercises[id]).flatMap(s=>normalizeExerciseLog(s.exercises[id]).map((set,i)=>({date:s.date,type:s.sessionType,set:i+1,...set})))}
function best(id){const h=hist(id);let top={score:0,text:'aucun log'};h.forEach(x=>{const kg=+x.kg||0,reps=+x.reps||0,sec=+x.sec||0;const score=kg*reps+reps+sec;if(score>top.score)top={score,text:'S'+x.set+' · '+(kg?kg+'kg · ':'')+(reps?reps+' reps · ':'')+(sec?sec+' sec · ':'')+x.date}});return top.text}
function rx(ex,i,type){if(type==='rest'||ex.category==='warmup')return{sets:2,repsTarget:'12',repsDefault:12,secDefault:30,rpe:5,pain:0,label:'Récupération',visible:'2 tours · 12 reps · 30 sec · RPE 5'};if(ex.category==='mobility')return{sets:2,repsTarget:'',repsDefault:'',secDefault:45,rpe:4,pain:0,label:'Mobilité',visible:'2 séries · 45 sec · RPE 4'};if(ex.category==='core')return{sets:3,repsTarget:'10',repsDefault:10,secDefault:30,rpe:7,pain:0,label:'Core',visible:'3 séries · 10 reps ou 30 sec · RPE 7'};if(i<2)return{sets:4,repsTarget:'6-10',repsDefault:8,secDefault:'',rpe:8,pain:0,label:'Principal',visible:'4 séries · 6-10 reps · RPE 8'};if(i<6)return{sets:3,repsTarget:'8-12',repsDefault:10,secDefault:'',rpe:8,pain:0,label:'Accessoire',visible:'3 séries · 8-12 reps · RPE 8'};return{sets:3,repsTarget:'12-15',repsDefault:12,secDefault:'',rpe:7,pain:0,label:'Finition',visible:'3 séries · 12-15 reps · RPE 7'}}
function defaultSets(r){return Array.from({length:r.sets},()=>({reps:r.repsDefault||'',kg:'',sec:r.secDefault||'',rpe:r.rpe||'',pain:0}))}
function prescription(r){return{sets:r.sets,repsTarget:r.repsTarget,secTarget:r.secDefault,rpe:r.rpe,label:r.label,visible:r.visible}}
export function renderSport(root,rr){const start=el('select',{class:'input',style:'max-width:180px'});SPORT_CYCLE.forEach(x=>start.append(el('option',{value:x},x)));start.value=cycleType();root.append(el('div',{class:'row'},[el('span',{class:'pill'},'Cycle actuel: '+cycleType()),start,btn('Démarrer cycle ici',()=>{Store.setSportCycle({anchorDate:Store.today(),anchorType:start.value});toast('Cycle redémarré: '+start.value);rr()},'green')]));root.append(subTabs([{id:'today',label:'Séance'},{id:'records',label:'Records'},{id:'library',label:'Bibliothèque'},{id:'bodyweight',label:'Poids du corps'},{id:'flex',label:'Souplesse'},{id:'history',label:'Historique'},{id:'tests',label:'Tests'}],panel,id=>{panel=id;rr()}));const box=el('div');root.append(box);({today,records,library,bodyweight,flex,history,tests}[panel]||today)(box,rr)}
function today(root,rr){const type=cycleType(),draft=Store.sportDraft(),ids=SPORT_PROGRAM[type]||[];root.append(summaryCard());const c=card('Séance du jour · '+type,'Chaque série a son slot réel. 4 séries prescrites = 4 lignes à remplir.');ids.forEach((id,i)=>c.append(exercise(byId(id),draft,true,i,type)));const notes=el('textarea',{class:'input',rows:'3',placeholder:'Notes séance / douleur / énergie',value:draft.notes||''});notes.addEventListener('change',()=>Store.setSportDraft(Store.today(),{notes:notes.value}));c.append(notes);c.append(el('div',{class:'row'},[btn('Sauver terminée',()=>saveSession('completed',rr),'green'),btn('Sautée',()=>saveSession('skipped',rr)),btn('Deload',()=>saveSession('deload',rr))]));root.append(c)}
function exercise(ex,draft,log=false,index=0,type=cycleType()){if(!ex)return el('div',{class:'exercise danger'},'Exercice manquant');const r=rx(ex,index,type);const saved=draft.exercises?.[ex.id]||{};const sets=saved.performedSets||defaultSets(r);const d=el('div',{class:'exercise '+(ex.c7Risk==='medium'?'warn':'')});d.append(el('div',{class:'exercise-title'},ex.name));d.append(el('div',{class:'exercise-meta'},[pill(ex.category),pill(ex.equipment),pill('C7 '+ex.c7Risk),pill(ex.difficulty),pill(r.label)]));d.append(el('div',{class:'exercise-title'},'Prescription: '+r.visible));d.append(el('div',{class:'small muted'},'Record: '+best(ex.id)));d.append(el('div',{class:'small muted'},'Règle: '+ex.progressionRule));if(log){sets.forEach((s,i)=>d.append(setRow(ex.id,i,s,r)));d.append(btn('Réinitialiser les séries prescrites',()=>{const cur=Store.sportDraft();cur.exercises=cur.exercises||{};cur.exercises[ex.id]={prescription:prescription(r),performedSets:defaultSets(r)};Store.setSportDraft(Store.today(),cur);toast('Séries réinitialisées')},''))}return d}
function setRow(exId,i,setData,r){const row=el('div',{class:'exercise'});row.append(el('div',{class:'exercise-title'},'Série '+(i+1)+' / '+r.sets));const fields=el('div',{class:'row'});[['reps','Reps'],['kg','Kg'],['sec','Sec'],['rpe','RPE'],['pain','Douleur']].forEach(([k,label])=>fields.append(num(label,setData[k]??'',v=>saveSet(exId,i,k,v,r))));row.append(fields);return row}
function saveSet(exId,i,k,v,r){const cur=Store.sportDraft();cur.exercises=cur.exercises||{};cur.exercises[exId]=cur.exercises[exId]||{prescription:prescription(r),performedSets:defaultSets(r)};cur.exercises[exId].performedSets=cur.exercises[exId].performedSets||defaultSets(r);cur.exercises[exId].performedSets[i]=cur.exercises[exId].performedSets[i]||{};cur.exercises[exId].performedSets[i][k]=v;Store.setSportDraft(Store.today(),cur)}
function saveSession(status,rr){const draft=Store.sportDraft(),type=cycleType(),ids=SPORT_PROGRAM[type]||[];const exercises={};ids.forEach((id,i)=>{const ex=byId(id);if(!ex)return;const r=rx(ex,i,type);const saved=draft.exercises?.[id]||{};exercises[id]={prescription:prescription(r),performedSets:saved.performedSets||defaultSets(r)}});const allSets=Object.values(exercises).flatMap(x=>x.performedSets||[]);const maxPain=Math.max(0,...allSets.map(x=>Number(x.pain||0)));const final=maxPain>=7?'pain_stop':status;Store.addSportSession({date:Store.today(),sessionType:type,status:final,exercises,notes:draft.notes||'',globalPainLevel:maxPain});Store.setSportDraft(Store.today(),{});toast(final==='pain_stop'?'Pain stop enregistré':'Séance sauvegardée');rr()}
function summaryCard(){const all=sessions(),last=all[all.length-1];return card('Résumé sport','Séances: '+all.length+' · dernière: '+(last?last.date+' '+last.sessionType+' '+last.status:'aucune'))}
function records(root){const c=card('Records par exercice','Basé sur les séries réellement loggées.');SPORT_LIBRARY.filter(e=>hist(e.id).length).forEach(e=>c.append(el('div',{class:'exercise'},e.name+' · '+best(e.id)+' · séries loggées '+hist(e.id).length)));root.append(c)}
function library(root,rr){const cats=['all','push','pull','legs','core','bodyweight','mobility','warmup'];root.append(subTabs(cats.map(x=>({id:x,label:x})),cat,id=>{cat=id;rr()}));const list=SPORT_LIBRARY.filter(e=>cat==='all'||e.category===cat);root.append(card('Bibliothèque','Total '+SPORT_LIBRARY.length+' · catégorie '+cat));list.forEach(e=>root.append(exercise(e,{},false)))}
function bodyweight(root){const data=Store.bodyweight();const c=card('Poids du corps','Niveaux 0-5 + meilleur score + date test.');['pushups','pullups','dips','legs','core','mobility'].forEach(f=>{const row=el('div',{class:'exercise'});row.append(el('b',{},f));const lvl=input('niveau 0-5',data[f]?.level||''),bestv=input('meilleur score',data[f]?.best||'');row.append(el('div',{class:'row'},[lvl,bestv,btn('Sauver',()=>{data[f]={level:+lvl.value||0,best:+bestv.value||0,lastTestDate:Store.today()};Store.setBodyweight(data);Store.addBodyweightTest({date:Store.today(),family:f,level:data[f].level,best:data[f].best});toast('Test sauvé')},'green')]));c.append(row)});root.append(c)}
function flex(root){const c=card('Souplesse','Niveaux + mesures.');FLEX_LEVELS.forEach(l=>c.append(el('div',{class:'exercise'},'Niveau '+l.level+' · '+l.label+' · '+l.routineMin+' min · '+l.milestones.join(' / '))));const fields=['forwardFoldCm','pikeCm','straddleDeg','frontSplitRightCm','frontSplitLeftCm','middleSplitCm','deepSquatSec','bridgeScore'],inputs={};fields.forEach(f=>{inputs[f]=input(f,'');c.append(inputs[f])});c.append(btn('Sauver mesures',()=>{const m={date:Store.today()};fields.forEach(f=>m[f]=inputs[f].value?+inputs[f].value:null);Store.addFlexMeasurement(m);toast('Mesures sauvées')},'green'));root.append(c)}
function history(root){const c=card('Historique','Dernières séances.');sessions().slice(-40).reverse().forEach(s=>{const setCount=Object.values(s.exercises||{}).flatMap(x=>normalizeExerciseLog(x)).length;c.append(el('div',{class:'exercise '+(s.status==='pain_stop'?'danger':'')},s.date+' · '+s.sessionType+' · '+s.status+' · douleur '+(s.globalPainLevel??0)+' · séries '+setCount))});root.append(c)}
function tests(root){const c=card('Tests mensuels','Pompes, plank, dead hang, squat, poids.');const fields=['pushupsMax','plankSec','deadHangSec','deepSquatSec','bodyweightKg'],inputs={};fields.forEach(f=>{inputs[f]=input(f,'');c.append(inputs[f])});c.append(btn('Sauver test',()=>{const t={date:Store.today()};fields.forEach(f=>t[f]=inputs[f].value?+inputs[f].value:null);Store.addSportMonthlyTest(t);toast('Test mensuel sauvé')},'green'));Store.sportMonthlyTests().slice(-6).reverse().forEach(t=>c.append(el('div',{class:'exercise'},t.date+' · pompes '+(t.pushupsMax??'-')+' · plank '+(t.plankSec??'-')+'s · poids '+(t.bodyweightKg??'-'))));root.append(c)}
function pill(x){return el('span',{class:'pill'},x)}function btn(label,fn,cls=''){return el('button',{class:'btn '+cls,onclick:fn},label)}function input(p,v){return el('input',{class:'input',placeholder:p,type:'number',value:v,style:'max-width:140px'})}function num(label,v,fn){const w=el('label',{class:'small muted',style:'display:flex;flex-direction:column;gap:4px;min-width:82px;max-width:96px'},[label]);const n=el('input',{class:'input',placeholder:label,type:'number',style:'max-width:96px',value:v});n.addEventListener('change',()=>fn(n.value));w.append(n);return w}
