import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, kpi as uiKpi, compactTable, actionRow } from '../assets/js/ui.js';
import { dailyScore, knownDates, gameSummary, domainScore, priorityScore, weakDomains, globalScore, lastDays } from './game.js';
export function renderStats(root){const g=gameSummary(),v=vintedNumbers(),sav=savingsMonth(),fuel=fuelAvg(),sport=weekSport(),read=readingNumbers();root.append(commandCenter(g));const rail=el('div',{class:'grid'});rail.append(uiKpi('Score',g.global+'/100','global',g.global<50?'danger':g.global<75?'warn':'ok'));rail.append(uiKpi('XP semaine',g.weekXp,'7 jours'));rail.append(uiKpi('Sport',sport.completed+'/'+sport.total,'séances',sport.completed<2?'warn':'ok'));rail.append(uiKpi('Fuel',fuelAvgText(),'moyenne',fuel.water<2200||fuel.protein<110?'warn':'ok'));rail.append(uiKpi('Vinted',euro(v.realProfit),'profit réel',v.realProfit<0?'danger':'ok'));rail.append(uiKpi('Épargne',euro(sav.done)+'/'+euro(sav.target),'mois',sav.done<sav.target?'danger':'ok'));root.append(rail);const grid=el('div',{class:'grid'});grid.append(alertsCard());grid.append(domainBoard());grid.append(priorityStats());grid.append(trackStats());grid.append(vintedStats());grid.append(leisureStats());grid.append(xpBoard());grid.append(activityStats());root.append(grid)}
function commandCenter(g){const w=weakDomains();const c=card('Progrès · contrôle','Score '+globalScore()+'/100 · XP semaine '+g.weekXp+' · domaines faibles '+w.length,'span-12 module-hero '+(g.global<50?'danger':g.global<75?'warn':'ok'));c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+g.global+'%'})));if(w.length)c.append(actionRow({label:'Priorité semaine',meta:w.slice(0,4).map(x=>x.domain+' '+x.xp+' XP').join(' · '),priority:'ALERTE'}));else c.append(actionRow({label:'Tous les domaines sont actifs',meta:'Continuer le rythme.',priority:'OK',done:true}));return c}
function domainBoard(){const s=domainScore();const rows=Object.entries(s).sort((a,b)=>b[1]-a[1]).map(([k,v])=>[k,v+' XP',v<60?'faible':v<120?'moyen':'OK']);const c=card('Domaines','XP sur 7 jours.','span-6');c.append(compactTable(['domaine','xp','état'],rows));return c}
function alertsCard(){const alerts=[];const f=Store.get('fuel_'+Store.today(),{water:0,protein:0});if((+f.water||0)<1500&&new Date().getHours()>=18)alerts.push(['Fuel','Eau sous 1500 ml après 18h']);if((+f.protein||0)<80&&new Date().getHours()>=18)alerts.push(['Fuel','Protéines sous 80 g après 18h']);const stale=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'&&age(x)>=30).length;if(stale)alerts.push(['Vinted',stale+' articles ≥30j']);const sav=savingsMonth();if(sav.done<sav.target)alerts.push(['Épargne','reste '+euro(sav.target-sav.done)]);const pain=Store.sportSessions().slice(-1)[0]?.globalPainLevel||0;if(pain>=7)alerts.push(['Sport','dernière douleur ≥7']);if(!hasActiveBook())alerts.push(['Lecture','aucun livre actif avancé']);weakDomains().slice(0,3).forEach(x=>alerts.push(['Domaine',x.domain+' '+x.xp+' XP']));const c=card('Alertes',alerts.length?alerts.length+' points':'RAS','span-6 '+(alerts.length?'danger':'ok'));if(alerts.length)c.append(compactTable(['zone','signal'],alerts));else c.append(actionRow({label:'RAS',meta:'Aucune alerte majeure.',priority:'OK',done:true}));return c}
function xpBoard(){const rows=knownDates().slice(-14).reverse().map(d=>{const s=dailyScore(d);return[d,s.xp+' XP',s.items.length+' gains']});const c=card('XP quotidien','14 derniers jours.','span-6');c.append(compactTable(['date','xp','détail'],rows));return c}
function priorityStats(){const days=lastDays(7),p=priorityScore(days);const rows=days.map(d=>{const s=dailyScore(d),r={N1:0,N2:0,N3:0};s.items.forEach(x=>{if(r[x.priority]!==undefined)r[x.priority]++});return[d,s.xp+' XP','N1 '+r.N1+' · N2 '+r.N2+' · N3 '+r.N3]});const c=card('Priorités','Semaine: N1 '+p.N1+' · N2 '+p.N2+' · N3 '+p.N3,'span-6');c.append(compactTable(['jour','xp','priorités'],rows));return c}
function trackStats(){const all=Store.get('track_state',{});const rows=['coding','ai','iot','repair'].map(k=>{const s=all[k]||{},b=BOOKS[k]||[],e=EXERCISE_PACKS[k]||[];return[k.toUpperCase(),(s.bookIndex||0)+'/'+b.length,(s.exerciseIndex||0)+'/'+e.length]});const c=card('Étude','Livres + exercices.','span-6');c.append(compactTable(['track','livres','exercices'],rows));return c}
function vintedStats(){const v=vintedNumbers();const c=card('Vinted','Stock et résultat réel.','span-6 '+(v.realProfit<0?'danger':'ok'));c.append(compactTable(['métrique','valeur'],[['total',v.total],['actifs',v.active],['à traiter',v.stale],['vendus',v.sold],['pertes',v.losses],['stock cash',euro(v.activeCost)],['profit réel',euro(v.realProfit)]]));return c}
function leisureStats(){const chess=Store.get('chess_elo_history',[]),last=chess[chess.length-1],read=readingNumbers(),games=Store.get('chess_games',[]);const c=card('Loisir','Échecs + lecture.','span-6');c.append(compactTable(['zone','valeur'],[['ELO',last?last.elo:'-'],['tendance',chessTrend()],['parties',games.length],['livres terminés',read.done],['pages',read.pages],['actions lecture',read.actions]]));return c}
function activityStats(){const a=Store.get('study_activity',[]);const rows=a.slice(-12).reverse().map(x=>[x.date||'-',x.domain||'-',x.title||x.exercise||x.resourceId||x.kind||x.status||'-']);const c=card('Activité récente','Derniers logs.','span-12');c.append(compactTable(['date','zone','action'],rows));return c}
function fuelAvg(){const days=lastDays(7);let w=0,p=0;days.forEach(d=>{const f=Store.get('fuel_'+d,{water:0,protein:0});w+=+f.water||0;p+=+f.protein||0});return{water:w/days.length,protein:p/days.length}}
function fuelAvgText(){const f=fuelAvg();return Math.round(f.water)+'ml / '+Math.round(f.protein)+'g'}
function weekSport(){const days=new Set(lastDays(7));const ss=Store.sportSessions().filter(s=>days.has(s.date));return{total:ss.length,completed:ss.filter(s=>s.status==='completed'||s.status==='deload').length}}
function vintedNumbers(){const list=Store.get('vinted_items',[]);const sold=list.filter(x=>x.status==='sold'),active=list.filter(x=>x.status!=='sold'&&x.status!=='abandoned');return{total:list.length,sold:sold.length,active:active.length,stale:active.filter(x=>age(x)>=14).length,activeCost:active.reduce((a,x)=>a+vcost(x),0),revenue:sold.reduce((a,x)=>a+(+x.sold||0),0),realProfit:sold.reduce((a,x)=>a+((+x.sold||0)-vcost(x)),0),losses:sold.filter(x=>((+x.sold||0)-vcost(x))<0).length}}
function savingsMonth(){const d=Store.get('finance_month',{income:2300,savingsGoalPct:20});const target=Math.round((+d.income||0)*(+d.savingsGoalPct||0)/100);const month=new Date().toISOString().slice(0,7);const done=Store.get('savings_history',[]).filter(x=>x.month===month).reduce((a,x)=>a+(+x.amount||0),0);return{target,done}}
function readingNumbers(){const reading=Store.get('reading_tracks',{});let done=0,pages=0,actions=0;Object.values(reading).forEach(t=>Object.values(t.books||{}).forEach(b=>{if(b.done)done++;pages+=+b.current||0;if(b.notes?.action)actions++}));return{done,pages,actions}}
function hasActiveBook(){const reading=Store.get('reading_tracks',{});return Object.values(reading).some(t=>Object.values(t.books||{}).some(b=>!b.done&&(+b.current||0)>0))}
function chessTrend(){const h=Store.get('chess_elo_history',[]);if(h.length<2)return'-';const d=(+h[h.length-1].elo||0)-(+h[h.length-2].elo||0);return d>=0?'+'+d:String(d)}
function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}function vcost(x){return(+x.buy||0)+(+x.shipping||0)+(+x.boost||0)+(x.boosts||[]).reduce((a,b)=>a+(+b.amount||0),0)}function euro(n){return(Number(n)||0).toFixed(2)+' €'}
