import { FEATURES } from '../assets/js/data.js';
import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card } from '../assets/js/ui.js';
import { renderGameCard, dailyScore, knownDates, gameSummary } from './game.js';
export function renderStats(root){root.append(renderGameCard());root.append(weeklyCommand());root.append(alertsCard());root.append(xpBoard());const v=vintedNumbers();const grid=el('div',{class:'grid'});grid.append(metric('XP aujourd’hui',gameSummary().todayXp+' XP'));grid.append(metric('XP semaine',gameSummary().weekXp+' XP'));grid.append(metric('Sport semaine',weekSport().completed+'/'+weekSport().total));grid.append(metric('Fuel moyen',fuelAvgText()));grid.append(metric('Profit Vinted',euro(v.realProfit)));grid.append(metric('Cash stock',euro(v.activeCost)));grid.append(metric('Épargne mois',euro(savingsMonth().done)+'/'+euro(savingsMonth().target)));grid.append(metric('Pages lues',readingNumbers().pages+' pages'));grid.append(metric('Tendance ELO',chessTrend()));root.append(grid);root.append(priorityStats());root.append(trackStats());root.append(vintedStats());root.append(leisureStats());root.append(activityStats())}
function metric(title,value){const c=card(title,value,'span-4');c.append(el('div',{class:'metric'},String(value).split(' ')[0]));return c}
function lastDays(n=7){const out=[];const d=new Date(Store.today());for(let i=n-1;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);out.push(x.toISOString().slice(0,10))}return out}
function weeklyCommand(){const days=lastDays(7),xp=days.reduce((a,d)=>a+dailyScore(d).xp,0),prio=priorityCounts(days),fuel=fuelAvg(),sport=weekSport(),v=vintedNumbers(),sav=savingsMonth(),read=readingNumbers();const c=card('Tableau semaine','XP '+xp+' · N1 '+prio.N1+' · N2 '+prio.N2+' · N3 '+prio.N3+' · sport '+sport.completed+'/'+sport.total+' · eau '+Math.round(fuel.water)+'ml · prot '+Math.round(fuel.protein)+'g · Vinted réel '+euro(v.realProfit)+' · stock '+euro(v.activeCost)+' · épargne '+euro(sav.done)+'/'+euro(sav.target)+' · lecture '+read.pages+' pages');c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+Math.min(100,Math.round(xp/1000*100))+'%'})));return c}
function alertsCard(){const alerts=[];const f=Store.get('fuel_'+Store.today(),{water:0,protein:0});if((+f.water||0)<1500&&new Date().getHours()>=18)alerts.push('Eau sous 1500 ml après 18h');if((+f.protein||0)<80&&new Date().getHours()>=18)alerts.push('Protéines sous 80 g après 18h');const stale=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'&&age(x)>=30).length;if(stale)alerts.push('Vinted: '+stale+' articles ≥30j');const sav=savingsMonth();if(sav.done<sav.target)alerts.push('Épargne: reste '+euro(sav.target-sav.done));const pain=Store.sportSessions().slice(-1)[0]?.globalPainLevel||0;if(pain>=7)alerts.push('Sport: dernière douleur ≥7');if(!hasActiveBook())alerts.push('Lecture: aucun livre actif réellement avancé');const c=card('Alertes opérationnelles',alerts.length?alerts.length+' alertes':'RAS');c.className+=' '+(alerts.length?'danger':'ok');alerts.forEach(a=>c.append(el('div',{class:'exercise danger'},a)));return c}
function xpBoard(){const c=card('Classement XP · historique','XP par jour basé sur validations réelles.');knownDates().slice(-14).reverse().forEach(d=>{const s=dailyScore(d);c.append(el('div',{class:'exercise'},d+' · '+s.xp+' XP · '+(s.items.map(x=>x.id+'+'+x.xp).join(' / ')||'aucun gain')))});return c}
function priorityCounts(days=lastDays(7)){const out={N1:0,N2:0,N3:0};days.forEach(d=>{dailyScore(d).items.forEach(x=>{if(out[x.priority]!==undefined)out[x.priority]++})});return out}
function priorityStats(){const days=lastDays(7),p=priorityCounts(days);const c=card('Priorités validées','Semaine: N1 '+p.N1+' · N2 '+p.N2+' · N3 '+p.N3);days.forEach(d=>{const s=dailyScore(d),row={N1:0,N2:0,N3:0};s.items.forEach(x=>{if(row[x.priority]!==undefined)row[x.priority]++});c.append(el('div',{class:'exercise'},d+' · '+s.xp+' XP · N1 '+row.N1+' · N2 '+row.N2+' · N3 '+row.N3))});return c}
function fuelAvg(){const days=lastDays(7);let w=0,p=0;days.forEach(d=>{const f=Store.get('fuel_'+d,{water:0,protein:0});w+=+f.water||0;p+=+f.protein||0});return{water:w/days.length,protein:p/days.length}}
function fuelAvgText(){const f=fuelAvg();return Math.round(f.water)+'ml / '+Math.round(f.protein)+'g'}
function weekSport(){const days=new Set(lastDays(7));const ss=Store.sportSessions().filter(s=>days.has(s.date));return{total:ss.length,completed:ss.filter(s=>s.status==='completed').length}}
function trackStats(){const all=Store.get('track_state',{});const c=card('Parcours étude','Progression livres + exercices.');['coding','ai','iot','repair'].forEach(k=>{const s=all[k]||{};const b=BOOKS[k]||[];const e=EXERCISE_PACKS[k]||[];c.append(el('div',{class:'exercise'},k.toUpperCase()+' · livres '+(s.bookIndex||0)+'/'+b.length+' · exercices '+(s.exerciseIndex||0)+'/'+e.length))});return c}
function vintedNumbers(){const list=Store.get('vinted_items',[]);const sold=list.filter(x=>x.status==='sold'),active=list.filter(x=>x.status!=='sold'&&x.status!=='abandoned');return{total:list.length,sold:sold.length,active:active.length,stale:active.filter(x=>age(x)>=14).length,activeCost:active.reduce((a,x)=>a+vcost(x),0),activePotential:active.reduce((a,x)=>a+((+x.asking||0)-vcost(x)),0),revenue:sold.reduce((a,x)=>a+(+x.sold||0),0),realProfit:sold.reduce((a,x)=>a+((+x.sold||0)-vcost(x)),0),losses:sold.filter(x=>((+x.sold||0)-vcost(x))<0).length}}
function vintedStats(){const v=vintedNumbers();const c=card('Stats Vinted','Total '+v.total+' · actifs '+v.active+' · à traiter '+v.stale+' · vendus '+v.sold+' · pertes réelles '+v.losses+' · cash stock '+euro(v.activeCost)+' · potentiel stock '+euro(v.activePotential)+' · encaissé '+euro(v.revenue)+' · profit réel '+euro(v.realProfit));c.className+=' '+(v.realProfit<0?'danger':'ok');return c}
function savingsMonth(){const d=Store.get('finance_month',{income:2300,savingsGoalPct:20});const target=Math.round((+d.income||0)*(+d.savingsGoalPct||0)/100);const month=new Date().toISOString().slice(0,7);const done=Store.get('savings_history',[]).filter(x=>x.month===month).reduce((a,x)=>a+(+x.amount||0),0);return{target,done}}
function leisureStats(){const chess=Store.get('chess_elo_history',[]),last=chess[chess.length-1],read=readingNumbers(),games=Store.get('chess_games',[]);return card('Stats loisir','ELO '+(last?last.elo:'-')+' · tendance '+chessTrend()+' · parties loggées '+games.length+' · livres terminés '+read.done+' · pages '+read.pages+' · actions lecture '+read.actions)}
function readingNumbers(){const reading=Store.get('reading_tracks',{});let done=0,pages=0,actions=0;Object.values(reading).forEach(t=>Object.values(t.books||{}).forEach(b=>{if(b.done)done++;pages+=+b.current||0;if(b.notes?.action)actions++}));return{done,pages,actions}}
function hasActiveBook(){const reading=Store.get('reading_tracks',{});return Object.values(reading).some(t=>Object.values(t.books||{}).some(b=>!b.done&&(+b.current||0)>0))}
function chessTrend(){const h=Store.get('chess_elo_history',[]);if(h.length<2)return'-';const d=(+h[h.length-1].elo||0)-(+h[h.length-2].elo||0);return d>=0?'+'+d:String(d)}
function activityStats(){const a=Store.get('study_activity',[]);const c=card('Activité récente','Derniers logs enregistrés.');a.slice(-12).reverse().forEach(x=>c.append(el('div',{class:'exercise'},(x.date||'-')+' · '+(x.domain||'-')+' · '+(x.kind||x.status||'-')+' · '+(x.title||x.exercise||x.resourceId||'-'))));return c}
function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}function vcost(x){return(+x.buy||0)+(+x.shipping||0)+(+x.boost||0)+(x.boosts||[]).reduce((a,b)=>a+(+b.amount||0),0)}function euro(n){return(Number(n)||0).toFixed(2)+' €'}