import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, kpi as uiKpi, compactTable, actionRow } from '../assets/js/ui.js';
import { dailyScore, knownDates, gameSummary, domainScore, priorityScore, weakDomains, globalScore, lastDays } from './game.js';

export function renderStats(root){const g=gameSummary(),v=vintedNumbers(),sav=savingsMonth(),fuel=fuelAvg(),sport=weekSport(),read=readingNumbers(),truth=truthSignal(g,v,sav,fuel,sport,read);root.append(commandCenter(g,truth));const rail=el('div',{class:'grid'});rail.append(uiKpi('Score global',g.global+'/100','niveau opérationnel',g.global<50?'danger':g.global<75?'warn':'ok'));rail.append(uiKpi('Signal faible',truth.zone,truth.action,truth.cls));rail.append(uiKpi('N1 semaine',priorityScore(lastDays(7)).N1,'actions vitales'));rail.append(uiKpi('Sport',sport.completed+'/'+sport.total,'7 jours',sport.completed<2?'warn':'ok'));rail.append(uiKpi('Fuel',fuelAvgText(),'moyenne',fuel.water<2200||fuel.protein<110?'warn':'ok'));rail.append(uiKpi('Épargne',euro(sav.done)+'/'+euro(sav.target),'mois',sav.done<sav.target?'danger':'ok'));root.append(rail);const grid=el('div',{class:'grid'});grid.append(alertsCard(),domainBoard(),priorityStats(),trackStats(),vintedStats(),proofStats(),xpBoard(),activityStats());root.append(grid)}
function commandCenter(g,t){const w=weakDomains();const c=card('COMMAND DASHBOARD','Score '+globalScore()+'/100 · XP semaine '+g.weekXp+' · signal: '+t.zone,'span-12 module-hero '+t.cls);c.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+g.global+'%'})));c.append(actionRow({label:'Ordre correctif',meta:t.action,priority:t.prio}));if(w.length)c.append(actionRow({label:'Domaines faibles',meta:w.slice(0,4).map(x=>x.domain+' '+x.xp+' XP').join(' · '),priority:'ALERTE'}));else c.append(actionRow({label:'Tous les domaines actifs',meta:'Maintenir rythme.',priority:'OK',done:true}));return c}
function truthSignal(g,v,sav,fuel,sport,read){if(g.global<45)return{zone:'discipline globale',action:'Revenir aux N1 uniquement pendant 48h.',prio:'N1',cls:'danger'};if(fuel.water<2200||fuel.protein<110)return{zone:'fuel',action:'Corriger eau/protéines avant nouveaux objectifs.',prio:'N1',cls:'danger'};if(sport.completed<2)return{zone:'sport',action:'Planifier séance courte ou mobilité.',prio:'N2',cls:'warn'};if(v.stale>=3)return{zone:'Vinted',action:'Traiter stock mort: 3 articles.',prio:'N1',cls:'danger'};if(sav.done<sav.target)return{zone:'épargne',action:'Verser ou réduire sortie cash.',prio:'N2',cls:'warn'};if(read.actions<1)return{zone:'preuves',action:'Transformer lecture en action écrite.',prio:'N2',cls:'warn'};return{zone:'stable',action:'Maintenir. Ne pas empiler.',prio:'OK',cls:'ok'}}
function alertsCard(){const alerts=[],f=Store.get('fuel_'+Store.today(),{water:0,protein:0});if((+f.water||0)<1500&&new Date().getHours()>=18)alerts.push(['Fuel','Eau sous 1500 ml après 18h']);if((+f.protein||0)<80&&new Date().getHours()>=18)alerts.push(['Fuel','Protéines sous 80 g après 18h']);const stale=Store.get('vinted_items',[]).filter(x=>x.status!=='sold'&&x.status!=='abandoned'&&age(x)>=30).length;if(stale)alerts.push(['Vinted',stale+' articles ≥30j']);const sav=savingsMonth();if(sav.done<sav.target)alerts.push(['Épargne','reste '+euro(sav.target-sav.done)]);const pain=Store.sportSessions().slice(-1)[0]?.globalPainLevel||0;if(pain>=7)alerts.push(['Sport','dernière douleur ≥7']);weakDomains().slice(0,3).forEach(x=>alerts.push(['Domaine',x.domain+' '+x.xp+' XP']));const c=card('Alertes',alerts.length?alerts.length+' points':'RAS','span-6 '+(alerts.length?'danger':'ok'));c.append(alerts.length?compactTable(['zone','signal'],alerts):actionRow({label:'RAS',meta:'Aucune alerte majeure.',priority:'OK',done:true}));return c}
function domainBoard(){const rows=Object.entries(domainScore()).sort((a,b)=>b[1]-a[1]).map(([k,v])=>[k,v+' XP',v<60?'faible':v<120?'moyen':'OK']);const c=card('Domaines','XP sur 7 jours.','span-6');c.append(compactTable(['domaine','xp','état'],rows));return c}
function priorityStats(){const days=lastDays(7),p=priorityScore(days);const rows=days.map(d=>{const s=dailyScore(d),r={N1:0,N2:0,N3:0};s.items.forEach(x=>{if(r[x.priority]!==undefined)r[x.priority]++});return[d,s.xp+' XP','N1 '+r.N1+' · N2 '+r.N2+' · N3 '+r.N3]});const c=card('Priorités','Semaine: N1 '+p.N1+' · N2 '+p.N2+' · N3 '+p.N3,'span-6');c.append(compactTable(['jour','xp','priorités'],rows));return c}
function trackStats(){const all=Store.get('track_state',{});const rows=['coding','ai','iot','repair'].map(k=>{const s=all[k]||{},b=BOOKS[k]||[],e=EXERCISE_PACKS[k]||[];return[k.toUpperCase(),(s.bookIndex||0)+'/'+b.length,(s.exerciseIndex||0)+'/'+e.length]});const c=card('Étude technique','Livres + exercices.','span-6');c.append(compactTable(['track','livres','exercices'],rows));return c}
function vintedStats(){const v=vintedNumbers();const c=card('Vinted','Stock et résultat réel.','span-6 '+(v.realProfit<0?'danger':v.stale>=3?'warn':'ok'));c.append(compactTable(['métrique','valeur'],[['total',v.total],['actifs',v.active],['à traiter',v.stale],['vendus',v.sold],['pertes',v.losses],['stock cash',euro(v.activeCost)],['profit réel',euro(v.realProfit)]]));return c}
function proofStats(){const list=Store.get('proofs',[]),today=list.filter(x=>x.date===Store.today()||x.dueDate===Store.today()),valid=today.filter(x=>x.status==='validated');const c=card('Preuves','Aujourd’hui '+valid.length+'/3 · total '+list.length,'span-6 '+(valid.length>=3?'ok':'warn'));c.append(compactTable(['preuve','statut'],[['étude',valid.some(x=>x.course==='étude')?'OK':'manque'],['santé/sport',valid.some(x=>x.course==='santé/sport')?'OK':'manque'],['argent/admin',valid.some(x=>x.course==='argent/admin')?'OK':'manque']]));return c}
function xpBoard(){const rows=knownDates().slice(-14).reverse().map(d=>{const s=dailyScore(d);return[d,s.xp+' XP',s.items.length+' gains']});const c=card('XP quotidien','14 derniers jours.','span-6');c.append(compactTable(['date','xp','détail'],rows));return c}
function activityStats(){const a=Store.get('study_activity',[]);const rows=a.slice(-12).reverse().map(x=>[x.date||'-',x.domain||'-',x.title||x.exercise||x.resourceId||x.kind||x.status||'-']);const c=card('Activité récente','Derniers logs.','span-12');c.append(compactTable(['date','zone','action'],rows));return c}
function fuelAvg(){const days=lastDays(7);let w=0,p=0;days.forEach(d=>{const f=Store.get('fuel_'+d,{water:0,protein:0});w+=+f.water||0;p+=+f.protein||0});return{water:w/days.length,protein:p/days.length}}
function fuelAvgText(){const f=fuelAvg();return Math.round(f.water)+'ml / '+Math.round(f.protein)+'g'}function weekSport(){const days=new Set(lastDays(7));const ss=Store.sportSessions().filter(s=>days.has(s.date));return{total:ss.length,completed:ss.filter(s=>s.status==='completed'||s.status==='deload').length}}function vintedNumbers(){const list=Store.get('vinted_items',[]);const sold=list.filter(x=>x.status==='sold'),active=list.filter(x=>x.status!=='sold'&&x.status!=='abandoned');return{total:list.length,sold:sold.length,active:active.length,stale:active.filter(x=>age(x)>=14).length,activeCost:active.reduce((a,x)=>a+vcost(x),0),realProfit:sold.reduce((a,x)=>a+((+x.sold||0)-vcost(x)),0),losses:sold.filter(x=>((+x.sold||0)-vcost(x))<0).length}}
function savingsMonth(){const d=Store.get('finance_month',{income:2300,savingsGoalPct:20});const target=Math.round((+d.income||0)*(+d.savingsGoalPct||0)/100),month=new Date().toISOString().slice(0,7),done=Store.get('savings_history',[]).filter(x=>x.month===month).reduce((a,x)=>a+(+x.amount||0),0);return{target,done}}function readingNumbers(){const reading=Store.get('reading_tracks',{});let done=0,pages=0,actions=0;Object.values(reading).forEach(t=>Object.values(t.books||{}).forEach(b=>{if(b.done)done++;pages+=+b.current||0;if(b.notes?.action)actions++}));return{done,pages,actions}}function age(x){return Math.max(0,Math.floor((new Date(Store.today())-new Date(x.listedAt||Store.today()))/86400000))}function vcost(x){return(+x.buy||0)+(+x.shipping||0)+(+x.boost||0)+(x.boosts||[]).reduce((a,b)=>a+(+b.amount||0),0)}function euro(n){return(Number(n)||0).toFixed(2)+' €'}
