import { BOOKS, EXERCISE_PACKS, NL_RESOURCES, NL_PLAN } from '../assets/js/study-catalog.js';
import { PRACTICE_SITES } from '../assets/js/practice-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, toast } from '../assets/js/ui.js';
const LABELS={coding:'Coding',ai:'IA',iot:'IoT',repair:'Réparation',python:'Python',linux:'Linux',network:'Réseaux',security:'Sécurité',nl:'Néerlandais'};
export function renderTrack(root,rr,track){const title=LABELS[track]||track.toUpperCase();root.append(card(title+' · parcours séquentiel',track==='nl'?'Livres, grammaire, sites, apps, SELOR/CNaVT et CVO Semper.':'Une ressource active: total pages + pages lues, puis exercices séquentiels.'));resume(root,track);books(root,rr,track);exercises(root,rr,track);track==='nl'?nlExtras(root,rr):sites(root,rr,track)}
function all(){return Store.get('track_state',{})}function save(s){Store.set('track_state',s)}function st(s,track){s[track]=s[track]||{bookIndex:0,books:{},exerciseIndex:0,done:{},notes:{}};s[track].books=s[track].books||{};s[track].done=s[track].done||{};s[track].notes=s[track].notes||{};return s[track]}
function resume(root,track){const s=st(all(),track),b=BOOKS[track]||[],q=EXERCISE_PACKS[track]||[];root.append(card('Mode reprise '+(LABELS[track]||track),'Livre: '+(b[s.bookIndex]||'terminé')+' · Exercice: '+(q[s.exerciseIndex]||'terminé')))}
function books(root,rr,track){const state=all(),s=st(state,track),list=BOOKS[track]||[];const c=card('Livres / cours '+(LABELS[track]||track),'Renseigne total pages + pages lues. Le champ + pages est supprimé.');list.forEach((name,i)=>{const p=s.books[name]||{current:0,total:0,done:false};const locked=i>s.bookIndex,done=p.done;const row=el('div',{class:'exercise '+(done?'ok':locked?'warn':'')});row.append(el('div',{class:'exercise-title'},(done?'✅ ':locked?'🔒 ':'📘 ')+name));row.append(el('div',{class:'small muted'},(p.current||0)+'/'+(p.total||'?')+' pages'));row.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct(p.current,p.total)+'%'})));if(!locked&&!done){const total=input('total pages',p.total||''),read=input('pages lues',p.current||''),note=el('input',{class:'input',placeholder:'note / preuve'});row.append(el('div',{class:'row'},[total,read,note,el('button',{class:'btn',onclick:()=>{saveBook(state,s,track,name,+read.value||0,+total.value||0,note.value,false);toast('Progression sauvée');rr()}},'Valider'),el('button',{class:'btn green',onclick:()=>{saveBook(state,s,track,name,+read.value||0,+total.value||0,note.value,true);toast('Ressource terminée');rr()}},'Terminer et débloquer')]))}c.append(row)});root.append(c)}
function saveBook(state,s,track,name,pagesRead,total,note,finish){const p=s.books[name]||{current:0,total:0,done:false};p.total=total||p.total||0;p.current=pagesRead||p.current||0;p.note=note||p.note||'';if(finish||(p.total&&p.current>=p.total)){p.done=true;s.bookIndex=Math.min((s.bookIndex||0)+1,(BOOKS[track]||[]).length)}s.books[name]=p;state[track]=s;save(state);Store.push('study_activity',{domain:track,kind:'book',title:name,pagesRead:p.current,total:p.total,note,finished:p.done,date:Store.today()})}
function exercises(root,rr,track){const state=all(),s=st(state,track),q=EXERCISE_PACKS[track]||[];const c=card('Exercices '+(LABELS[track]||track),'Un exercice actif. Valide pour débloquer le suivant.');q.forEach((name,i)=>{const done=s.done[name],locked=i>s.exerciseIndex;const row=el('div',{class:'exercise '+(done?'ok':locked?'warn':'')});row.append(el('div',{class:'exercise-title'},(done?'✅ ':locked?'🔒 ':'🎯 ')+name));if(!locked&&!done){const note=el('input',{class:'input',placeholder:'note / erreur / preuve'});row.append(el('div',{class:'row'},[note,el('button',{class:'btn green',onclick:()=>{s.done[name]=true;s.notes[name]=note.value;s.exerciseIndex=Math.min(s.exerciseIndex+1,q.length);state[track]=s;save(state);Store.push('study_activity',{domain:track,kind:'exercise',title:name,note:note.value,date:Store.today()});toast('Exercice validé');rr()}},'Valider et débloquer')]))}c.append(row)});root.append(c)}
function nlExtras(root,rr){const plan=card('Plan NL','Progression structurée.');NL_PLAN.forEach(x=>plan.append(el('div',{class:'exercise'},[el('b',{},x[0]+' · '+x[1]),el('div',{class:'small muted'},x[2])])));root.append(plan);const c=card('Ressources NL','Livres, sites, apps, bibliothèques, SELOR/CNaVT, CVO Semper.');NL_RESOURCES.forEach(x=>c.append(el('div',{class:'exercise'},[el('b',{},x.kind+' · '+x.title),el('div',{class:'small muted'},(x.level||'-')+' · '+(x.goal||'-')),el('div',{class:'small muted'},x.url||'ressource physique'),el('button',{class:'btn green',onclick:()=>{Store.push('study_activity',{domain:'nl',kind:x.kind,title:x.title,date:Store.today()});Store.push('study_materials',{course:'nl',source:x.kind,title:x.title,url:x.url||'',current:0,total:0,status:'active'});toast('Ressource NL validée') }},'Ajouter / valider')])));root.append(c)}
function sites(root,rr,track){const c=card('Sites utiles '+(LABELS[track]||track),'Ajout rapide au matériel si nécessaire.');(PRACTICE_SITES[track]||[]).forEach(x=>c.append(el('div',{class:'exercise'},[el('b',{},x[0]),el('div',{class:'small muted'},x[2]),el('button',{class:'btn',onclick:()=>{Store.push('study_materials',{course:track,source:'site',title:x[0],url:x[1],current:0,total:0,status:'active'});toast('Site ajouté') }},'Ajouter site')])));root.append(c)}
function input(p,v){return el('input',{class:'input',placeholder:p,type:'number',value:v,style:'max-width:150px'})}function pct(a,b){return b?Math.min(100,Math.round((+a||0)/(+b||1)*100)):0}
