import { renderEpfcYear1 } from './study-epfc.js';
import { renderTrack } from './study-track.js';
import { CERTS } from '../assets/js/data.js';
import { COURSES } from '../assets/js/study-catalog.js';
import { EPFC_YEAR1 } from '../assets/js/epfc-year1.js';
import { EPFC_DAILY_ROTATION } from '../assets/js/practice-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='resume';
export function renderStudy(root,rr){const tabs=['resume:Commandement','epfc:EPFC','coding:Coding','ai:IA','iot:IoT','repair:Réparation','errors:Erreurs','proofs:Preuves','certs:Certifs'].map(x=>{const a=x.split(':');return{id:a[0],label:a[1]}});root.append(subTabs(tabs,panel,id=>{panel=id;rr()}));const box=el('div');root.append(box);if(panel==='epfc')return renderEpfcYear1(box,rr);if(['coding','ai','iot','repair'].includes(panel))return renderTrack(box,rr,panel);({resume,errors,proofs,certs}[panel]||resume)(box,rr)}
function resume(root,rr){const ep=epfcToday(),due=dueErrors(),p=proofState(),g=el('div',{class:'grid'});g.append(order(ep,due,p,rr),quick(rr),proofCard(rr),review(due,rr),track('coding',rr),track('ai',rr),track('iot',rr),track('repair',rr));root.append(g);root.append(activity())}
function order(ep,due,p,rr){const hot=due.length||p.valid<1,c=card('ETUDE COMMAND','EPFC → erreurs → preuve → technique','span-12 module-hero '+(hot?'danger':'ok')),title=due.length?'Réviser '+due.length+' erreurs':'EPFC '+ep.code+' · '+ep.title;c.append(el('div',{class:'exercise'},[el('b',{},title),el('div',{class:'small muted'},'25 min ou fallback 5 min. Une trace obligatoire.'),el('div',{class:'row'},[btn('Valider 25 min',()=>log('study','deep',title,rr),'green'),btn('Fallback 5 min',()=>log('study','fallback',title,rr))]) ]));return c}
function quick(rr){const c=card('Validation rapide','Trace minimale.','span-6'),domain=sel(['epfc','coding','ai','iot','repair','nl']),kind=sel(['exercice','livre','preuve','revision']),note=inp('note');c.append(el('div',{class:'row'},[domain,kind,note,btn('Valider',()=>{Store.push('study_activity',{domain:domain.value,kind:kind.value,title:note.value||kind.value,date:Store.today(),status:'done'});if(kind.value==='preuve')Store.push('proofs',{course:'étude',title:note.value||'Preuve étude',date:Store.today(),dueDate:Store.today(),status:'validated'});toast('Étude validée');rr()},'green')]));return c}
function proofCard(rr){const zones=['étude','santé/sport','argent/admin'],p=proofState(),c=card('Preuves du jour',p.valid+'/3','span-6 '+(p.valid>=3?'ok':'danger'));zones.forEach(z=>{const ok=p.valids.some(x=>x.course===z);c.append(el('div',{class:'exercise '+(ok?'ok':'')},[el('b',{},z),btn(ok?'OK':'Valider',()=>{Store.push('proofs',{course:z,title:'Preuve '+z,date:Store.today(),dueDate:Store.today(),status:'validated'});toast('Preuve validée');rr()},ok?'green':'')]))});return c}
function proofs(root,rr){root.append(proofCard(rr));const c=card('Historique preuves','Dernières traces.');Store.get('proofs',[]).slice().reverse().slice(0,30).forEach(p=>c.append(el('div',{class:'exercise '+(p.status==='validated'?'ok':'warn')},(p.date||p.dueDate||'-')+' · '+(p.course||'-')+' · '+(p.title||'-'))));root.append(c)}
function errors(root,rr){root.append(review(dueErrors(),rr));const c=card('Ajouter erreur','Erreur → correction → prochaine révision.'),course=sel(COURSES.map(x=>x[0])),err=inp('erreur'),fix=inp('correction'),days=sel(['1','3','7','14','30']);c.append(el('div',{class:'row'},[course,err,fix,days,btn('Ajouter',()=>{Store.push('error_bank',{course:course.value,error:err.value,fix:fix.value,reviewCount:0,nextReview:addDays(+days.value||3),status:'open'});toast('Erreur ajoutée');rr()},'green')]));root.append(c)}
function review(due,rr){const c=card('Révisions dues',due.length?due.length+' à revoir':'RAS','span-6 '+(due.length?'danger':'ok'));due.slice(0,8).forEach(x=>c.append(el('div',{class:'exercise danger'},[el('b',{},x.error||'Erreur'),el('div',{class:'small muted'},x.fix||'-'),el('div',{class:'row'},[btn('Revu',()=>{Store.updateList('error_bank',x.id,{reviewCount:(x.reviewCount||0)+1,nextReview:addDays(3),status:'reviewed'});toast('Révision validée');rr()},'green'),btn('Faux',()=>{Store.updateList('error_bank',x.id,{reviewCount:0,nextReview:addDays(1),status:'failed'});toast('Revoir demain');rr()},'danger')])])));return c}
function certs(root,rr){const c=card('Certifications','Cible et date.'),name=sel(CERTS),date=inp('date cible','date');c.append(el('div',{class:'row'},[name,date,btn('Ajouter',()=>{Store.push('certifications',{name:name.value,targetDate:date.value,status:'active'});toast('Certif ajoutée');rr()},'green')]));root.append(c);Store.get('certifications',[]).forEach(x=>root.append(card(x.name,(x.targetDate||'-')+' · '+x.status)))}
function track(k,rr){const c=card(k.toUpperCase(),'Bloc technique 25 min.','span-4');c.append(el('div',{class:'row'},[btn('Valider',()=>log(k,'exercise','Validation '+k,rr),'green'),btn('Ouvrir',()=>{panel=k;rr()})]));return c}
function activity(){const c=card('Activité récente','Logs étude.');Store.get('study_activity',[]).slice(-12).reverse().forEach(x=>c.append(el('div',{class:'exercise'},(x.date||'-')+' · '+(x.domain||'-')+' · '+(x.kind||'-')+' · '+(x.title||'-'))));return c}
function log(domain,kind,title,rr){Store.push('study_activity',{domain,kind,title,date:Store.today(),status:'done'});toast('Bloc validé');rr()}function proofState(){const list=Store.get('proofs',[]).filter(x=>x.date===Store.today()||x.dueDate===Store.today()),valids=list.filter(x=>x.status==='validated');return{valids,valid:valids.length}}function dueErrors(){return Store.get('error_bank',[]).filter(x=>x.status!=='closed'&&(x.nextReview||'9999')<=Store.today())}function epfcToday(){const code=EPFC_DAILY_ROTATION[new Date().getDay()%EPFC_DAILY_ROTATION.length];return EPFC_YEAR1.find(c=>c.code===code)||EPFC_YEAR1[0]}function addDays(n){const d=new Date(Store.today());d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}function inp(p,t='text',v=''){return el('input',{class:'input',placeholder:p,type:t,value:v})}function sel(items,v=''){const s=el('select',{class:'input'});items.forEach(x=>s.append(el('option',{value:Array.isArray(x)?x[0]:x},Array.isArray(x)?x[1]:x)));s.value=v;return s}function btn(label,onClick,cls=''){return el('button',{class:'btn '+cls,onclick:onClick},label)}
