import { BOOKS, EXERCISE_PACKS } from '../assets/js/study-catalog.js';
import { PRACTICE_SITES } from '../assets/js/practice-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, toast } from '../assets/js/ui.js';
const LABELS={coding:'Coding',ai:'IA',iot:'IoT',repair:'Réparation'};
export function renderTrack(root,rr,track){const title=LABELS[track]||track.toUpperCase();root.append(card(title+' · parcours séquentiel','Même logique que EPFC: une ressource active, validation pages, déblocage suivant, puis exercices séquentiels.'));resume(root,track);books(root,rr,track);exercises(root,rr,track);sites(root,rr,track)}
function all(){return Store.get('track_state',{})}function save(s){Store.set('track_state',s)}function st(s,track){s[track]=s[track]||{bookIndex:0,books:{},exerciseIndex:0,done:{},notes:{}};s[track].books=s[track].books||{};s[track].done=s[track].done||{};s[track].notes=s[track].notes||{};return s[track]}
function resume(root,track){const s=st(all(),track),b=BOOKS[track]||[],q=EXERCISE_PACKS[track]||[];root.append(card('Mode reprise '+(LABELS[track]||track),'Livre: '+(b[s.bookIndex]||'terminé')+' · Exercice: '+(q[s.exerciseIndex]||'terminé')))}
function books(root,rr,track){const state=all(),s=st(state,track),list=BOOKS[track]||[];const c=card('Livres / cours '+(LABELS[track]||track),'Un seul livre/cours actif. Renseigne le total, valide les pages faites, puis débloque le suivant.');list.forEach((name,i)=>{const p=s.books[name]||{current:0,total:0,done:false};const locked=i>s.bookIndex,done=p.done;const row=el('div',{class:'exercise '+(done?'ok':locked?'warn':'')});row.append(el('div',{class:'exercise-title'},(done?'✅ ':locked?'🔒 ':'📘 ')+name));row.append(el('div',{class:'small muted'},p.current+'/'+(p.total||'?')+' pages'));row.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pct(p.current,p.total)+'%'})));if(!locked&&!done){const total=input('total pages',p.total||''),add=input('+ pages','');row.append(el('div',{class:'row'},[total,add,el('button',{class:'btn',onclick:()=>{saveBook(state,s,track,name,+add.value||0,+total.value||0,false);toast('Progression sauvée');rr()}},'Valider pages'),el('button',{class:'btn green',onclick:()=>{saveBook(state,s,track,name,+add.value||0,+total.value||0,true);toast('Ressource terminée');rr()}},'Terminer et débloquer')]))}c.append(row)});root.append(c)}
function saveBook(state,s,track,name,delta,total,finish){const p=s.books[name]||{current:0,total:0,done:false};p.total=total||p.total||0;p.current=finish?(p.total||p.current+delta):p.current+delta;if(finish||(p.total&&p.current>=p.total)){p.done=true;s.bookIndex=Math.min((s.bookIndex||0)+1,(BOOKS[track]||[]).length)}s.books[name]=p;state[track]=s;save(state);Store.push('study_activity',{domain:track,kind:'book',title:name,delta,total:p.total,finished:p.done,date:Store.today()})}
function exercises(root,rr,track){const state=all(),s=st(state,track),q=EXERCISE_PACKS[track]||[];const c=card('Exercices '+(LABELS[track]||track),'Un exercice actif. Valide pour débloquer le suivant.');q.forEach((name,i)=>{const done=s.done[name],locked=i>s.exerciseIndex;const row=el('div',{class:'exercise '+(done?'ok':locked?'warn':'')});row.append(el('div',{class:'exercise-title'},(done?'✅ ':locked?'🔒 ':'🎯 ')+name));if(!locked&&!done){const note=el('input',{class:'input',placeholder:'note / erreur / preuve'});row.append(el('div',{class:'row'},[note,el('button',{class:'btn green',onclick:()=>{s.done[name]=true;s.notes[name]=note.value;s.exerciseIndex=Math.min(s.exerciseIndex+1,q.length);state[track]=s;save(state);Store.push('study_activity',{domain:track,kind:'exercise',title:name,note:note.value,date:Store.today()});toast('Exercice validé');rr()}},'Valider et débloquer')]))}c.append(row)});root.append(c)}
function sites(root,rr,track){const c=card('Sites utiles '+(LABELS[track]||track),'Ajout rapide au matériel si nécessaire.');(PRACTICE_SITES[track]||[]).forEach(x=>c.append(el('div',{class:'exercise'},[el('b',{},x[0]),el('div',{class:'small muted'},x[2]),el('button',{class:'btn',onclick:()=>{Store.push('study_materials',{course:track,source:'site',title:x[0],url:x[1],current:0,total:0,status:'active'});toast('Site ajouté') }},'Ajouter site')])));root.append(c)}
function input(p,v){return el('input',{class:'input',placeholder:p,type:'number',value:v,style:'max-width:150px'})}function pct(a,b){return b?Math.min(100,Math.round((+a||0)/(+b||1)*100)):0}
