import { renderEpfcYear1 } from './study-epfc.js';
import { renderTrack } from './study-track.js';
import { CERTS } from '../assets/js/data.js';
import { COURSES, SOURCES, TYPES, BOOKS, EXERCISE_PACKS, NL_PLAN, NL_RESOURCES } from '../assets/js/study-catalog.js';
import { EPFC_YEAR1 } from '../assets/js/epfc-year1.js';
import { EPFC_DAILY_ROTATION } from '../assets/js/practice-catalog.js';
import * as Store from '../assets/js/store.js';
import { el, card, subTabs, toast } from '../assets/js/ui.js';
let panel='resume';
export function renderStudy(root,rr){
 const tabs=[{id:'resume',label:'Reprise globale'},{id:'epfc',label:'EPFC N1'},{id:'coding',label:'Coding'},{id:'ai',label:'IA'},{id:'iot',label:'IoT'},{id:'repair',label:'Réparation'},{id:'materials',label:'Livres/Matériel'},{id:'exercises',label:'Exercices/Labs'},{id:'certs',label:'Certifs'},{id:'proofs',label:'Preuves'},{id:'nl',label:'NL / SELOR'}];
 root.append(subTabs(tabs,panel,id=>{panel=id;rr();}));const box=el('div');root.append(box);
 if(panel==='resume')return resume(box,rr);
 if(panel==='epfc')return renderEpfcYear1(box,rr);
 if(['coding','ai','iot','repair'].includes(panel))return renderTrack(box,rr,panel);
 ({materials,exercises,certs,proofs,nl}[panel]||materials)(box,rr)
}
function resume(root,rr){const g=el('div',{class:'grid'});g.append(todayMission(rr));g.append(epfcBox());['coding','ai','iot','repair'].forEach(k=>g.append(trackBox(k)));g.append(nlBox());g.append(certsBox());g.append(proofsBox());root.append(g);root.append(recentActivity())}
function todayMission(rr){const c=card('Mission étude maintenant','Ordre: EPFC du jour → NL → un parcours technique → preuve.','span-8');const d=Store.get('study_mission_'+Store.today(),{done:{}});missionItems().forEach(x=>{const ok=!!d.done[x.id];c.append(el('div',{class:'exercise '+(ok?'ok':'')},[el('b',{},x.title),el('div',{class:'small muted'},x.desc),el('button',{class:'btn '+(ok?'green':''),onclick:()=>{d.done[x.id]=!ok;Store.set('study_mission_'+Store.today(),d);Store.push('study_activity',{domain:'study_mission',kind:x.id,title:x.title,date:Store.today(),status:d.done[x.id]?'done':'open'});toast(d.done[x.id]?'Validé':'Rouvert');rr()}},ok?'Validé':'Valider')]))});return c}
function missionItems(){const ep=epfcToday();return[{id:'epfc',title:'EPFC du jour',desc:ep.code+' · '+ep.title+' → '+epfcResume(ep.code)},{id:'nl',title:'NL',desc:nlResume()},{id:'tech',title:'Technique',desc:pickTech()},{id:'proof',title:'Preuve',desc:'Sauver une preuve ou une note exploitable.'},{id:'review',title:'Review',desc:'Noter blocage et prochaine action.'}]}
function epfcBox(){const ep=epfcToday();return card('EPFC du jour',ep.code+' · '+ep.title+' → '+epfcResume(ep.code),'span-4')}
function trackBox(k){return card(k.toUpperCase(),trackResume(k),'span-4')}
function nlBox(){return card('NL / SELOR',nlResume(),'span-4')}
function certsBox(){const list=Store.get('certifications',[]);const active=list.filter(x=>x.status!=='passed');return card('Certifications',active.length?active.map(x=>x.name+' · '+(x.targetDate||'-')).join(' | '):'aucune cible active','span-4')}
function proofsBox(){const list=Store.get('proofs',[]).filter(x=>x.status!=='validated');return card('Preuves ouvertes',list.length?list.slice(0,5).map(x=>x.title).join(' | '):'aucune preuve ouverte','span-4')}
function recentActivity(){const c=card('Activité étude récente','Derniers logs.');Store.get('study_activity',[]).slice(-12).reverse().forEach(x=>c.append(el('div',{class:'exercise'},(x.date||'-')+' · '+(x.domain||'-')+' · '+(x.kind||x.status||'-')+' · '+(x.title||x.exercise||x.resourceId||'-'))));return c}
function epfcToday(){return courseByCode(EPFC_DAILY_ROTATION[new Date().getDay()%EPFC_DAILY_ROTATION.length])}function courseByCode(code){return EPFC_YEAR1.find(c=>c.code===code)||EPFC_YEAR1[0]}
function epfcResume(code){const st=Store.get('epfc_y1_state',{})[code]||{};const r=courseByCode(code).resources[st.activeIndex||0];if(!r)return'parcours terminé';const p=st.progress?.[r[0]]||{};return r[1]+' · '+(p.current||0)+'/'+(p.total||'?')+' '+r[3]}
function trackResume(k){const st=Store.get('track_state',{})[k]||{};return 'Livre: '+((BOOKS[k]||[])[st.bookIndex||0]||'terminé')+' · Exercice: '+((EXERCISE_PACKS[k]||[])[st.exerciseIndex||0]||'terminé')}
function pickTech(){const order=['coding','ai','iot','repair'];const k=order[new Date().getDay()%order.length];return k.toUpperCase()+' → '+trackResume(k)}
function nlResume(){const d=Store.get('nl_program',{level:'A1',target:'SELOR'});return d.level+' → '+d.target+' · Anki/écoute/phrases/corrections'}
function inp(p,t='text',v=''){return el('input',{class:'input',placeholder:p,type:t,value:v})}function sel(items,v=''){const s=el('select',{class:'input'});items.forEach(x=>s.append(el('option',{value:Array.isArray(x)?x[0]:x},Array.isArray(x)?x[1]:x)));s.value=v;return s}function cname(id){return (COURSES.find(x=>x[0]===id)||[id,id])[1]}function pc(a,b){return b?Math.min(100,Math.round(Number(a||0)/Number(b||1)*100)):0}
function materials(root,rr){const list=Store.get('study_materials',[]);const c=card('Livres / Matériel','Vue générale. EPFC, Coding, IA, IoT et Réparation ont aussi leur parcours séquentiel dédié.');const course=sel(COURSES),source=sel(SOURCES),title=inp('titre'),cur=inp('actuel','number'),total=inp('total','number'),url=inp('lien');c.append(el('div',{class:'row'},[course,source,title,cur,total,url]));c.append(el('button',{class:'btn green',onclick:()=>{Store.push('study_materials',{course:course.value,source:source.value,title:title.value,current:Number(cur.value||0),total:Number(total.value||0),url:url.value,status:'active'});toast('Matériel ajouté');rr()}},'Ajouter'));root.append(c);Object.entries(BOOKS).forEach(([k,arr])=>{const b=card('Pack livres · '+cname(k),'Ajout rapide.');arr.forEach(x=>b.append(el('button',{class:'btn',onclick:()=>{Store.push('study_materials',{course:k,source:k==='epfc'?'Syllabus':k==='nl'?'Livre NL':'O’Reilly',title:x,current:0,total:0,url:'',status:'active'});toast('Livre ajouté');rr()}},x)));root.append(b)});list.forEach(m=>{const r=card(m.title||'Matériel',cname(m.course)+' · '+m.source+' · '+pc(m.current,m.total)+'%');r.append(el('div',{class:'progress'},el('div',{class:'bar',style:'width:'+pc(m.current,m.total)+'%'})));r.append(el('div',{class:'row'},[el('button',{class:'btn',onclick:()=>{Store.updateList('study_materials',m.id,{current:Number(m.current||0)+1});rr()}},'+1'),el('button',{class:'btn',onclick:()=>{Store.updateList('study_materials',m.id,{current:Number(m.current||0)+10});rr()}},'+10'),el('button',{class:'btn green',onclick:()=>{Store.updateList('study_materials',m.id,{current:m.total,status:'done'});rr()}},'Terminé')]));root.append(r)})}
function exercises(root,rr){const list=Store.get('study_exercises',[]);const c=card('Exercices / Labs','Vue générale. Pour Coding/IA/IoT/Réparation, utilise leurs onglets dédiés pour la progression séquentielle.');const course=sel(COURSES),src=sel(SOURCES),type=sel(TYPES),title=inp('exercice / lab'),diff=sel(['easy','medium','hard','exam']),url=inp('lien');c.append(el('div',{class:'row'},[course,src,type,title,diff,url]));c.append(el('button',{class:'btn green',onclick:()=>{Store.push('study_exercises',{course:course.value,source:src.value,type:type.value,title:title.value,difficulty:diff.value,url:url.value,status:'todo',lesson:'',redoDate:''});toast('Exercice ajouté');rr()}},'Ajouter'));root.append(c);Object.entries(EXERCISE_PACKS).forEach(([k,arr])=>{const b=card('Pack exercices · '+cname(k),'Ajout rapide.');arr.forEach(x=>b.append(el('button',{class:'btn',onclick:()=>{Store.push('study_exercises',{course:k,source:k==='nl'?'SELOR/CNaVT':'Exercice plateforme',type:k==='nl'?'selor_prep':'exercise',title:x,difficulty:k==='nl'?'exam':'easy',url:'',status:'todo',lesson:'',redoDate:''});toast('Exercice ajouté');rr()}},x)));root.append(b)});list.forEach(x=>{const r=card(x.title||'Exercice',cname(x.course)+' · '+x.source+' · '+x.type+' · '+x.status);const lesson=inp('erreur / leçon','text',x.lesson||''),redo=inp('à refaire le','date',x.redoDate||'');r.append(el('div',{class:'row'},[lesson,redo,el('button',{class:'btn',onclick:()=>{Store.updateList('study_exercises',x.id,{status:'active',lesson:lesson.value,redoDate:redo.value});rr()}},'En cours'),el('button',{class:'btn green',onclick:()=>{Store.updateList('study_exercises',x.id,{status:'done',lesson:lesson.value,redoDate:redo.value});rr()}},'Validé')]));root.append(r)})}
function certs(root,rr){const list=Store.get('certifications',[]);const c=card('Certifications','Cibles + scores blancs.');const name=sel(CERTS),date=inp('date cible','date');c.append(el('div',{class:'row'},[name,date]));c.append(el('button',{class:'btn green',onclick:()=>{Store.push('certifications',{name:name.value,targetDate:date.value,status:'planned',scores:[]});toast('Certif ajoutée');rr()}},'Ajouter'));root.append(c);list.forEach(x=>{const r=card(x.name,'Statut: '+x.status+' · cible: '+(x.targetDate||'-'));const sc=inp('score %','number');r.append(el('div',{class:'row'},[sc,el('button',{class:'btn',onclick:()=>{Store.updateList('certifications',x.id,{scores:[...(x.scores||[]),{date:Store.today(),score:Number(sc.value||0)}]});rr()}},'Score'),el('button',{class:'btn green',onclick:()=>{Store.updateList('certifications',x.id,{status:'passed'});rr()}},'Réussie')]));root.append(r)})}
function proofs(root,rr){const list=Store.get('proofs',[]);const c=card('Preuves','Une compétence = une preuve exploitable.');const course=sel(COURSES),title=inp('preuve'),due=inp('échéance','date'),url=inp('lien preuve');c.append(el('div',{class:'row'},[course,title,due,url]));c.append(el('button',{class:'btn green',onclick:()=>{Store.push('proofs',{course:course.value,title:title.value,dueDate:due.value,evidenceUrl:url.value,status:'todo'});toast('Preuve ajoutée');rr()}},'Ajouter'));root.append(c);list.forEach(p=>{const r=card(p.title,cname(p.course)+' · '+p.status+' · '+(p.dueDate||'-'));r.append(el('div',{class:'row'},[el('button',{class:'btn green',onclick:()=>{Store.updateList('proofs',p.id,{status:'validated'});rr()}},'Valider'),el('button',{class:'btn',onclick:()=>{Store.updateList('proofs',p.id,{status:'active'});rr()}},'En cours')]));root.append(r)})}
function nl(root,rr){const d=Store.get('nl_program',{level:'A1',target:'SELOR',daily:{}});const c=card('Néerlandais / SELOR Command','Objectif final: réussir SELOR/Werkenvoor.be. Programme basé sur la liste du prof.');NL_PLAN.forEach(x=>c.append(el('div',{class:'exercise'},x[0]+' · '+x[1]+' · '+x[2])));const level=sel(['A1','A2','B1','B2','C1'],d.level),target=sel(['B2','C1','SELOR'],d.target),anki=inp('Anki cartes','number'),listen=inp('écoute min','number'),sent=inp('phrases','number'),err=inp('erreurs corrigées','number');c.append(el('div',{class:'row'},[level,target,anki,listen,sent,err]));c.append(el('button',{class:'btn green',onclick:()=>{d.level=level.value;d.target=target.value;d.daily[Store.today()]={anki:Number(anki.value||0),listeningMin:Number(listen.value||0),sentences:Number(sent.value||0),errors:Number(err.value||0)};Store.set('nl_program',d);toast('NL sauvé');rr()}},'Sauver NL'));root.append(c);const res=card('Ressources prof NL / SELOR','Bouton = ajouter au matériel ou ajouter entraînement.');NL_RESOURCES.forEach(r=>{const row=el('div',{class:'exercise'},[el('b',{},r.title),el('div',{class:'small muted'},r.kind+' · '+r.level+' · '+r.goal),el('div',{class:'row'},[el('button',{class:'btn',onclick:()=>{Store.push('study_materials',{course:'nl',source:r.kind,title:r.title,current:0,total:0,url:r.url,status:'active'});toast('Ressource NL ajoutée');rr()}},'Ajouter matériel'),el('button',{class:'btn green',onclick:()=>{Store.push('study_exercises',{course:'nl',source:r.kind,type:r.kind==='SELOR'?'selor_prep':'exercise',title:'Travailler: '+r.title,difficulty:r.level?.includes('B2')?'exam':'medium',url:r.url,status:'todo'});toast('Exercice NL ajouté');rr()}},'Ajouter exercice')])]);res.append(row)});root.append(res);Object.entries(d.daily||{}).slice(-10).forEach(([date,x])=>root.append(card(date,'Anki '+x.anki+' · écoute '+x.listeningMin+' min · phrases '+x.sentences+' · erreurs '+x.errors)))}
