import { AUTOMATIONS, BODY_SYSTEMS, CULTURE_DOMAINS, CULTURE_QUESTIONS, HEALTH_PILLARS, LEARNING_BOOKS, LEARNING_PATH, NAV, QUICK_ACTIONS } from '../content.js';
import { dailyQuestionIndex, dueCards, ensureState, euro, getDay, healthScores, learningStats, localDate, moneyStats, num, smartPlan, sportStats, tradingPhase, weeklyReview } from '../engine.js';
import { badge, button, checked, empty, esc, fieldGrid, formField, formatDate, formatTime, icon, iconButton, metric, numberInput, panel, progress, routeButton, scoreRing, selectInput, textInput, textarea, transactionRow } from '../ui.js';
const today = localDate;
import { pageHero } from './shared.js';
export function renderBody(raw) {
  const state = ensureState(structuredClone(raw));
  const stats = sportStats(state);
  const recent = [...state.sport.sessions].slice(-10).reverse().map(row=>`<div class="data-row"><div><b>${esc(row.type)}</b><small>${esc(row.date)} · ${num(row.durationMin)} min · RPE ${num(row.rpe)} · douleur ${num(row.pain)}/10</small></div><div class="row-end">${badge(row.status||'completed',row.pain>=6?'danger':'muted')}${iconButton('Supprimer','delete-record','trash',`data-path="sport.sessions" data-id="${esc(row.id)}"`)}</div></div>`).join('');
  return `${pageHero('CORPS & PERFORMANCE',stats.next,stats.pain>=6?'La douleur récente impose une séance légère et sans aggravation.':'Le prochain bloc est choisi automatiquement selon le cycle journalisé.',Math.min(100,Math.round(stats.sessions/Math.max(1,num(state.sport.weeklyTarget,4))*100)),'semaine',button('Journaliser séance','scroll-to','primary','data-target="session-log"')+button('Récupération','log-recovery','secondary'))}<div class="metrics-row">${metric('Séances',String(stats.sessions),'sept jours','','△')}${metric('Volume',`${stats.minutes} min`,'sept jours','','↟')}${metric('Douleur max',`${stats.pain}/10`,stats.pain>=6?'alléger':'stable',stats.pain>=6?'danger':'','!')}${metric('Dernière',stats.last?formatDate(stats.last.date):'—',stats.last?.type||'aucune','','✓')}</div><div class="layout-grid">${panel('Séance proposée',`<div class="session-prescription"><span>${esc(stats.next)}</span><h3>${stats.next==='Force'?'Mouvements contrôlés, progression mesurée et nuque neutre.':stats.next==='Cardio zone 2'?'Effort respiratoire soutenable, régulier, sans sprint.':stats.next==='Mobilité & tronc'?'Contrôle, amplitude sans douleur et stabilité.':stats.next==='Conditionnement'?'Intervalles modérés, technique avant intensité.':'Marche, mobilité et respiration.'}</h3><ul><li>Stop si faiblesse, engourdissement progressif ou douleur irradiée.</li><li>Journalise durée, RPE, douleur et preuve.</li><li>La séance suivante dépend de ce que tu enregistres réellement.</li></ul></div>`,{className:'span-5',eyebrow:'AUTOPROGRAMMATION'})}${panel('Journal de séance',`<div id="session-log">${fieldGrid([formField('Type',selectInput('sport-type',[['Force','Force'],['Cardio zone 2','Cardio zone 2'],['Mobilité & tronc','Mobilité & tronc'],['Conditionnement','Conditionnement'],['Récupération active','Récupération active']],stats.next)),formField('Durée',numberInput('sport-duration',stats.next==='Récupération active'?20:45,5,300,5)),formField('RPE',numberInput('sport-rpe',6,1,10,1)),formField('Douleur',numberInput('sport-pain',0,0,10,1))])}${formField('Preuve / résultat',textarea('sport-proof','','Ex. 4×8 à 60 kg, 32 min zone 2, douleur stable…',3))}<div class="actions">${button('Enregistrer la séance','save-sport','primary')}</div></div>`,{className:'span-7',eyebrow:'PREUVE',id:'session-log'})}${panel('Historique',recent?`<div class="data-list">${recent}</div>`:empty('Aucune séance enregistrée.'),{className:'span-12',eyebrow:'10 DERNIÈRES'})}</div>`;
}
