import { AUTOMATIONS, BODY_SYSTEMS, CULTURE_DOMAINS, CULTURE_QUESTIONS, HEALTH_PILLARS, LEARNING_BOOKS, LEARNING_PATH, NAV, QUICK_ACTIONS } from '../content.js';
import { dailyQuestionIndex, dueCards, ensureState, euro, getDay, healthScores, learningStats, localDate, moneyStats, num, smartPlan, sportStats, tradingPhase, weeklyReview } from '../engine.js';
import { badge, button, checked, empty, esc, fieldGrid, formField, formatDate, formatTime, icon, iconButton, metric, numberInput, panel, progress, routeButton, scoreRing, selectInput, textInput, textarea, transactionRow } from '../ui.js';
const today = localDate;
import { pageHero } from './shared.js';
export function moneySettings(state) {
  return `${fieldGrid([formField('Revenu mensuel',numberInput('money-income',state.money.settings.income||0,0,100000,10)),formField('Solde actuel',numberInput('money-balance',state.money.settings.openingBalance||0,-1000000,1000000,10)),formField('Épargne cible',numberInput('money-saving',state.money.settings.savingsTarget||0,0,100000,10)),formField('Fonds urgence',numberInput('money-emergency',state.money.settings.emergencyTarget||0,0,1000000,100))])}<div class="actions">${button('Sauver paramètres','save-money-settings','primary')}</div>`;
}

export function renderMoney(raw) {
  const state = ensureState(structuredClone(raw));
  const stats = moneyStats(state);
  const recent = [...state.money.transactions].slice(-12).reverse().map(row=>transactionRow(row,iconButton('Supprimer','delete-record','trash',`data-path="money.transactions" data-id="${esc(row.id)}"`))).join('');
  const recurring = state.money.recurring.map(row=>`<div class="data-row"><div><b>${esc(row.label)}</b><small>jour ${num(row.day,1)}</small></div><div class="row-end"><strong>${euro(row.amount)}</strong>${iconButton('Supprimer','delete-record','trash',`data-path="money.recurring" data-id="${esc(row.id)}"`)}</div></div>`).join('');
  const budgets = Object.entries(state.money.budgets||{}).map(([cat,limit])=>`<div class="data-row"><div><b>${esc(cat)}</b><small>${euro(stats.byCategory[cat]||0)} dépensés</small></div><div class="row-end"><strong>${euro(limit)}</strong>${badge((stats.byCategory[cat]||0)>limit?'Dépassé':'OK',(stats.byCategory[cat]||0)>limit?'danger':'good')}</div></div>`).join('');
  return `${pageHero('ARGENT',euro(stats.forecast),'Prévision après charges fixes, dépenses enregistrées et épargne.',stats.alerts.length?45:85,'contrôle',button('Ajouter mouvement','scroll-to','primary','data-target="transaction"')+button('Capture rapide','quick-action','secondary','data-quick="expense"'))}<div class="metrics-row">${metric('Revenu',euro(num(state.money.settings.income)+stats.income),'ce mois','','€')}${metric('Charges fixes',euro(stats.recurring),'mensuel','','↘')}${metric('Dépenses',euro(stats.expenses),stats.month,stats.alerts.length?'danger':'','−')}${metric('Épargne',euro(stats.savings),`cible ${euro(state.money.settings.savingsTarget)}`,'','＋')}</div><div class="layout-grid">${panel('Ajouter une transaction',`<div id="transaction">${fieldGrid([formField('Date',`<input id="tx-date" type="date" value="${today()}">`),formField('Type',selectInput('tx-type',[['expense','Dépense'],['income','Revenu'],['saving','Épargne']],'expense')),formField('Catégorie',textInput('tx-category','','Courses, voiture…')),formField('Montant',numberInput('tx-amount','',0,1000000,.01))])}${formField('Note',textInput('tx-note','','Facultatif'))}<div class="actions">${button('Ajouter','add-transaction','primary')}</div></div>`,{className:'span-7',eyebrow:'CAPTURE RÉELLE',id:'transaction'})}${panel('Paramètres',moneySettings(state),{className:'span-5',eyebrow:'BASE'})}${panel('Budgets',`${fieldGrid([formField('Catégorie',textInput('budget-category','','Courses')),formField('Limite',numberInput('budget-limit','',0,100000,.01))])}<div class="actions">${button('Sauver budget','save-budget','secondary')}</div><div class="data-list compact">${budgets||empty('Aucun budget configuré.')}</div>`,{className:'span-6',eyebrow:`${stats.alerts.length} ALERTE(S)`})}${panel('Charges récurrentes',`${fieldGrid([formField('Nom',textInput('rec-label','','Loyer')),formField('Montant',numberInput('rec-amount','',0,100000,.01)),formField('Jour',numberInput('rec-day',1,1,31,1))])}<div class="actions">${button('Ajouter charge','add-recurring','secondary')}</div><div class="data-list compact">${recurring||empty('Aucune charge récurrente.')}</div>`,{className:'span-6',eyebrow:'AUTOMATISATION'})}${panel('Historique',recent?`<div class="data-list">${recent}</div>`:empty('Aucune transaction.'),{className:'span-12',eyebrow:'12 DERNIÈRES'})}</div>`;
}
