import { AUTOMATIONS, BODY_SYSTEMS, CULTURE_DOMAINS, CULTURE_QUESTIONS, HEALTH_PILLARS, LEARNING_BOOKS, LEARNING_PATH, NAV, QUICK_ACTIONS } from '../content.js';
import { dailyQuestionIndex, dueCards, ensureState, euro, getDay, healthScores, learningStats, localDate, moneyStats, num, smartPlan, sportStats, tradingPhase, weeklyReview } from '../engine.js';
import { badge, button, checked, empty, esc, fieldGrid, formField, formatDate, formatTime, icon, iconButton, metric, numberInput, panel, progress, routeButton, scoreRing, selectInput, textInput, textarea, transactionRow } from '../ui.js';
const today = localDate;
import { pageHero } from './shared.js';
export function renderSettings(raw) {
  const state = ensureState(structuredClone(raw));
  const backupRows = [];
  const automations = AUTOMATIONS.map(([id,label,detail])=>`<label class="setting-row"><div><b>${esc(label)}</b><small>${esc(detail)}</small></div><input type="checkbox" class="switch" data-setting="automation" data-key="${esc(id)}" ${checked(state.nexus.automation[id])}></label>`).join('');
  const widgets = Object.entries(state.nexus.widgets).map(([id,value])=>`<label class="setting-row"><div><b>Widget ${esc(id)}</b><small>Visible sur Aujourd’hui</small></div><input type="checkbox" class="switch" data-setting="widget" data-key="${esc(id)}" ${checked(value)}></label>`).join('');
  return `${pageHero('RÉGLAGES','Ton système, tes données, zéro surcouche.','Les changements visuels et automatiques sont appliqués immédiatement.',null,'',button('Exporter données','export-data','primary','', 'download')+button('Créer backup','create-backup','secondary'))}<div class="layout-grid">${panel('Interface',`${fieldGrid([formField('Thème',selectInput('setting-theme',[['graphite','Graphite'],['oled','OLED noir'],['light','Clair']],state.ui.theme)),formField('Densité',selectInput('setting-density',[['comfortable','Confort'],['compact','Compact']],state.ui.density)),formField('Objectif principal',selectInput('setting-goal',[['balanced','Équilibre complet'],['energy','Énergie et santé'],['learning','Apprentissage et culture'],['body','Corps et performance'],['money','Argent et stabilité']],state.nexus.onboarding.goal)),formField('Prénom / nom court',textInput('setting-name',state.nexus.onboarding.name||'','Facultatif'))])}<div class="actions">${button('Appliquer','save-settings','primary')}</div>`,{className:'span-6',eyebrow:'DESIGN'})}${panel('Automatisations',`<div class="settings-list">${automations}</div>`,{className:'span-6',eyebrow:'NEXUS'})}${panel('Widgets Aujourd’hui',`<div class="settings-list">${widgets}</div>`,{className:'span-6',eyebrow:'PERSONNALISATION'})}${panel('Données',`<div class="data-actions">${button('Exporter JSON','export-data','secondary','', 'download')}<label class="file-button">${icon('upload')}<span>Importer JSON</span><input id="import-file" type="file" accept="application/json"></label>${button('Annuler dernière modification','undo','quiet','', 'undo')}${button('Réinitialiser complètement','reset-app','danger')}</div><div class="medical-note">Les exports contiennent les données saisies localement. Ne partage pas un export contenant des informations sensibles.</div>${backupRows.join('')}`,{className:'span-6',eyebrow:'LOCAL-FIRST'})}${panel('Audit architecture V7',`<div class="audit-list"><div><span>✓</span><p>Un seul runtime JavaScript.</p></div><div><span>✓</span><p>Un seul routeur et un seul gestionnaire de clics.</p></div><div><span>✓</span><p>Aucun MutationObserver pour réécrire les écrans.</p></div><div><span>✓</span><p>Données V6 conservées dans le store existant.</p></div><div><span>✓</span><p>Actions tactiles de 48 px minimum.</p></div><div><span>✓</span><p>PWA hors ligne avec cache versionné.</p></div></div>`,{className:'span-12',eyebrow:'CE QUI CHANGE VRAIMENT'})}</div>`;
}
