import { AUTOMATIONS, BODY_SYSTEMS, CULTURE_DOMAINS, CULTURE_QUESTIONS, HEALTH_PILLARS, LEARNING_BOOKS, LEARNING_PATH, NAV, QUICK_ACTIONS } from '../content.js';
import { dailyQuestionIndex, dueCards, ensureState, euro, getDay, healthScores, learningStats, localDate, moneyStats, num, smartPlan, sportStats, tradingPhase, weeklyReview } from '../engine.js';
import { badge, button, checked, empty, esc, fieldGrid, formField, formatDate, formatTime, icon, iconButton, metric, numberInput, panel, progress, routeButton, scoreRing, selectInput, textInput, textarea, transactionRow } from '../ui.js';
const today = localDate;
import { pageHero } from './shared.js';
export function renderTrading(raw) {
  const state = ensureState(structuredClone(raw));
  const phase = tradingPhase(state);
  const setup = state.trading.setup||{};
  const recent = [...state.trading.trades].slice(-8).reverse().map(row=>`<div class="data-row"><div><b>${esc(row.date)} · ${esc(row.setup||'setup')}</b><small>${esc(row.market)} · ${num(row.contracts)} contrat(s) · risque ${euro(row.risk)}</small></div><div class="row-end"><strong class="${num(row.pnl)>=0?'positive-text':'negative-text'}">${num(row.pnl)>=0?'+':''}${euro(row.pnl)}</strong>${iconButton('Supprimer','delete-record','trash',`data-path="trading.trades" data-id="${esc(row.id)}"`)}</div></div>`).join('');
  const stages = [['Setup unique',phase.index>0],['100 backtests',phase.index>1],['Simulation propre',phase.index>2],['2 mocks',phase.index>3],['Revue règles',phase.index>4]];
  return `${pageHero('TRADING GUIDÉ',phase.title,phase.detail,phase.progress,'étape',button('Aller à l’action','scroll-to','primary','data-target="trading-action"')+button('Voir données','scroll-to','secondary','data-target="trading-history"'))}<div class="layout-grid">${panel('Parcours',`<div class="stage-list">${stages.map(([label,done],i)=>`<article class="stage ${done?'done':i===phase.index?'active':''}"><span>${done?'✓':i+1}</span><b>${label}</b></article>`).join('')}</div>`,{className:'span-12',eyebrow:'UNE ÉTAPE À LA FOIS'})}${panel('Action actuelle',phase.index===0?`${fieldGrid([formField('Nom du setup',textInput('trade-setup-name',setup.name||'','Ex. rejet de niveau')),formField('Marché',textInput('trade-market',setup.market||'MNQ','MNQ')),formField('Session',textInput('trade-session',setup.session||'New York AM','New York AM'))])}${formField('Règles complètes',textarea('trade-rules',setup.rules||'','Contexte, déclencheur, stop, objectif, non-trade…',5))}<div class="actions">${button('Sauver setup unique','save-trading-setup','primary')}</div>`:phase.index===1?`${fieldGrid([formField('Nombre de cas',numberInput('backtest-samples',10,1,500,1)),formField('Durée',numberInput('backtest-minutes',45,5,300,5))])}${formField('Résultat',textarea('backtest-note','','Ce que les données montrent, sans changer les règles.',4))}<div class="actions">${button('Ajouter le backtest','add-backtest','primary')}</div>`:phase.index===2?`${fieldGrid([formField('Date',`<input id="trade-date" type="date" value="${today()}">`),formField('Contrats',numberInput('trade-contracts',1,1,100,1)),formField('Risque',numberInput('trade-risk',state.trading.risk?.riskPerTrade||100,1,100000,.01)),formField('P&L',numberInput('trade-pnl','',-1000000,1000000,.01))])}${formField('Décision / preuve',textarea('trade-note','','Contexte, entrée, stop, sortie, erreur…',3))}<div class="actions">${button('Journaliser simulation','add-sim-trade','primary')}</div>`:`<div class="mock-box"><h3>${phase.title}</h3><p>${phase.detail}</p><p>Le dashboard conserve les données mais ne remplace jamais le règlement officiel de la firme.</p></div>`,{className:'span-7',eyebrow:'MAINTENANT',id:'trading-action'})}${panel('Règles personnelles',`${fieldGrid([formField('Risque / trade',numberInput('risk-per-trade',state.trading.risk?.riskPerTrade||100,1,100000,.01)),formField('Stop journalier',numberInput('risk-daily',state.trading.risk?.dailyStop||250,1,100000,.01)),formField('Trades max',numberInput('risk-count',state.trading.risk?.maxTrades||3,1,100,1)),formField('Pertes consécutives',numberInput('risk-losses',state.trading.risk?.maxConsecutiveLosses||2,1,20,1))])}<div class="actions">${button('Sauver garde-fous','save-risk','secondary')}</div>`,{className:'span-5',eyebrow:'SURVIE'})}${panel('Trades récents',recent?`<div class="data-list">${recent}</div>`:empty('Aucun trade simulé.'),{className:'span-12',eyebrow:'AUDIT',id:'trading-history'})}</div>`;
}
